### ISSUE TITLE
Update lightbox doc

### ISSUE THREAD

**Issue by JBeater** [MurhafSousli/ngx-gallery#103]
In https://github.com/MurhafSousli/ngx-gallery/wiki/Lightbox is LIghtBoxModule defined as :

```
import { GalleryLightbox } from  '@ngx-gallery/lightbox';
GalleryLightbox.forRoot(lightboxConfig?)
```

but when i installed newest version it is invalid because lightbox export module is called LightboxModule.

Update it to :

```
import {LightboxModule} from  '@ngx-gallery/lightbox';
LightboxModule.forRoot(lightboxConfig?)
```

**Comment by MurhafSousli** [comment]
Updated
