### ISSUE TITLE
Cannot use custom gallery config while using the lightbox

### ISSUE THREAD

**Issue by JBeater** [MurhafSousli/ngx-gallery#104]
Hi, i use in my project ng-gallery in some components. The problem is with config ... i cant set up specific config for gallery-ref, it still using global.

I try both ways:

```
            this.gallery.ref('single-image-gallery', Config).load([this.imageItem]);
            this.gallery.ref('single-image-gallery').setConfig(Config);
```
Config look like:
```
Config: GalleryConfig = {
    gestures: false,
    loop: false,
    etc.....
};
```
But it not work. Am I doing something wrong or is there a bug?
For info: Angular version 6.

**Comment by MurhafSousli** [comment]
Hi @JBeater, You can change the global config

```ts
GalleryModule.forRoot(config)
```

Or you can set a custom config to a gallery on initializing

```ts
let newGalleryRef = this.gallery.ref('single-image-gallery', config)
```

But if `single-image-gallery` ref is already created, the function `ref()` will just return it and won't set the config, so use the following instead:

```
let galleryRef = this.gallery.ref('single-image-gallery');
galleryRef.setConfig(config);
```

**Comment by JBeater** [comment]
I tried it.

```
        this.galleryRef = this.gallery.ref('single-image-gallery');
        this.galleryRef.setConfig(SingleImageGalleryConfig);
        this.galleryRef.add(this.imageItem);
        this.lightBox.open(0, 'single-image-gallery',ZfSingleImageLightBoxConfig);
```

But it still using global config instead of local :(

**Comment by MurhafSousli** [comment]
@JBeater Can you reproduce it in this [stackbltiz](https://stackblitz.com/edit/ngx-gallery)

**Comment by JBeater** [comment]
@MurhafSousli  here: [try it!](https://stackblitz.com/edit/ngx-gallery-jpjjz6?file=app%2Fissuecomponent%2Fissuecomponent.component.ts)

**Comment by MurhafSousli** [comment]
Now I see, the lightbox is resetting the gallery ref config

**Comment by CosmoFruit** [comment]
also when:
this.gallery.ref('1', this.config).load(items);
this.lightbox.open( this.currIndex, '1');

show broken style: 
1. default config 
![default](https://user-images.githubusercontent.com/28723724/41717492-9770e262-7562-11e8-8f93-28dc84d0f1e5.png)
2.in lightbox no dots 
![default](https://user-images.githubusercontent.com/28723724/41717510-a3f070f2-7562-11e8-9fc0-97d0069d6df1.png)
3. after closed lightbox gallery config is broke
![default](https://user-images.githubusercontent.com/28723724/41717534-b313d24a-7562-11e8-9160-600550804d39.png)
