### ISSUE TITLE
Lightbox fullscreen on mobile style issue

### ISSUE THREAD

**Issue by JBeater** [MurhafSousli/ngx-gallery#107]
Hi fullscreen on mobile still looks bad.

I see your old issue [Fix](https://github.com/MurhafSousli/ngx-gallery/pull/102/commits/f3ea544ec6a9fa3323d0dc347e1a036755b563ee) which is merged. Style work fine, but when i test it on mobile device it isn't applied, **For now i copy it into my project global styles and all work fine on android/IOS,** Can you please fix it.

Version before my fix:

<img src="https://user-images.githubusercontent.com/22459590/41536927-44a587de-7307-11e8-86ea-be1b3c93f885.jpg" width="300px"/>

<img src="https://user-images.githubusercontent.com/22459590/41536923-424a4024-7307-11e8-93ab-58f8ff9d4c83.png" width="300px"/>

**Can be your issue:** 
After my fix is there second close button or part of it.

<img src="https://user-images.githubusercontent.com/22459590/41538449-b7eefe42-730b-11e8-89e1-296311a82ef1.png" width="300px"/>

**Comment by MurhafSousli** [comment]
Did you try to remove the `.fullscreen` class from the ligthbox

**Comment by dodomui** [comment]
Version 11.0.0, the close button may overlap with status bar while running with native ionic App.
