### ISSUE TITLE
Close lightbox on router changes

### ISSUE THREAD

**Issue by JBeater** [MurhafSousli/ngx-gallery#108]
On android is back button, on IOS it is swipe from the left to right site. When you open lightbox gallery on fullscreen mode and click on back button(android) you are navigated back in history but lightboxis still opened. On IOS back swipe hide lightbox, make back action, and show lightbox again.

**Comment by MurhafSousli** [comment]
I cannot understand what is the issue, please fill the issue template when you are submitting an issue, provide screenshots or stackblitz if possible

**Comment by JBeater** [comment]
Go into own site https://murhafsousli.github.io/ngx-gallery/#/ use navigate menu for example basic, then mixed, then advanced and lightbox. On lightbox page open fullscreen and pres back button... What happen? You was navigated to previous page(in your site) and gallery is still open, That isn't normal reaction when ppl devices like mobile use back button to close.

Back button:

![image](https://user-images.githubusercontent.com/22459590/41557729-d83e4f4e-733e-11e8-8165-b5aebda7e36d.png)

IOS back. swipe:
![image](https://user-images.githubusercontent.com/22459590/41557772-f4f66536-733e-11e8-95ed-fb135980534d.png)

**Comment by MurhafSousli** [comment]
Ok, I got it now, the lightbox is not closing when router changes
you can use the router event to close it manually
```ts
const lightboxRef = this.lightbox.ref();

this.router.events.pipe(
  filter((event) => event instanceof NavigationEnd),
  take(1),
  tap(() => lightboxRef.close())
).subscribe();
```
Will add this as an enchancement in the next release
