### ISSUE TITLE
'gallery' is not a known element

### ISSUE THREAD

**Issue by CosmoFruit** [MurhafSousli/ngx-gallery#111]
**Describe the bug**
when i use     
<gallery id="ex1" [items]="items" thumbPosition="left"></gallery>
in lazyload module template
  
 Uncaught Error: Template parse errors:'gallery' is not a known element

**To Reproduce**
1.  import { GalleryModule } from  '@ngx-gallery/core';

@NgModule({
 imports: [
    GalleryModule.forRoot(config?)
 ]
})
2.  in Routes = [
       { path: '', loadChildren: `/index/index.module#IndexModule` }
     ]
3.  in IndexModule in Routes = [
    {
        path: '',
        component: PageIndexComponent
    }
];
4. in index.component.html   try to use <gallery id="ex1" [items]="items" thumbPosition="left"></gallery>
and get the error  Uncaught Error: Template parse errors:'gallery' is not a known element

**Expected behavior**
gallery should work

**Comment by MurhafSousli** [comment]
Just add `GalleryModule` to `index.module.ts`
