### ISSUE TITLE
Allow custom template from scratch

### ISSUE THREAD

**Issue by ayazhussein** [MurhafSousli/ngx-gallery#125]
Hello, 
Since 3.0.0, is there a way to pass an observable as src image since I have to generate signedUrl from the API, before we could've implement custom image component and it worked.

Open to suggestions :D

**Comment by MurhafSousli** [comment]
@ayazhussein I think you can!

You can define the template, check this [stackbltiz](https://stackblitz.com/edit/ngx-gallery-rkjs8y?file=src%2Fapp%2Fapp.component.html)

```ts
this.items = [
   new ImageItem({ srcObservable: of(item.srcUrl), thumb: item.previewUrl })
]
```
```html
<gallery [items]="items" [itemTemplate]="itemTemplate"></gallery>

<ng-template #itemTemplate let-data=data>

   <!-- Custom logic goes here -->

  <img [src]="data.srcObservable | async">
</ng-template>
```
