### ISSUE TITLE
 Object(...) is not a function

### ISSUE THREAD

**Issue by CosmoFruit** [MurhafSousli/ngx-gallery#129]
new version is not compatible with Angular 5.* ?

#### What is the current behavior?

ncaught TypeError: Object(...) is not a function
    at eval (ngx-gallery-core.js:573)
    at eval (ngx-gallery-core.js:575)
    at Object../node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js (vendor.bundle.js:567)

#### Which versions are you using for the following packages?

Angular: 5.2.5
Angular CLI: 1.7.0
Typescript: 2.6.2
Gallery:  3.0.1

**Comment by MurhafSousli** [comment]
To use the latest version, you will need to upgrade to Angular 6. otherwise use `2.1.1`

**Comment by udayasindhu** [comment]
I'm using Angular 6 and Gallery version is 5.0.0. I'm facing the same issue. Can you please suggest the version for Angular 6 ?
