### ISSUE TITLE
 galleryRef.setConfig() not worked

### ISSUE THREAD

**Issue by CosmoFruit** [MurhafSousli/ngx-gallery#130]
Gallery 3.0.1
reproduce in home.component
https://stackblitz.com/edit/ngx-gallery-zucrva

**Comment by MurhafSousli** [comment]
When the gallery component is first initialized, it initializes the config from the defaults. so you should set the config after the view is initialized.

Here you go https://stackblitz.com/edit/ngx-gallery-jkti9o?file=src/app/home/home.component.ts
```ts
  ngAfterViewInit() {
    const galleryRef = this.gallery.ref('basic-test');
    galleryRef.setConfig(this.config);
  }
```
