### ISSUE TITLE
Undefined artefact in thumb

### ISSUE THREAD

**Issue by CosmoFruit** [MurhafSousli/ngx-gallery#132]
if src for thumb is failed we look this:
![default](https://user-images.githubusercontent.com/28723724/42375365-fe777788-8123-11e8-9d7e-e6e839455c7e.png)

![default](https://user-images.githubusercontent.com/28723724/42375375-0ef42606-8124-11e8-92ad-11d521206857.png)

can you fix undefined text in html?

(fall back and blue contur is my custom template)

#### Which versions are you using for the following packages?

Gallery: 3.0.1

**Comment by MurhafSousli** [comment]
This undefined isn't caused by thumb src failure, it is about the `loadingIcon` that is undefined, anyway you can use CSS
```scss
gallery-thumb {
   .g-loading {
       display: none;
   }
}
```
