### ISSUE TITLE
Loading icon shows undefined in some cases on mobile

### ISSUE THREAD

**Issue by JBeater** [MurhafSousli/ngx-gallery#133]
Hi i have issue with loading state of fullscreen gallery. It happens only on mobile devices and i dont know what is bad. I try to simulate it on stackblitz but unsuccessfully. All angular/ng-gallery packages are updated to newest version. 
When i open lightbox as soon as possible and there is a lot of pictures with HQ i see undefined in thumbs and sometimes in main screen where is loading animation, then it is changed from undefined to loading animation and then to image.

Is this loading state some svg /icon/image loaded from external resource, is there any style which i can overide and replace loading icon with own and fix this my problem? I dont want hide loading state, i want it but no 'undefined' text.

<img src="https://user-images.githubusercontent.com/22459590/42409269-33a9db3a-81d8-11e8-85fa-9abd6fd450d6.png" width="250" height="400"/>

**Comment by MurhafSousli** [comment]
@JBeater Did you add thumbnail src path? please show your usage code

**Comment by JBeater** [comment]
As i write i cant simulate it at stackblitz, here is preview but you cant see it there: https://stackblitz.com/edit/ngx-gallery-25aj25?file=src%2Fapp%2Fhome%2Fhome.component.ts

Yea i added thumb url, how i write it happens .. undefined -> loading -> image.. so there is maybe problem with loading of loading icon if it is external resource.

**Comment by MurhafSousli** [comment]
Both `gallery-item` and `gallery-thumb` use the same component `gallery-image` which displays the loading icon and then load the image.

The SVG loading icon is not coming from an external source, it is defined in the `GalleryConfig` as an inline data. which should load immediatly.

The weird thing is that in your screenshot, the loading icon works properly in the `gallery-item` but shows **undefined** in `gallery-thumb`. it just doesn't make sense!

I test it on samsung galaxy S4 chrome and iphone 6 both safari and chrome and I couldn't see the issue.

Anyway, CSS can be used to hide it, see #132
