### ISSUE TITLE
Auto detect images inside a component

### ISSUE THREAD

**Issue by eyalhakim** [MurhafSousli/ngx-gallery#136]
#### What is the expected behavior?
When gallerize is defined in a container of multiple components each containing an image the images should be detected.

#### What is the current behavior?
Images inside components are not detected

#### What are the steps to reproduce?
```html
<div gallerize>
  // this component contains an image
  <my-component *ngFor="let i of components"></my-component>
</div>
```

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Typescript:
Gallery:

**Comment by MurhafSousli** [comment]
Did you try use the selector input?
```html
<div  gallerize selector="my-component">
  <my-component *ngFor="let i of components">
</div>
`

**Comment by eyalhakim** [comment]
I ended up implementing it with the lightbox service manually but i thought that the selector is suppose to be of the element containing the src. Isn't that so?

**Comment by MurhafSousli** [comment]
gallerize is very simple, first you give the selector, if it is an `img` tag it uses the src, else it uses the background image. 

```html
<div gallerize>
  <my-component *ngFor="let i of components">
      <img [src]="src"/>
   </my-component>
</div>

 <!-- or -->

<div gallerize selector=".img-background">
  <my-component *ngFor="let i of components">
      <div class="img-background" [style.background]="'url(' + src + ')'"/>
   </my-component>
</div>
```
But anyway loading the image in the lightbox manually is not a bad idea!

**Comment by MurhafSousli** [comment]
Thanks!
