### ISSUE TITLE
Gallery Module not working with angular 6

### ISSUE THREAD

**Issue by christopulimoottil** [MurhafSousli/ngx-gallery#137]
ERROR in node_modules/ng-gallery/components/gallery-player/gallery-player.component.d.ts(4,10): error TS2305: Module '"E:/@Projects/GIthub/Delnie/Hostel/Hostel Website/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-gallery/components/gallery-slider/gallery-slider.component.d.ts(2,10): error TS2305: Module '"E:/@Projects/GIthub/Delnie/Hostel/Hostel Website/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/ng-gallery/components/gallery-thumb/gallery-thumb.component.d.ts(4,10): error TS2305: Module '"E:/@Projects/GIthub/Delnie/Hostel/Hostel Website/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-gallery/directives/lazy.directive.d.ts(2,10): error TS2305: Module '"E:/@Projects/GIthub/Delnie/Hostel/Hostel Website/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ng-gallery/services/gallery.service.d.ts(2,10): error TS2305: Module '"E:/@Projects/GIthub/Delnie/Hostel/Hostel Website/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/ng-gallery/services/gallery.service.d.ts(3,10): error TS2305: Module '"E:/@Projects/GIthub/Delnie/Hostel/Hostel Website/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

**Comment by MurhafSousli** [comment]
Fill the issue template
