### ISSUE TITLE
Cannot find 'galleryConfig?' when added to @ngModule !

### ISSUE THREAD

**Issue by jaasmaz** [MurhafSousli/ngx-gallery#140]
// this is my app.model.ts file //
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { GalleryModule } from  '@ngx-gallery/core';
import { LightboxModule } from  '@ngx-gallery/lightbox';
import { GallerizeModule } from  '@ngx-gallery/gallerize';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    GalleryModule.forRoot(galleryConfig?),
    LightboxModule.forRoot(lightboxConfig?),
    GallerizeModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
---------------------------------------------------
// This is my app.component.ts file //
import { Component, OnInit} from '@angular/core';
import { GalleryItem, ImageItem, Gallery } from '@ngx-gallery/core';
import { Lightbox } from '../../node_modules/@ngx-gallery/lightbox';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  images: GalleryItem[];

  ngOnInit() {
    // Set gallery items array
    this.images = [
      new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
      new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
      new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
      new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
      new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
    ];
  }
}
-------------------------------------
//this is my app.component.html file
<gallery [items]="images"></gallery>
---------------------------------------------

#### What is the expected behavior?
why the gallery is not working ?!!

**Comment by MurhafSousli** [comment]
Please fill the issue template properly, include the versions

**Comment by jaasmaz** [comment]
This is my app.model.ts file 
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { GalleryModule } from '@ngx-gallery/core';
import { LightboxModule } from '@ngx-gallery/lightbox';
import { GallerizeModule } from '@ngx-gallery/gallerize';

import { AppComponent } from './app.component';

@NgModule({
declarations: [
AppComponent
],
imports: [
BrowserModule,
BrowserAnimationsModule,
GalleryModule.forRoot(galleryConfig?),
LightboxModule.forRoot(lightboxConfig?),
GallerizeModule
],
providers: [],
bootstrap: [AppComponent]
})
export class AppModule { }
```
This is my app.component.ts file

``` 
import { Component, OnInit} from '@angular/core';
import { GalleryItem, ImageItem, Gallery } from '@ngx-gallery/core';
import { Lightbox } from '../../node_modules/@ngx-gallery/lightbox';

@component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})
export class AppComponent {
images: GalleryItem[];

ngOnInit() {
// Set gallery items array
this.images = [
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
];
}
}
```
This is app.component.html File
```
<gallery [items]="images">
```
#### What is the expected behavior?
The gallery should work

#### What is the current behavior?
it is showing no error  when i run ng serve but when i open localhost its just a white page !!

#### What are the steps to reproduce?



#### Which versions are you using for the following packages?

Angular: 6.0.9
Angular CDK: 6.3.3
Angular CLI: 6.0.8
Typescript: 2.7.2
Gallery: ^3.0.2


#### Is there anything else we should know?
[Ts] error in app.module.ts on 
GalleryModule.forRoot(galleryConfig?), and 
LightboxModule.forRoot(lightboxConfig?), it says cannot find name galleryConfig
