### ISSUE TITLE
it shows nothing but white screen when i run this

### ISSUE THREAD

**Issue by jaasmaz** [MurhafSousli/ngx-gallery#142]
This is my app.model.ts file 
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { GalleryModule } from '@ngx-gallery/core';
import { LightboxModule } from '@ngx-gallery/lightbox';
import { GallerizeModule } from '@ngx-gallery/gallerize';

import { AppComponent } from './app.component';

@NgModule({
declarations: [
AppComponent
],
imports: [
BrowserModule,
BrowserAnimationsModule,
GalleryModule.forRoot(galleryConfig?),
LightboxModule.forRoot(lightboxConfig?),
GallerizeModule
],
providers: [],
bootstrap: [AppComponent]
})
export class AppModule { }
```
This is my app.component.ts file

``` 
import { Component, OnInit} from '@angular/core';
import { GalleryItem, ImageItem, Gallery } from '@ngx-gallery/core';
import { Lightbox } from '../../node_modules/@ngx-gallery/lightbox';

@component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})
export class AppComponent {
images: GalleryItem[];

ngOnInit() {
// Set gallery items array
this.images = [
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
new ImageItem({src: 'https://preview.ibb.co/jrsA6R/img12.jpg', thumb: 'https://preview.ibb.co/jrsA6R/img12.jpg' }),
];
}
}
```
This is app.component.html File
```
<gallery [items]="images">
```
#### What is the expected behavior?
The gallery should work

#### What is the current behavior?
it is showing no error  when i run ng serve but when i open localhost its just a white page !!

#### Which versions are you using for the following packages?

Angular: 6.0.9
Angular CDK: 6.3.3
Angular CLI: 6.0.8
Typescript: 2.7.2
Gallery: ^3.0.2

#### Is there anything else we should know?

**Comment by MurhafSousli** [comment]
@jaasmaz You got it wrong, as I mentioned in #140, this line of code does not make sense

```ts
GalleryModule.forRoot(galleryConfig?),
LightboxModule.forRoot(lightboxConfig?),
```

I wrote it in the demo to highlight that the function `forRoot()` can accept an optional parameter for the config in case you want to set a default config for all galleries. but it is not used this way, check the [Gallery API](https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-service-api)

Just keep like this and it should work

```ts
GalleryModule.forRoot(),
LightboxModule.forRoot(),
```

I recommend you to compare your code with the [stackblitz](https://stackblitz.com/edit/ngx-gallery) and use the documentation from the [wiki](https://github.com/MurhafSousli/ngx-gallery/wiki)

**Comment by MurhafSousli** [comment]
@jaasmaz I haven't tested it, if the fix worked let me know so I can publish a new version :)
