### ISSUE TITLE
Import gallery components styles individually

### ISSUE THREAD

**Issue by magoss** [MurhafSousli/ngx-gallery#144]
I've got a problem with implementing basic example. I followed code example shown on your page regarding Gallery:
https://murhafsousli.github.io/ngx-gallery/#/gallery

#### What is the expected behavior?
I'd like to display gallery in any way.

#### What is the current behavior?
Following code example from documentation seems to not work. Isn't documentation out-of-date, is it?

#### What are the steps to reproduce?
Check stackblitz out here:
https://stackblitz.com/edit/angular-cu7ygs?file=src/app/app.component.ts

#### Which versions are you using for the following packages?

Angular: 6.1.0
Angular CDK:  6.4.1
Angular CLI: 6
Typescript:
Gallery: 3.0.2

**Comment by MurhafSousli** [comment]
@magoss Where is the issue? the gallery is working in your stackblitz!

**Comment by magoss** [comment]
I tracked the problem. It was the matter of place of import styles. I wanted to do it in component styles, but it works only in global file. It's mentioned in docs, you are right, but in my opinion it's a little bit optimization problem, because you have to import whole styles of gallery no matter user decide to load appropriate component.

**Comment by MurhafSousli** [comment]
@magoss The styles aren't huge, their size combined are less than 4.5kb
But if you are too concerned about the extra styles. you can create SCCS file and copy the styles that you use only but you won't save more than 2kb at max

**Comment by MurhafSousli** [comment]
No, currently it has to be loaded globally, did you try copy&paste gallery styles into your lazy component styles instead?

**Comment by magoss** [comment]
Nope. I'm not prefer that way, because I'd like to be compliant with your new library versions. Failure to comply may cause problems with i.e. Angular upgrade.

**Comment by magoss** [comment]
I mean I'm afraid of copying code manually, because your library breaking changes could prevent me from smooth upgrade of ngx-gallery. If adapting breaking changes of your library would be required to be compliant with i.e the next version of Angular (which I encountered while working with other library) - it could potentially cause serious troubles for us.
