### ISSUE TITLE
'undefined' printed in place of loading indicator on thumbnail

### ISSUE THREAD

**Issue by kamisbox** [MurhafSousli/ngx-gallery#150]
#### What is the expected behavior?

I should see loading indicator on thumb items when loading takes perceptible amount of time.

#### What is the current behavior?

Currently I see text 'undefined' on thumb items which load long enough.

#### What are the steps to reproduce?

* Set gallery background to white.
* Point thumbnail source to slowly responding resource or use 'Slow 3G' network preset.

#### Known workaround.

Add loading indicator svg via `.g-loading` class `backound-image`.

**Comment by MurhafSousli** [comment]
@kamisbox I have pushed a beta version, can you test it and tell me if the issue has been resolved. I also prepared a [stacbklitz](https://stackblitz.com/edit/ngx-gallery-bux4bg)
