### ISSUE TITLE
Gallery image is not visible when it loads longer than 300 ms

### ISSUE THREAD

**Issue by kamisbox** [MurhafSousli/ngx-gallery#151]
#### What is the expected behavior?

Images should appear on gallery even if their load time is longer than 300 ms.

#### What is the current behavior?

Gallery appears blank until I tap on any thumbnail other than first.

#### What are the steps to reproduce?

Load big images on slow network settings.

**Comment by dpinheiro** [comment]
I'm having the same problem, first image is never loaded

**Comment by MurhafSousli** [comment]
@kamisbox  It seems that this is only happening when `thumbPosition` is set to `left` or `right`, can you confirm this on your end?

**Comment by MurhafSousli** [comment]
This has nothing to do with loading images, but when the `thumbPosition` is set to `left` or `right` the clientWidth of its parent element is 0

**Comment by MurhafSousli** [comment]
@dpinheiro @kamisbox  I just pushed a beta version, please check it and tell me if the issue has been resolved. I also prepared a [stacbklitz](https://stackblitz.com/edit/ngx-gallery-bux4bg?file=src%2Fapp%2Fhome%2Fhome.component.ts) with the beta version
