### ISSUE TITLE
Generated CSS files should be moved to a different directory

### ISSUE THREAD

**Issue by vially** [MurhafSousli/ngx-gallery#153]
#### What is the expected behavior?

Importing the `sass` files should work as expected.

#### What is the current behavior?

Importing any `sass` file (e.g.: `@import '~@ngx-gallery/core/styles/lightbox';`) throws error:

```
It's not clear which file to import for @ngx-gallery/core/styles/lightbox. Candidates:
Candidates:
  @ngx-gallery/core/styles/lightbox.scss
  @ngx-gallery/core/styles/lightbox.css
Please delete or rename all but one of these files.
````

#### What are the steps to reproduce?

Trying to import any `scss` file from the `styles` directory without specifying the `.scss` extension results in the error mentioned above. This is because `node-sass` does not support having both `.css` and `.scss` files in the same directory: [node-sass#1222](https://github.com/sass/node-sass/issues/1222)

#### What is the use-case or motivation for changing an existing behavior?

Being able to import the `.scss` file without throwing any errors. 

#### Which versions are you using for the following packages?

Angular: 5.2.10
Angular CDK: 5.2.4
Angular CLI: N/A
Typescript: 2.6.2
Gallery: 2.2.1

#### Is there anything else we should know?

Moving the generated `.css` files to a different directory should fix this issue.

**Comment by MurhafSousli** [comment]
@vially I tried it without the extension and it worked! like in [here](https://stackblitz.com/edit/ngx-gallery?file=src%2Fstyles.scss)

**Comment by vially** [comment]
I can see most of the examples where it works are using `angular-cli`. I'm testing it in an ionic project (which is not using angular-cli) and it fails with the above error.

I suppose ionic and angular-cli might have a different configuration for handling sass imports (it looks like angular-cli is using webpack `sass-loader` while ionic [is not](https://github.com/ionic-team/ionic-app-scripts/blob/master/src/sass.ts)).

Ideally this project should support both (e.g.: by not generating the CSS files in the same directory), but if that's not possible adding a note about this issue to the documentation might help.

**Comment by MurhafSousli** [comment]
Ionic 4 uses angular cli, I think it should be working there too

**Comment by vially** [comment]
It's still not working and I don't expect it will until it's fixed in either:
- `ngx-gallery` by moving the generated CSS files to a different directory
- `libsass` by removing support for inline CSS imports [libsass#2611](https://github.com/sass/libsass/issues/2611)
- `ionic` by moving to `angular-cli` (which will happen in ionic 4)
