### ISSUE TITLE
Display captions in Lightbox

### ISSUE THREAD

**Issue by cur3n4** [MurhafSousli/ngx-gallery#155]
#### What is the expected behavior?
Ability to display captions when viewing images in Lightbox.

#### What is the current behavior?
There is no way to display a caption about the image.

#### What are the steps to reproduce?
-

#### What is the use-case or motivation for changing an existing behavior?
It would be great to be able to show captions on the Lightbox, however there doesn't seem to be a way to pass a custom template for the Lightbox.

#### Which versions are you using for the following packages?

Angular: 6.1.0
Angular CDK: 6.4.1
Angular CLI: 6
Typescript:
Gallery: 3.0.2

**Comment by MurhafSousli** [comment]
It is very similar to the advanced example, you just need to set the item template using the `GalleryRef`

```html
<!-- Add custom template to image items -->

<ng-template #itemTemplate let-data="data">
  <span [@youCanAddAnimation] class="item-text">
    {{data?.textProperty}}
  </span>
</ng-template>
```
```ts

@ViewChild('itemTemplate') itemTemplate: TemplateRef<any>;

  constructor(public gallery: Gallery, public lightbox: Lightbox) {
  }

  ngOnInit() {
    // get the gallery ref of the lightbox and set its item template
     this.gallery.ref('lightbox').setConfig({
        itemTemplate: this.itemTemplate
     });
   }

  openLightbox() {
     this.lightbox.open();
  }
}
```

Here is a [stackblitz](https://stackblitz.com/edit/ngx-gallery-w3bna7?file=src%2Fapp%2Fhome%2Fhome.component.ts)

**Comment by cur3n4** [comment]
Brilliant! Thanks a lot.

**Comment by bcwhite-code** [comment]
I don't know if things have changed since 2018 but I can't create a `new ImageItem()` with additional properties.  Even creating a derived type and casting it `as ImageItemData` breaks `load()`.  However, this works for me:

```
    for (let img of this.images) {
        gallery.addImage({
            src:   this.urlPrefix + img + "/full",
            thumb: this.urlPrefix + img + "/thumb",
            caption: img,  // testing; replace with real caption
        } as ImageItemData)
    }
```

**Comment by FiniteLooper** [comment]
This does not seem to work any more.  Passing an item template to a lightbox doesn't do anything.  I'm using Angular 16.1.2 and ng-gallery 10.0.0

```html
<ng-template #lightboxTemplate let-data="data">
  <span class="item-text">
    About this image: {{data?.alt}}
  </span>
</ng-template>

<img *ngFor="let item of items; index as i"
     [lightbox]="i"
     [src]="item.data.thumb"
     [alt]="item.data.alt" />
```

```ts
@ViewChild('lightboxTemplate') lightboxTemplate: TemplateRef<HTMLElement>;

items: ImageItem[] = [
  new ImageItem({
    src: 'https://example.com/img1.jpg',
    thumb: 'https://example.com/img1-thumb.jpb',
    alt: 'My alt text',
  }),
];

constructor(public gallery: Gallery) {}

ngOnInit() {
  const lightboxRef = this.gallery.ref();

  lightboxRef.setConfig({
    itemTemplate: this.lightboxTemplate
  })

  lightboxRef.load(this.items);
}
```


@bcwhite-code did you get this to work?

**Comment by FiniteLooper** [comment]
For anyone finding this in 2023 or later, apparently an `itemTemplate` must be set in the `ngAfterViewInit` event, **NOT** `ngOnInit` or else it doesn't exist yet!
