### ISSUE TITLE
Customization of the way of displaying images

### ISSUE THREAD

**Issue by magoss** [MurhafSousli/ngx-gallery#156]
#### What is the expected behavior?
To broaden a range of possible usage - it'd be useful to make it configurable how images are displayed in gallery. For carousel or slider it's totally acceptable to show images with background-size set to cover (which causes cutoffs). As a image reviewer it'd be better to avoid cutoffs (at the top and bottom). Is it possible to make this property configurable by an input property (with options `cover `and `contain`? 

#### What is the current behavior?
So far the following class is responsible for displaying images that way.:

```
.g-image-item {
  background-size: cover;
}
```

The only method to change that behaviour is to set global styling as follows: 

```
#my-attachments-gallery {
  .g-image-item {
    background-size: contain;
  }
}
```

#### Which versions are you using for the following packages?

Angular: 6.0.3
Angular CDK: 6.4.1
Angular CLI: 6.x
Typescript: 2.9.2
Gallery: 3.0.2

**Comment by MurhafSousli** [comment]
have you forgot about `::ng-deep` ? in component style
```scss
:host {
  ::ng-deep {
     .g-image-item {
        background-size: contain;
     }
   }
}
```
will add this as component input next update

**Comment by MurhafSousli** [comment]
in **v3.1.0** and above, you can use `imageSize` that accepts either `cover` or `contain`

```
<gallery imageSize="contain"></gallery>
```
