### ISSUE TITLE
Vertical scroll is not working on gallery on touch device

### ISSUE THREAD

**Issue by kamisbox** [MurhafSousli/ngx-gallery#161]
#### What is the expected behavior?

Vertical scroll on mobile device is not prevented.

#### What is the current behavior?

Gallery prevents vertical scrolling on mobile devices with hammerjs.

#### What are the steps to reproduce?

Open https://murhafsousli.github.io/ngx-gallery/#/gallery, switch to mobile mode in dev console, scroll down to the gallery.

#### Workaround with its own downsides exists

Set `Hammer.defaults.touchAction = 'pan-y';`. Issues with this approach: 
* this is global config
* horizontal gallery changes to the next slide when user scrolls up or down

**Comment by MurhafSousli** [comment]
Thanks for sharing the workaround! If anyone has a solution without the side effect, please let me know

**Comment by priatelko** [comment]
@kamisbox How can i implement this solution into angular project? I do not understand that, how can I make an access for Hammer
