### ISSUE TITLE
Left / right arrows bug on android

### ISSUE THREAD

**Issue by bastienlemaitre** [MurhafSousli/ngx-gallery#174]
Hi,
I developed a website and i use your LightBox for the pictures.
Everything work on Desktop but a problem appear on Android, cant use left / right arrows.
Any idea ?
Check it on mobile : https://rueduparticulier.com/realty/1, then click on picture.
Thanks.

**Comment by MurhafSousli** [comment]
Hi @bastienlemaitre, The navigation buttons actually work, try the demo https://ngx-gallery.stackblitz.io on the same android device. I think there is a performance issue with your app which is blocking the clicks from working
