### ISSUE TITLE
Not working with Angular 6 + 

### ISSUE THREAD

**Issue by Chethannp** [MurhafSousli/ngx-gallery#175]
[ng] @import '~@ngx-gallery/core/styles/gallery';
[ng] ^
[ng]       File to import not found or unreadable: ~@ngx-gallery/core/styles/gallery.
[ng]       in C:\Users\Chethan\Pictures\flockby-web\src\theme\variables.scss (line 1, column 1)
[ng] ERROR in src/app/app.module.ts(21,10): error TS2305: Module '"C:/Users/Chethan/Pictures/flockby-web/node_modules/@ngx-gallery/lightbox/ngx-gallery-lightbox"' has no exported member 'GalleryLightbox'.
[ng] i ｢wdm｣: Failed to compile.
[ng] i ｢wdm｣: Compiling...
[ng] Date: 2018-08-18T08:06:35.598Z - Hash: 3d9993a28dd44f961b14 - Time: 2105ms
[ng] 4 unchanged chunks
[ng] chunk {styles} styles.js, styles.js.map (styles) 35.2 kB [initial] [rendered]
[ng] i ｢wdm｣: Compiled successfully.
[ng] ERROR in src/app/app.module.ts(21,10): error TS2305: Module '"C:/Users/Chethan/Pictures/flockby-web/node_modules/@ngx-gallery/lightbox/ngx-gallery-lightbox"' has no exported member 'GalleryLightbox'.
Terminate batch job (Y/N)?

![2018_08_15_13_44_45_ionic_app](https://user-images.githubusercontent.com/7566931/44297464-9413a900-a2ef-11e8-9e78-8408ac017075.png)

**Comment by MurhafSousli** [comment]
Closing as it does not follow the template issue

**Comment by Chethannp** [comment]
@MurhafSousli - Hi I am not sure on how to use this with Ionic 4 and angular latest can you please help me?
