### ISSUE TITLE
How to Use this with Ionic 4?

### ISSUE THREAD

**Issue by Chethannp** [MurhafSousli/ngx-gallery#176]
I am getting #175 error

**Comment by Chethannp** [comment]
Can you please respond ??

**Comment by MurhafSousli** [comment]
@Chethannp You have to fill the template issue properly! add the versions and the code you used, I am not a magician to guess what is going on in your project

**Comment by Chethannp** [comment]
Oh oh sorry if that was way to quick. I am trying to use your plugin in the latest ionic 4 project.  I just started a new Ionic 4 project (https://beta.ionicframework.com/docs/installation/cli/) and followed the steps mentioned in the repo, that is it nothing else.

**Comment by Chethannp** [comment]
#178
