### ISSUE TITLE
AOT compilation breaks gallery config

### ISSUE THREAD

**Issue by den-luschitsky** [MurhafSousli/ngx-gallery#181]
I use ngx-gallery in several places on site. i have global config for each gallery.
In app.module.ts:
`GalleryModule.forRoot(galleryConfig)`

my config (galleryConfig):
```
{
  loadingStrategy: 'preload' as 'preload',
  gestures: true,
  thumb: false,
  counter: false,
  dots: true,
  // loop: false,
}
```

#### What is the expected behavior?

AOT compilation does not breaks global gallery config.

#### What is the current behavior?

After AOT compilation global config was ignored, gallery was initialized with default settings.
I have try to set config manually and it solves issue:
`this.gallery.galleryRef.setConfig(config)`

with JIT compilation all works as expected.

#### What are the steps to reproduce?

1. create simple gallery
2. set global config 
2. Compile app in AOT mode
3. check gallery config

#### Which versions are you using for the following packages?

Angular: 6.1.3
Angular CDK: 6.4.5
Angular CLI: 6.1.4
Typescript: 2.9.2
Gallery: 3.1.0

**Comment by MurhafSousli** [comment]
What is the error? I think you are mistaken other plugin error with this one, I tried the config but it works in AOT

**Comment by den-luschitsky** [comment]
hm. there are no errors. just broken the gallery config.
![image](https://user-images.githubusercontent.com/3027056/44407551-1659d280-a567-11e8-87e7-1c00c2b2d6cd.png)

I mean that my config says `thumb: false, dots: true,`, but the gallery was rendered with thumbnails and without dots.

when i try to set config through `this.gallery.galleryRef.setConfig(config)` all works as expected, without thumbnails and with dots.

![image](https://user-images.githubusercontent.com/3027056/44408144-73a25380-a568-11e8-94d3-04286962f106.png)

So, config that was applied as `GalleryModule.forRoot(galleryConfig)` does not work in AOT mode.
Only `this.gallery.galleryRef.setConfig(config)` definition works for AOT.

For JIT both variants work perfectly.

Also, i'm using the `Lightbox` module. I tried to remove it, but global config still ignored.


Sorry for my English :)

**Comment by MurhafSousli** [comment]
@den-luschitsky I could not reproduce your issue! I need a reproduction for the issue in order to fix it.
