### ISSUE TITLE
Add imageSize as an input so it can be used in lightbox mode

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-gallery#183]

**Comment by MurhafSousli** [comment]
@aardvark79 because the default `imageSize` is contain :)

**Comment by aardvark79** [comment]
I may be missing something, but I've tried both 'cover' and 'contain' and both settings have a 'cover' effect - there doesn't appear to be any change regardless of the value used. Like I said I could be missing something, though. I'll try to set up a stackblitz in the morning.
