### ISSUE TITLE
Double Click / Touch on thumbs to get the slide.

### ISSUE THREAD

**Issue by KartoffelToby** [MurhafSousli/ngx-gallery#188]
Must double click or tap on mobile to trigger the event on thumbnails
+ Havy loadtime when > 300 Images

Angular: 6.0.3
Angular CDK: 6.4.7
Angular CLI: 6.1.5
Typescript: 2.7.2
Gallery: 3.1.1

**Comment by MurhafSousli** [comment]
Hi @KartoffelToby I am sorry I didn't notice this issue until now!

Currently the gallery renders the `gallery-item` component for all the items you add and loads the images according to the `loadingStrategy` option, so when you add 300 items, that's a lot! adding 300 empty components will still have impact on performance!.

I don't see a use case for adding even 50 images! I mean do you expect the user to slider over 300 images?

I recommend you to use 20 items at a time
