### ISSUE TITLE
TypeError: Cannot read property 'subscribe' of null

### ISSUE THREAD

**Issue by amjadalfawal** [MurhafSousli/ngx-gallery#189]
when clicking on the open lightbox  button
![image](https://user-images.githubusercontent.com/37481122/45202394-8e233f00-b281-11e8-9add-ca6b897d8709.png)

when I comment this line its back to work  
![image](https://user-images.githubusercontent.com/37481122/45202451-bca11a00-b281-11e8-83f5-1cd7dd00efbc.png)

what is the problem?  

Angular: 6.0.3
Angular CDK: 6.4.7
Angular CLI: 6.1.5
Typescript: 2.7.2
Gallery: 3.1.1

**Comment by MurhafSousli** [comment]
Can you reproduce the error in a [stackblitz](https://stackblitz.com/edit/ngx-gallery)?

**Comment by amjadalfawal** [comment]
https://stackblitz.com/edit/angular-yqubfh

**Comment by amjadalfawal** [comment]
APP url :https://angular-yqubfh.stackblitz.io

**Comment by MurhafSousli** [comment]
In **v3.1.2** You don't have to import the `RouterModule`
