### ISSUE TITLE
Angular 5 support with v2.1.1?

### ISSUE THREAD

**Issue by kgriffiths** [MurhafSousli/ngx-gallery#191]
#### What is the expected behavior?
Expected that Gallery will work with Angular 5, by using v2.1.1 of Gallery

#### What is the current behavior?
The thumbnail view appears only, without the main image, arrows, or counter
![image](https://user-images.githubusercontent.com/5571766/45651125-78422500-ba9e-11e8-9d33-38a6327e0cbe.png)

#### What are the steps to reproduce?
Stackblitz: https://stackblitz.com/edit/angular-trbz2n

#### What is the use-case or motivation for changing an existing behavior?
N/A / Support of Angular 5

#### Which versions are you using for the following packages?

Angular: 5.2.11
Angular CDK: 5.2.5
Angular CLI: 1.7.4 locally (unsure which version stackblitz is using)
Typescript: 2.4.2 locally (unsure which version stackblitz is using)
Gallery: 2.1.1

**Comment by MurhafSousli** [comment]
in v2.1.1 You must give a height 

```html
<gallery [items]="slidesPreview" [style.height.px]="500"></gallery>
```

**Comment by kgriffiths** [comment]
Awesome, thanks for your time!
