### ISSUE TITLE
Youtube videos in a lightbox (full screen)

### ISSUE THREAD

**Issue by galampi** [MurhafSousli/ngx-gallery#194]
I am trying to play a Youtube/Brightcove videos inside of a Lightbox.  I am wondering if the ngx-gallery is capable of doing this?  All I could find were examples of static images (for lightbox, not gallery).  

I really like the gallery, by the way, so thank you :-)

**Comment by MurhafSousli** [comment]
Yes, you can! here is a [stackblitz](https://stackblitz.com/edit/ngx-gallery-xe4tu6?file=src/app/home/home.component.html)
