### ISSUE TITLE
Make thumbnails slider infinite

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-gallery#195]
If anyone is interested, PRs are welcome

**Comment by mbtestfeed** [comment]
What do you mean by this, exactly? Provided there's enough items in the set you'll see ```[ setsize[-2], setsize[-1], setsize[0], setsize[1], setsize[2] ]``` on load, so it looks like it wraps all the way around?

**Comment by MurhafSousli** [comment]
Yupp

**Comment by MurhafSousli** [comment]
This would require a new version written from scratch, closing for now
