### ISSUE TITLE
How should we control the size of the images/Videos

### ISSUE THREAD

**Issue by Mythrim** [MurhafSousli/ngx-gallery#196]
I am not able to control the height of images/videos through normal CSS in my custom template. Please help me regarding how to change the default height of the images/videos rendered using this library.

**Comment by ashu07** [comment]
Got the same Issue. We can overwrite the CSS in our app but that's not the best practice.

> **Can we add Enhance the feature to customize the height and width also?** 

That would be very nice to have.

**Comment by MurhafSousli** [comment]
@Mythrim I did not get it! what are you trying to accomplish?
I am not sure if I understood but the images/videos are set to fill the gallery height

You can change the height of the gallery, like:
```css
gallery {
   height: 600px;
}
```
The styles for other parts of the gallery can overwritten with CSS the same way.
