### ISSUE TITLE
Do not require importing global styles

### ISSUE THREAD

**Issue by olaf89** [MurhafSousli/ngx-gallery#197]
#### What is the expected behavior?
I would like to use Gallery without importing styles globally.

#### What is the current behavior?
I have to import styles globally, 

#### What is the use-case or motivation for changing an existing behavior?

I have a application with many different modules, only one of them which is for administrators is using gallery. I would like to be able to use gallery only in this module without impacting other modules. I do not want to copy styles cause i would like to have smooth upgrades to newer versions.

**Comment by MurhafSousli** [comment]
fixed in `v3.2.0`
