### ISSUE TITLE
Build of applications using 'strictNullChecks and ngx-gallery as dependency fails

### ISSUE THREAD

**Issue by GasiorowskiPiotr** [MurhafSousli/ngx-gallery#201]
Once we run production build of our application with 'strictNullChecks' parameter set to true (which is a kind of requirement for us), typescript compiler throws error like this:
"ERROR in ngx-gallery-core.d.ts.ɵh.html(2,28): : Object is possibly 'undefined'.". 

We identified the cause and possible solution (in most cases - handle null propagation in Angular templates)

#### What is the expected behavior?
Compiling application with ngx-gallery as npm dependency and with 'strictNullChecks' TS config option should not fail.

#### What is the current behavior?
Compiling application with ngx-gallery as npm dependency and with 'strictNullChecks' TS config option fails

#### What are the steps to reproduce?
1. Create empty angular project with @angular/material dependency
2. Set 'strictNullChecks' parameter to true in tsconfig.app.json
3. Run ng build --prod
4. Observe compile errors

#### What is the use-case or motivation for changing an existing behavior?
We would like to use ngx-gallery as npm package and compile our project with 'strictNullChecks'

#### Which versions are you using for the following packages?

Angular: 6.1.0
Angular CDK: 6.4.7
Angular CLI: 6.1.1
Typescript: 3.0.1
Gallery: 3.1.2

**Comment by olaf89** [comment]
"strictNullChecks" is a configuration inside compilerOptions
So it should be
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": [],
"strictNullChecks": true
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by MurhafSousli** [comment]
@olaf89 @GasiorowskiPiotr 
This seems to be a known bug in the Angular CLI, [#21390](https://github.com/angular/angular/issues/21390)

**Comment by ivanblazevic** [comment]
@MurhafSousli this is not a bug of CLI but of this library, possible undefined objects are not handled properly inside the template.

"Bug" of CLI is that it takes also libraries into consideration when it does strictNullChecks which is in one way a good thing for such cases as we have here.

@olaf89 @GasiorowskiPiotr @elvirdolic
Here is another report of the same problem:
https://github.com/MurhafSousli/ngx-gallery/issues/82

and fix
https://github.com/MurhafSousli/ngx-gallery/pull/83/files

Unfortunately, until this is not recognized as a problem I'll need to maintain my fork of this library.

**Comment by elvirdolic** [comment]
It’s pitty that codeowner doesn’t recognize this and is not willing to
accept an existing PR. But ok. Otherwise this lib is fantastic.

Blaz <notifications@github.com> schrieb am Fr. 25. Jän. 2019 um 14:47:

**Comment by MurhafSousli** [comment]
@ivanblazevic @elvirdolic If the main guy developing the angular cli himself is saying it is a bug and that he is waiting for the core team to add it to the backlog!

![image](https://user-images.githubusercontent.com/8130692/51751198-53e9fb00-20c5-11e9-8648-e03183c3fe87.png)

![image](https://user-images.githubusercontent.com/8130692/51751241-6fed9c80-20c5-11e9-9927-36aac4d9c48b.png)


It is a bug and it is still open, like many other bugs opened on Angular CLI!

**Comment by elvirdolic** [comment]
I totally understand your point and it’s a bug in the angular core backlog.
Because of the low impact and a low number of libs which have this issue in
their code base they don’t have priority/pressure on that. It’s up to you
to decide on that. I don’t expect that angular team will fix this soon.

Br

Murhaf Sousli <notifications@github.com> schrieb am Fr. 25. Jän. 2019 um
15:20:

**Comment by MurhafSousli** [comment]
@elvirdolic To be honest with you, I already have a newer version for this plugin and couldn't complete it because of my job, therefore do not expect a fix any time soon, I am sorry

You can still include the source code in your app and use it!
