### ISSUE TITLE
Image URLs with spaces in do not load in the Lightbox component

### ISSUE THREAD

**Issue by mbrookson** [MurhafSousli/ngx-gallery#208]
#### What is the expected behavior?
Images should always be displayed in a Lightbox.

#### What is the current behavior?
When an image url contains a space the images do not appear in the Lightbox.

#### What are the steps to reproduce?
Try to load an image with a space in the image name.
I have test with plain `<img>` tags and both 'example-image.png' and 'example image.png' load correctly. When there is a space the browser automatically encodes the URL to be 'example%20image.png', however this doesn't load in the Lightbox component.

#### Which versions are you using for the following packages?

Angular: ^6.0.0
Angular CDK: ^6.4.7 
Angular CLI: ^6.0.0
Typescript: ^2.7.2
Gallery: ^3.1.2

**Comment by MurhafSousli** [comment]
@mbrookson please add a [repro stackblitz](https://stackblitz.com/edit/ngx-gallery)

**Comment by MurhafSousli** [comment]
Just wrap the source URL with `encodeURI(src)`
