### ISSUE TITLE
Add custom button on top of lightbox

### ISSUE THREAD

**Issue by alanclayson** [MurhafSousli/ngx-gallery#217]
#### What is the expected behavior?
Possibility to add custom buttons on lightbox top to do some actions as download, rotate, upload, etc. Could be a custom template as "itemTemplate" and "thumbTemplate"

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Typescript:
Gallery:

**Comment by MurhafSousli** [comment]
We cannot include such features in the core package, currently you can use any third party library that adds functionalities to the image item, This example uses [ngx-imageviewer](https://github.com/hallysonh/ngx-imageviewer) which has rotate and zoom features
[stackblitz example](https://stackblitz.com/edit/ngx-gallery-imageviewer?file=src%2Fapp%2Fhome%2Fhome.component.html)

**Comment by MurhafSousli** [comment]
You can accomplish this with CSS

Try
```xml
<gallery>
    <my-controls></my-controls>
</gallery>
```
or
```xml
<gallery></gallery>
<my-controls></my-controls>
```
Both should work, just play with CSS positioning

**Comment by Amitshaale** [comment]
`<div class="gallery" class="gallery">
            <div class="row">
              <div class="col media-margin" *ngFor="let gallery of libraryHome?.gallery; index as i"
                [ngClass]="{'col-lg-4': libraryHome?.gallery.length > 1}" [lightbox]="i">
                <a class="item" *ngIf="gallery.type == 'image'">
                  <img src="{{gallery.thumbnail}}" style="max-width: 100%;"
                    onError="this.onerror=null; this.src='assets/img/placeholder.png';" download />
                </a>
                <a class="item" *ngIf="gallery.type == 'video'">
                  <img src="{{gallery.thumbnail}}" style="max-width: 100%;"
                    onError="this.onerror=null; this.src='assets/img/placeholder.png';" />
                </a>
              </div>
            </div>
          </div>`


I HAVE THIS CODE HOW TO ADD DOWNLOAD OPTION FOR IMAGE PLEASE HELP...
