### ISSUE TITLE
GalleryModule.forRoot(config) - config problem....

### ISSUE THREAD

**Issue by bobingham** [MurhafSousli/ngx-gallery#219]
I install using yarn, import the library following instructions and then add the following line to the imports array:
`GalleryModule.forRoot(config)`
and I get "cannot find name 'config'".
Where and what is the config object?
If I omit it I have the following error:
```
StaticInjectorError(RootModule)[InjectionToken galleryConfig]: 
  StaticInjectorError(Platform: core)[InjectionToken galleryConfig]: 
    NullInjectorError: No provider for InjectionToken galleryConfig!

```

**Comment by bobingham** [comment]
My media component is in a lazy-loaded module. 
GalleryModule.forRoot(config)
should be placed in the app root module and again in the lazy-loaded module to get it to work.
Great work, by the way!

**Comment by MurhafSousli** [comment]
Config is optional variable to set the config, just remove `config` and it will work
