### ISSUE TITLE
Enable videos

### ISSUE THREAD

**Issue by eestein** [MurhafSousli/ngx-gallery#22]
Hi, nice library. I was just testing it, but there's one feature I'm missing. 
Is there any way you'd consider adding video playback? i.e: from YouTube/Vimeo.

Thanks

**Comment by MurhafSousli** [comment]
Hi @eestein, thanks. Yes, I have this on my radar

**Comment by magoss** [comment]
Is it now possible to present video in the ngx-gallery? Could you indicate any tips / code example? I cannot see docs regarding it.

**Comment by MurhafSousli** [comment]
@magoss It is right [here](https://github.com/MurhafSousli/ngx-gallery/wiki/Mixed-Content-Usage)
