### ISSUE TITLE
Too much of transition delay in opening the images via lightgallery

### ISSUE THREAD

**Issue by Chethanpremkumar** [MurhafSousli/ngx-gallery#224]
#### What is the expected behavior?
It loads super fast on web but on ionic 4 android version it is very slow.

#### What is the current behavior?
Lightbox is loading very slowly

#### What are the steps to reproduce?
I have created a screen recorder for your info. 
https://drive.google.com/open?id=0B0kKLNspClIBSDF5X0QwVVJ3eW9iaXluN0xBc3JjQW1JOXhR
  
Steps to reproduce:
Kindly install ionic4 version and add ngx-gallery plugin to it, then build an apk version to reproduce.
Fyi: https://beta.ionicframework.com/docs/publishing/play-store

**Comment by Chethannp** [comment]
Can you please quote an example of the usage which you think can solve the problem :)

**Comment by MurhafSousli** [comment]
I really don't know, but I am working on a new version that will solve performance issues (no due date).
