### ISSUE TITLE
EXIF orientation Configuration

### ISSUE THREAD

**Issue by cvbc2010** [MurhafSousli/ngx-gallery#225]
When images are uploaded based on EXIF metadata in base64 encoded images.

#### What is the expected behavior?
Images should be oriented automatically when src is provided as base64.

#### What is the current behavior?
Images are not getting oriented as per EXIF

#### What are the steps to reproduce?
providing base64 encoded content as src for images

#### Which versions are you using for the following packages?

Angular:6.1.6
Angular CDK:6.4.7
Angular CLI:6.1.6
Typescript:2.9.2
Gallery: 3.1.2

**Comment by MurhafSousli** [comment]
I am not sure do you mean by oriented automatically! can you reproduce your issue in a [stackblitz](https://stackblitz.com/edit/ngx-gallery)?

**Comment by cvbc2010** [comment]
https://stackblitz.com/edit/ngx-gallery-bvf95v

please check the above example

**Comment by MurhafSousli** [comment]
@cvbc2010 your example is working fine! where is the problem?

**Comment by cvbc2010** [comment]
the image should be rotated to portrait. As the orientation specified for that image is 6 -> rotate 90degrees

**Comment by MurhafSousli** [comment]
I cannot understand you, what rotation and what orientation? you gave me exactly the same stackblitz without reproduction, are you trolling. closing as not an issue

**Comment by cvbc2010** [comment]
can you check the same stackblitz example above. somehow my changes were not saved. I am not trolling. and i was trying to fix this for a long time.

**Comment by MurhafSousli** [comment]
Your issue is not part of this plugin, you can first fix your image with a rotation function then add it to the gallery
 
https://stackoverflow.com/questions/17040360/javascript-function-to-rotate-a-base-64-image-by-x-degrees-and-return-new-base64
