### ISSUE TITLE
Cannot import beta in feature module

### ISSUE THREAD

**Issue by olaf89** [MurhafSousli/ngx-gallery#234]
#### What is the expected behavior?
I would like to use Gallery in feature module without importing it in AppModule

#### What is the current behavior?
In previous version it was possible to import GalleryModule and LightboxModule in feature module and it worked, with latest beta's its not longer possible

The following error is thrown:
TypeError: Cannot read property 'config' of undefined
    at new GalleryComponent (ngx-gallery-core.js:694)

#### What are the steps to reproduce?

Import gallery in feature module

#### What is the use-case or motivation for changing an existing behavior?

I would like to use gallery in feature module

#### Which versions are you using for the following packages?

Angular: 7
Angular CDK:7
Angular CLI:7
Typescript:3.16
Gallery: 4.0.0-beta.1

**Comment by MurhafSousli** [comment]
Did you try `GalleryModule.forRoot()` in your lazy module?

**Comment by olaf89** [comment]
Yes, thats how i have been importing with success in v3

**Comment by MurhafSousli** [comment]
fixed in `v4.0.0`
