### ISSUE TITLE
hello, is there update the 'gallery-main'? i didn't find this class.I try to just add to gallery,but there only show the thumbs.so how can i respect the height  now?

### ISSUE THREAD

**Issue by kefengwei** [MurhafSousli/ngx-gallery#236]
_Originally posted by @kefengwei in https://github.com/MurhafSousli/ngx-gallery/issue_comments#issuecomment-440873853_

**Comment by MurhafSousli** [comment]
It is unclear what you are asking for! Please follow the issue template and fill the required information
