### ISSUE TITLE
Gallery component breaks server side render

### ISSUE THREAD

**Issue by ArtyomZakharov** [MurhafSousli/ngx-gallery#240]
I was trying to set up SSR, but encountered the problem with Gallery component. 

#### What is the expected behavior?
Gallery is being render on server with no errors.

#### What is the current behavior?
Server throws the following error when I request some page with the gallery component on it:
```
ERROR ReferenceError: Image is not defined
    at new LazyDirective (/var/www/app/dist/express/server.js:190064:36)
    at createClass (/var/www/app/dist/express/server.js:13181:20)
    at createDirectiveInstance (/var/www/app/dist/express/server.js:13068:20)
    at createViewNodes (/var/www/app/dist/express/server.js:14288:36)
    at callViewAction (/var/www/app/dist/express/server.js:14604:13)
    at execComponentViewsAction (/var/www/app/dist/express/server.js:14523:13)
    at createViewNodes (/var/www/app/dist/express/server.js:14316:5)
    at Object.createEmbeddedView (/var/www/app/dist/express/server.js:14196:5)
    at TemplateRef_.createEmbeddedView (/var/www/app/dist/express/server.js:12783:38)
    at ViewContainerRef_.createEmbeddedView (/var/www/app/dist/express/server.js:12649:35)
```
As a result, server stops render on this point and returns the page with no gallery and anything after it.

#### What are the steps to reproduce?
Try to run angular universal app, containing something like
```html
<gallery [items]="images" ...></gallery>
```
where `images` is array of [`ImageItem`](https://github.com/MurhafSousli/ngx-gallery/blob/1bd67b9dea65a3ac57f26508b57fb17dea56ad6c/projects/core/src/lib/components/templates/index.ts#L3) objects.

#### What is the use-case or motivation for changing an existing behavior?
It would be great if anyone could use gallery with angular universal without devising any workarounds.

#### Which versions are you using for the following packages?

Angular: 6.1.10
Angular CDK: 6.4.7
Angular CLI: 6.2.7
Typescript: 2.9.2
Gallery: 3.1.2

#### Is there anything else we should know?
I found that the cause of this problem is in [`LazyDirective`](https://github.com/MurhafSousli/ngx-gallery/blob/1bd67b9dea65a3ac57f26508b57fb17dea56ad6c/projects/core/src/lib/directives/lazy.directive.ts#L22). Its constructor uses the [`Image`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image) constructor that is not available when the app is being executed on server.

#### PS. Workaround for anyone who is googling for quick solution
Instead of passing array of [`ImageItem`](https://github.com/MurhafSousli/ngx-gallery/blob/1bd67b9dea65a3ac57f26508b57fb17dea56ad6c/projects/core/src/lib/components/templates/index.ts#L3) objects to gallery component you can use the custom item template and array of objects implementing [`GalleryItem`](https://github.com/MurhafSousli/ngx-gallery/blob/1bd67b9dea65a3ac57f26508b57fb17dea56ad6c/projects/core/src/lib/models/gallery.model.ts#L12) interface. 

In template:
```html
<gallery [items]="items" [itemTemplate]="someCustomTemplate" ...></gallery>
<ng-template
  #someCustomTemplate
  let-index="index"
  let-type="type"
  let-data="data"
  let-currIndex="currIndex"
>
 <div [style.background-image]="'url('+ data +')'"></div>
</ng-template>
```
In component class:
```typescript
items: GalleryItem[] = [
  { type: 'custom-gallery-image', data: 'link/to/your/image' },
  ...
];
```

**Comment by MurhafSousli** [comment]
@ArtyomZakharov Please try the Gallery 4 with Angular 7 and Typescript 3.1.x and tell me if the issue is still there
