### ISSUE TITLE
Image caching does not work in v4

### ISSUE THREAD

**Issue by olaf89** [MurhafSousli/ngx-gallery#243]
#### What is the expected behavior?
Each time i open gallery same images are loaded again

#### What is the current behavior?
Images are loaded each time.

#### What are the steps to reproduce?

Use gallery in feature module, navigate to view with gallery, then go back and navigate there again.

#### Which versions are you using for the following packages?

Angular: 7
Angular CDK: 7
Angular CLI: 7
Typescript:3.1
Gallery: 4

#### Is there anything else we should know?
I think its because of interceptors, i think interceptors are setup when application starts and providing additional interceptors in feature modules does not work.

Providing interceptor
https://github.com/MurhafSousli/ngx-gallery/blob/master/projects/core/src/lib/gallery.module.ts#L34

Interceptors are set once on setup and then cached
https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/packages/common/http/src/module.ts#L39

**Comment by MurhafSousli** [comment]
Hi @olaf89, it is working fine in the demo, can you add a repro?
