### ISSUE TITLE
No exported member 'GALLERY_CONFIG'.

### ISSUE THREAD

**Issue by priatelko** [MurhafSousli/ngx-gallery#244]
I updated new version from 3.1.2 to 4.0.1., but I have an issue with GALLERY_CONFIG, which is not importable. I am going by an API Documentation, the Lazy loading section.

`[ts] Module '".../@ngx-gallery/core/ngx-gallery-core"' has no exported member 'GALLERY_CONFIG'.`

**Comment by MurhafSousli** [comment]
It is exported! maybe you need a fresh npm install, try it in the [stackblitz](https://stackblitz.com/edit/ngx-gallery)
