### ISSUE TITLE
CORS Error when upgrading from 3.x to 4.x

### ISSUE THREAD

**Issue by SzabKel** [MurhafSousli/ngx-gallery#245]
#### What is the expected behaviour?
In version 3.3.1, I could load images without any additional tricks. We store our images in amazon S3 the public links should be loadable as the image sources.

#### What is the current behaviour?
`Unable to load image!` error appears and a CORS error is thrown in the console (on stackblitz, check the browser's console), even though the image is loaded successfully in the network tab.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://.....jpg. (Reason: CORS request did not succeed).
```

#### What are the steps to reproduce?
[https://stackblitz.com/edit/ngx-gallery-cors-error](https://stackblitz.com/edit/ngx-gallery-cors-error)

**Comment by MurhafSousli** [comment]
@SzabKel You can use `loadingMode: 'indeterminate'` to switch back to the native loader

**Comment by pjr0001** [comment]
This stil appears to be an issue. I added loadingMode: 'indeterminate' on my import statement, and still have the CORS issue.

**Comment by MurhafSousli** [comment]
@pjr0001 You need to add a reproduction

**Comment by maku** [comment]
@MurhafSousli @pjr0001  I had the same problem - it occured with pictures stored on S3. I had to config explicitly a CORS config for the bucket to solve the problem...
```

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
</CORSConfiguration> 
```

**Comment by fazpu** [comment]
nothing from the above mentioned solutions work for me.

**Comment by matheusdavidson** [comment]
It did works for me, i had to add that config in the root module(app.module), but i didn't want to load it there, so instead of loading `GalleryModule` i just placed the config in the `providers` section of app.module as stated here: https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery then i loaded `GalleryModule` only in the module i'm using the gallery.
