### ISSUE TITLE
Multiple gallerize

### ISSUE THREAD

**Issue by adrienlamotte** [MurhafSousli/ngx-gallery#246]
Hi !

Is there a way to have multiple gallerize on the same page ?
Only the last one seems to be working : https://stackblitz.com/edit/ngx-gallery-cors-error-s22jgj

Thank you !

**Comment by MurhafSousli** [comment]
@adrienlamotte In the stacbklitz you provided, you are mixing `gallerize` directive with the `lighbox` directive

[fix stackblitz](https://stackblitz.com/edit/ngx-gallery-cors-error-zp5cwp?file=src%2Fapp%2Fhome%2Fhome.component.ts)

**Comment by adrienlamotte** [comment]
Awesome ! Thank you !

You should add the `gallerize="test-1"` trick to the documentation (or maybe I missed it) :-)

**Comment by MurhafSousli** [comment]
I usually write the docs at very late hours, that's why it has mistakes :D, I am updating the docs progressively https://github.com/MurhafSousli/ngx-gallery/wiki/Gallerize-directive

**Comment by adrienlamotte** [comment]
@MurhafSousli thank you for your hard work :-)
