### ISSUE TITLE
Add ImageItem with given index and open by it

### ISSUE THREAD

**Issue by vaydich** [MurhafSousli/ngx-gallery#248]
Hello.

I'm trying to push in gallery items array by given index. But i'm getting error 

> Cannot read property 'type' of undefined
 
Is it possible to use gallery according my case?

**Comment by MurhafSousli** [comment]
@vaydich Please fill the issue template, add the version you are using and your usage code or a stackblitz reproduction

**Comment by vaydich** [comment]
Hi

```
"@ngx-gallery/core": "3.0.2",
"@ngx-gallery/gallerize": "^3.1.0-beta.0",
"@ngx-gallery/lightbox": "3.0.2"
```

Code example (but i don't know is it possible to do like this).

```
vehicleImagesTest[10] = new ImageItem({
    src: this._fileManagerService.getImageSrc(fileId),
    thumb: this._fileManagerService.getImageSrc(fileId)
});

_gallery.ref('lightbox').load(vehicleImagesTest);

_lightbox.open(10, 'lightbox');
```
