### ISSUE TITLE
Some mobile can't swipe

### ISSUE THREAD

**Issue by priatelko** [MurhafSousli/ngx-gallery#250]
Helo firends, I have a mobile swiping issue, that I can't swipe the slide. Of course just some smart phones, it seems maybe with lower perrmance.

Here is an video example: https://www.youtube.com/watch?v=Fdw8F4Jtiq4

Have someone any idea?

I tried also panSensitivity: from 0 - 1000... nothing happens.

Thank you

**Comment by MurhafSousli** [comment]
Please fill the issue template with the required details
