### ISSUE TITLE
Hammer is not defined when gestures are disabled

### ISSUE THREAD

**Issue by paumartin** [MurhafSousli/ngx-gallery#254]
#### What is the expected behavior?

Use the gallery without gestures and hammerjs installed

#### What is the current behavior?
When using the gallery with the gestures disabled an error is shown in the console
![screenshot 2018-12-21 at 18 23 04](https://user-images.githubusercontent.com/713064/50355357-b6902a00-054e-11e9-8f70-085ee2f94797.png)

I have disabled the gestures when initializing the module, as the documentation says, but it still crashes
```
GalleryModule.withConfig({
      gestures: false
})
```

After you import hammerjs the error never apperars.

#### What is the use-case or motivation for changing an existing behavior?

Hammerjs is needed when you have disabled the gestures?

#### Which versions are you using for the following packages?

Angular: 7.1.2
Angular CDK: 7.1.1
Angular CLI: 6.0.0
Typescript: 2.7.2
Gallery: 4.0.1

**Comment by allahyar** [comment]
**I have this problem.**

angular 7.12
CDK 7.2.1
Gallery : 4.0.1
