### ISSUE TITLE
loadingError for Gallery config

### ISSUE THREAD

**Issue by linjie997** [MurhafSousli/ngx-gallery#257]
Hello,
I've been looking on handling errors when a not valid image is loaded in the Gallery.
I coudn't find the parameter "loadingError" for the gallery configuration, which is present in the lightboxConfig.
Is it possible to have the same parameter as lightbox for gallery?

#### What is the expected behavior?
Use a custom message when a loading error occurs in Gallery

#### What is the current behavior?
The default error messages appear "Unable to load the image"

#### What are the steps to reproduce?
Starting from a basic gallery, add an image with the src referring to an unvalid image

#### What is the use-case or motivation for changing an existing behavior?
Handling the error when the image is not found or invalid, and internalization of the message

#### Which versions are you using for the following packages?

Angular: 7.1.2
Angular CDK: 7.2
Angular CLI: 7.1.2
Typescript: 3.1.6
Gallery: 4.0.2

**Comment by MurhafSousli** [comment]
Hi @linjie997, the `loadingError` parameter is defined in the global config, if set, it should work for basic gallery and the lightbox. did you try 

Example
```ts
GalleryModule.withConfig({
  loadingError: `
  <div>Could not find the image</div>
  `
})
```

The lightbox config is only for the overlay options

**Comment by linjie997** [comment]
Thank you for your fast reply. This does work as expected, thank you!
