### ISSUE TITLE
Gallery navigation buttons freezing when added multiple gallery in one page

### ISSUE THREAD

**Issue by shubham16394** [MurhafSousli/ngx-gallery#258]
#### What is the expected behavior?
Navigaton button should not freeze while moving to next image or video

#### What is the current behavior?
When added multiple gallery in one page, in some of the galleries navigation buttons freeze and user is not able to move to next or previous image or video

#### What are the steps to reproduce?
Add multiple gallery(10 or more) in one page and add 5 or more images and videos in every gallery and this kind of behaviour will start coming.

#### What is the use-case or motivation for changing an existing behavior?
If this bug is not resolved then one will not be able to use gallery in large projects where multiple medias needed to be inserted at same page.

#### Which versions are you using for the following packages?

Angular: 6
Angular CDK: 
Angular CLI: 6 
Typescript: 2.9.2
Gallery: 4.0.1

**Comment by MurhafSousli** [comment]
We need a stackblitz reproduction to look into this, Please try to make one using the latest versions
