### ISSUE TITLE
The loadingIcon is not available any more from the config

### ISSUE THREAD

**Issue by mezoistvan** [MurhafSousli/ngx-gallery#259]
#### What is the expected behavior?
The wiki docs state that the default loadingIcon is available from the config. It was the case in v3.

#### What is the current behavior?
In 4.0.1, the loadingIcon property is undefined on the config.

#### What are the steps to reproduce?
In the most basic stackblitz, check the config value.

#### Which versions are you using for the following packages?
Gallery: 4.0.1

#### Is there anything else we should know?
Thanks for all the hard work! This is a great package.

**Comment by MurhafSousli** [comment]
Hi @mezoistvan it is working! https://stackblitz.com/edit/ngx-gallery-zjkjze?file=src/app/app.module.ts

**Comment by mezoistvan** [comment]
Ok, thanks! 👍  Was it just changed from the svg element to the `Loading...` text?

**Comment by MurhafSousli** [comment]
Yupp but the image are loaded too fast
