### ISSUE TITLE
Gallery with Gallerize and AutoPlay doesn't show images

### ISSUE THREAD

**Issue by hugoserrana** [MurhafSousli/ngx-gallery#260]
When use gallery with gallerize and set autoPlay to true, the lightbox doesn't show anything. The result is the same as the issue: https://github.com/MurhafSousli/ngx-gallery/issues/69

Without autoPlay, the component works as expected.

#### What are the steps to reproduce?
Example:
<gallery gallerize [items]="images" autoPlay="true"></gallery>

#### Which versions are you using for the following packages?

Angular: 7.2.0
Angular CDK: 7.2.1
Angular CLI: 7.1.4
Typescript: 3.1.6
Gallery: 4.0.1

**Comment by MurhafSousli** [comment]
Can you please add a reproduction https://stackblitz.com/edit/ngx-gallery

**Comment by hugoserrana** [comment]
Your stackblitz works. Just add auto play to [this example ](https://stackblitz.com/edit/ngx-gallery-nqudkt?file=src%2Fapp%2Fhome%2Fhome.component.html) and then stop work.
This example is on [Gallerize Examples Page](https://github.com/MurhafSousli/ngx-gallery/wiki/Gallerize-Examples)

**Comment by hugoserrana** [comment]
Sorry for the delay, but I found the difference and why it works in your example.
When set autoPlay:
`<gallery gallerize [items]="items" autoPlay="true"></gallery>`

and just set images like that: 
```
items: GalleryItem[] = [
  {
    srcUrl: 'https://preview.ibb.co/jrsA6R/img12.jpg',
    previewUrl: 'https://preview.ibb.co/jrsA6R/img12.jpg'
  }
];
```
The lightbox does not work.
One workaround is to set the light box items by reference:

```
images: GalleryItem[];

    constructor(public gallery: Gallery, public lightbox: Lightbox) { }

    ngOnInit() {
      this.items = this.imageData.map(item => new ImageItem({ src: item.srcUrl, thumb: item.previewUrl 
    }));

    /** Lightbox Example */

    // Get a lightbox gallery ref
    const lightboxRef = this.gallery.ref('lightbox');

    // Add custom gallery config to the lightbox (optional)
    lightboxRef.setConfig({
      imageSize: ImageSize.Cover,
      thumbPosition: ThumbnailsPosition.Top
    });

    // Load items into the lightbox gallery ref
    lightboxRef.load(this.items);
  }
```

I do not know if this is the desired behavior, because in the documentation it shows as if it were automatic, without needing to reference the lightbox and set the items manually.

Anyway, wonderful work on the component.
