### ISSUE TITLE
Gallery Gallerize

### ISSUE THREAD

**Issue by anthowm** [MurhafSousli/ngx-gallery#261]
Hello,
Is there a way to the images inner a gallerize cover all like in the example ( Im using <gallery gallerize [items]="cameraImages"></gallery>)
![image](https://user-images.githubusercontent.com/5764698/50964405-7da10080-14cf-11e9-8099-1ea6e60f0297.png)
I get the behaviour like the example in stackblitz https://stackblitz.com/edit/ngx-gallery-nqudkt
Thanks in advance.

**Comment by MurhafSousli** [comment]
Sure! use the following config
```ts
GalleryModule.withConfig({
  imageSize: 'cover'
}),
```
https://stackblitz.com/edit/ngx-gallery-hhaztv?file=src%2Fapp%2Fapp.module.ts
