### ISSUE TITLE
Gallery show error with universal

### ISSUE THREAD

**Issue by andy200486** [MurhafSousli/ngx-gallery#262]
#### What is the current behavior?
`ERROR ReferenceError: requestAnimationFrame is not defined
    at AnimationFrameAction.requestAsyncId 
`
The problem seems to be at this line 
`rxjs.animationFrameScheduler.schedule(function () { return _this._slidingWorker$.next(newState); });`
#### Which versions are you using for the following packages?

Angular:7.1.4
Angular CDK:7.2.1
Angular CLI:7.1.4
Typescript:3.1.6
Gallery: 4.0.1

I'm facing issues with your module when I use server side rendering. 
Could you help me ?

Thanks

**Comment by andy200486** [comment]
When would it be available ?

Thanks

**Comment by MurhafSousli** [comment]
Sure! hopefully tomorrow

**Comment by MurhafSousli** [comment]
Should be fixed in v4.0.2-beta.0

**Comment by Meistercoach83** [comment]
Hey Andy & Murhaf! Is there a solution for the "Image is not defined" error with SSR?

**Comment by MyneLife** [comment]
> Thanks, it works good! But I got an other error now with this version :
> `ERROR ReferenceError: Image is not defined` at this line
> `var img = new Image();`

+1 Facing the same error, fix appreciated.

Using latest version 4.0.2-beta.0

**Comment by MyneLife** [comment]
I think I found the reason for this issue. As Angular Universal does not provide an actual DOM, you are not allowed to directly access the DOM for example via `window` or `document` objects (see [Angular Universal documentation](https://angular.io/guide/universal#working-around-the-browser-apis)) in case you are using SSR.

```
ERROR ReferenceError: Image is not defined
  at LazyImage.nativeLoader (XXX\dist\server.js:203719:19)
  ...
```

Looking at the [corresponding source code](https://github.com/MurhafSousli/ngx-gallery/blob/master/projects/core/src/lib/directives/lazy-image.ts#L77), I can see that a new instance of the class `Image` is created.
```
nativeLoader(url: string): Observable<any> {
    const img = new Image();
    ...
}
```

As documented in the [MDN spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image), `Image` is just a wrapper around `document.createElement('img')` which directly accesses the `document` object which again is forbidden for SSR usage. This should be easy to fix as Angular provides an abstraction for the `document` object which can be used even when using SSR as stated in the [Universal documentation](https://angular.io/guide/universal#working-around-the-browser-apis).

@MurhafSousli I don't have time to fix and test this fix properly, but this hopefully helps you to fix it :) Their might be other direct usages of DOM objects, keep this in mind when fixing this issue.

**Comment by bastienlemaitre** [comment]
Up!

**Comment by bastienlemaitre** [comment]
Hello,
Can you reopen the issue, it seems that another bug is present server side because of 
 `this._loaderSub$`
Indeed, server side, each observable is converted into a promise and becomes expected.
Only it is never triggered because the `zip` is waiting for both answers. By passing to a `merge`, the triggering takes place and releases promise.

**Comment by MurhafSousli** [comment]
@bastienlemaitre Why haven't you test it out with Universal before sending me the PR?

**Comment by bastienlemaitre** [comment]
I use the double compilation with a ng serve and a ng build, the SSR sometimes only triggers later after the update of the code, for at least a minute it worked, I had no more error but my code was not up to date ..

**Comment by bastienlemaitre** [comment]
All my excuses, it works. On the other hand the server-side autoplay seems to pose a problem, it is he who makes the script crash because of the promise

**Comment by mrandreev** [comment]
Hey, any updates on this bug? As I see last fix was solved one problem and provided new one.

For now I can see only one workaround its just skip autoPlay feature on server-side:
`[autoPlay]="isBrowser"`
