### ISSUE TITLE
Add hls stream to video player

### ISSUE THREAD

**Issue by allahyar** [MurhafSousli/ngx-gallery#263]
Hi,
Ngx-gallery will not play live stream hls , Please fix it or let me know if can make it ?

**Comment by MurhafSousli** [comment]
What do you mean add HLS stream, you already have HTML5 video player, just give it the valid source

**Comment by MurhafSousli** [comment]
You can integrate your custom video player, follow the [advanced guide](https://github.com/MurhafSousli/ngx-gallery/wiki/Advanced-Usage)

**Comment by allahyar** [comment]
I want to use 'm3u8' video format, beacuse of the lowest volume. But html5 video player don't suport this format.
I see advanced guide but i chose this solution :P
Thanks anyway

**Comment by MurhafSousli** [comment]
I updated my answer in case you wanted to implement a custom video player

**Comment by allahyar** [comment]
I use the lightbox , Can the video player be customized ?

**Comment by MurhafSousli** [comment]
Yes, get the `TemplateRef` using `@ViewChild()` then set it with the lightbox `galleryRef`
```ts
@ViewChild('itemTemplate') templateItem: TemplateRef<any>

ngAfterViewInit() {
  const galleryRef = this._gallery.ref('lightbox');
  galleryRef.setConfig({
    templateItem: this.templateItem
  });
}
```
