### ISSUE TITLE
Gallery is broken when ViewEncapsulation turned off

### ISSUE THREAD

**Issue by alexshakura** [MurhafSousli/ngx-gallery#270]
#### What is the expected behavior?
All of the styles must work with all of the `ViewEncapsulation`. 

#### What is the current behavior?
Gallery styles aren't working with `ViewEncapsulation.None` set globally.

#### What are the steps to reproduce?
https://stackblitz.com/edit/ngx-gallery-bpnus6

#### Which versions are you using for the following packages?

Angular: 7.1.0
Angular CDK:
Angular CLI: 7.1.0 
Typescript: 3.1.6
Gallery: 4.0.0

#### Is there anything else we should know?
`::ng-deep` in styles +  `ViewEncapsulation.None` = styles aren't working

**Comment by MurhafSousli** [comment]
I don't understand what is not working, the stackblitz you shared does not use `ViewEncapsulation.None`, how is it not working?

**Comment by alexshakura** [comment]
@MurhafSousli please checkout `main.ts` file:
```
platformBrowserDynamic().bootstrapModule(AppModule, {
  defaultEncapsulation: ViewEncapsulation.None
}).then(ref => {
```
