### ISSUE TITLE
Certain images do not show

### ISSUE THREAD

**Issue by mmmatthew** [MurhafSousli/ngx-gallery#272]
#### What is the expected behavior?
All image items should display

#### What is the current behavior?
Certain images are not shown.

#### What are the steps to reproduce?
Visit https://beta.water-fountains.org/zurich?lang=en&queryType=byId&database=wikidata&idval=Q27229903

The images are sourced from here: https://commons.wikimedia.org/wiki/Category:Lindenhof_Brunnen
Source code of my website: https://github.com/water-fountains/proximap
#### Which versions are you using for the following packages?

Angular: 6.1
Angular CDK: 6.4
Angular CLI: 6.2
Typescript: 2.7
Gallery: 3.3 (I can't upgrade to Angular 7 yet)

#### Is there anything else we should know?
I had a similar issue with another Angular Gallery library: https://github.com/lukasz-galka/ngx-gallery/issues/202

**Comment by mmmatthew** [comment]
I get the following warning in the console:

> core.js:7429 WARNING: sanitizing unsafe style value url(https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/'Occupy'_Lindenhof_Zürich_2011-11-09_14-16-09_(SX230HS).JPG/1200px-'Occupy'_Lindenhof_Zürich_2011-11-09_14-16-09_(SX230HS).JPG) (see http://g.co/ng/security#xss).

**Comment by MurhafSousli** [comment]
Unfortunately, this was a bug in the previous version, if you want to stay on the version you are using you can implement a custom item template and then use `DomSanitizerbypassSecurityTrustStyle()` on the image URL.

Here is a complete example of how to do it with custom item template https://stackblitz.com/edit/ngx-gallery-custom-item-jnpcgv?file=src%2Fapp%2Fcustom-gallery-item%2Fcustom-gallery-item.component.ts

**Comment by mmmatthew** [comment]
Thanks for that!. I tried forking and building the package locally but wasn't able to run the demos so I gave up... hopefully angular redux will update soon...
