### ISSUE TITLE
How to make pictures zoom in and out

### ISSUE THREAD

**Issue by NineFly** [MurhafSousli/ngx-gallery#273]
#### What is the expected behavior?
When previewing a picture, your fingers can zoom in and out.

#### What is the current behavior?
Pictures cannot be enlarged for viewing

#### What are the steps to reproduce?
Picture preview, double finger enlargement picture has no effect, hope to view a part of the picture can be enlarged.

#### What is the use-case or motivation for changing an existing behavior?
I just want to be able to see the location information of the picture.

#### Which versions are you using for the following packages?

Angular:6.1.0
Angular CDK:7.2.1
Angular CLI:6.2.6
Typescript:2.9.2
Gallery: 4.0.1

#### Is there anything else we should know?
Hope to prompt how to modify, is to zoom in and out of the picture, thank you.

**Comment by MurhafSousli** [comment]
Not out of the box, you should use a zooming library and then integrate it in the gallery, here is an example but it is not perfect https://github.com/MurhafSousli/ngx-gallery/wiki/Image-zoom-example

**Comment by kinizumi** [comment]
it is no longer working with later versions of angular @MurhafSousli  reasons:

- this guy https://github.com/hallysonh/ngx-imageviewer is 7 years ago
- it is no longer compatable with the latest ng-gallery
