### ISSUE TITLE
Is that any possible ways to add a button to the lightbox with itemTemplate?

### ISSUE THREAD

**Issue by AswinKumar12** [MurhafSousli/ngx-gallery#276]
Is there any possible ways to add share button for the lightbox images?

**Comment by MurhafSousli** [comment]
Share buttons shares website URLs, if your app routing is configured to open lightbox then yes and you can add share button on each image (like facebook lightbox)

But if you are just using the lightbox normally like in the demo, then share buttons can only share your current URL for the page NOT for a specific image.

Only Pinterest button would work for individual images.

**Comment by AswinKumar12** [comment]
No, i asked about adding button on the "Lightbox"(fullscreen-mode) !!

**Comment by AswinKumar12** [comment]
@MurhafSousli  please help with this....

**Comment by MurhafSousli** [comment]
Yes you can 

```html
<ng-template #itemTemplate>
  <button>Press Me</button>
</ng-template>
```
```ts
@Component({
...
})
export class HomeComponent implements OnInit {

  @ViewChild('itemTemplate') itemTemplate;

  constructor(public gallery: Gallery, public lightbox: Lightbox) {
  }

  ngOnInit() {
    /** Lightbox Example */

    // Get a lightbox gallery ref
    const lightboxRef = this.gallery.ref('lightbox');

    // Set itemTemplate using gallery setConfig function
    lightboxRef.setConfig({
      itemTemplate: this.itemTemplate
    });
  }
}
```
Here is an [example](https://stackblitz.com/edit/ngx-gallery-y9kzck?file=src/app/home/home.component.ts)

**Comment by AswinKumar12** [comment]
Thank you very much!! You made my day!!!
