### ISSUE TITLE
Mobile back button related request

### ISSUE THREAD

**Issue by AswinKumar12** [MurhafSousli/ngx-gallery#278]
Hi @MurhafSousli. I saw the old `enhancement request` as,On tapping `back button` in the mobile phones `lightbox` will close, parallelly the _route_ also change.But in my condition,on tapping `back button` the `lightbox` wants to close and also _route_ not to change,then **after closed** if we tap `back button`,the _route_ must change accordingly.**Is that possible?**

**Comment by MurhafSousli** [comment]
Hi @AswinKumar12 can you add a reproduction?

**Comment by AswinKumar12** [comment]
Did you mean a stackblitz demo for my current issue?

**Comment by AswinKumar12** [comment]
@MurhafSousli Is there any stream that executes after `closed` stream?
or else can you make me that?
