### ISSUE TITLE
Beta shown as latest

### ISSUE THREAD

**Issue by internalsystemerror** [MurhafSousli/ngx-gallery#279]
Whenever a new beta is released, for some reason, with this package it shows as being the "latest" version. I don't notice this on any other packages that have a newer beta only version. Is this by design? Is it safe to consider these beta releases as the latest stable?

**Comment by MurhafSousli** [comment]
There is a bug in Universal that should be fixed before releasing a stable version

**Comment by internalsystemerror** [comment]
Sorry, I mean to say that in npm, the beta version is tagged as 'latest' as opposed to 'next'. Is there any particular reason for this? It's not being considered the latest stable by npm or yarn, however, PHPStorm is defaulting to the beta as the latest version due to the tag.
