### ISSUE TITLE
Images stop loading after clicking back-forward few times

### ISSUE THREAD

**Issue by kkseven07** [MurhafSousli/ngx-gallery#285]
#### What is the expected behavior?
![Screen Shot 2019-06-11 at 3 31 45 PM](https://user-images.githubusercontent.com/25701048/59260871-3aa1af80-8c5e-11e9-9d0e-00be3b7ce366.png)

#### What is the current behavior?

![Screen Shot 2019-06-11 at 3 31 56 PM](https://user-images.githubusercontent.com/25701048/59260886-42615400-8c5e-11e9-8564-7728a64202ab.png)

#### What are the steps to reproduce?
After clicking a few times forward, and then a few times backward, the images stop loading, only the list of previews work
<!-- 

#### Which versions are you using for the following packages?

Angular:7
Angular CDK:7.3.7
Angular CLI:7.3.8
Typescript:3.2.2
Gallery:  4.0.3

**Comment by kkseven07** [comment]
Data structure: 
`let imgs = []
    this.screenshots.map((screen, index)=> {
      imgs.push({srcUrl:screen.screenShotUrl, previewUrl:screen.screenShotUrl})
    })
    this.imageData = imgs`

**Comment by kkseven07** [comment]
`loadingMode: "indeterminate"` fixes the problem, however I think this is a bug

**Comment by MurhafSousli** [comment]
Yes, it is. There seem to be a problem when using HttpClient to load the image, stay with the native image loader `indeterminate`
