### ISSUE TITLE
Angular 8 Support

### ISSUE THREAD

**Issue by internalsystemerror** [MurhafSousli/ngx-gallery#287]
Is angular 8 supported or planned if not? I can't find a definitive answer looking through various issues.

**Comment by MurhafSousli** [comment]
Yea! what is the problem? did you get an error?

**Comment by internalsystemerror** [comment]
From what I can see this package is built against Angular 7. In order to begin our application upgrades I'm getting the status of all the libraries we use, of which this is one. If you're happy that Angular 8 is fully supported please feel free to close this issue.

**Comment by MurhafSousli** [comment]
Yea, it should work without problems

**Comment by internalsystemerror** [comment]
"should"... But has it been tested in isolation? Any problems with Ivy (not that this is required until Angular 9)?

**Comment by nadhir-falta** [comment]
No, as of today this is not working against Ivy, getting this error with Ivy:
`ERROR in ENOENT: no such file or directory, open 'C:/Users/nfalta/Desktop/rizkhalal/node_modules/ngx-gallery/ngx-gallery.js'`

**Comment by nadhir-falta** [comment]
No, as of today this is not working against Ivy, getting this error with Ivy:
ERROR in ENOENT: no such file or directory, open 'C:/Users/develoepr/Desktop/myProj/node_modules/ngx-gallery/ngx-gallery.js'
