### ISSUE TITLE
Part of next/previous image is visible in gallery when width is not integer

### ISSUE THREAD

**Issue by pzmuda13** [MurhafSousli/ngx-gallery#288]
#### What is the expected behavior?
The part of next image should not be visible when galery width is not integer.

#### What is the current behavior?
The translate value takes to calculation of slider offset offsetWidth which is always integer (
https://github.com/MurhafSousli/ngx-gallery/blob/master/projects/core/src/lib/components/gallery-slider.component.ts
line 162
). When total width of gallery is not integer it results in showing part of other picture on the edge. Taking width from boundingClientRect will be more accurate, but when I changed it in sources to test it in my project problem with lightbox occured.

Quick workaround with fractional widths:

`<div class="gallery-container" #galleryContainer="#galleryContainer">
  <gallery id="property-gallery" gallerize="gallerize" [items]="galleryImages" 
  [loadingMode]="'indeterminate'" [style.width.px]="galleryContainer?.offsetWidth"></gallery>
</div>`

#### What are the steps to reproduce?
https://stackblitz.com/edit/ngx-gallery-pfmfpv?file=src%2Fapp%2Fhome%2Fhome.component.css

Go to the last image. 
![Zrzut ekranu 2019-06-13 o 10 33 52](https://user-images.githubusercontent.com/34399835/59417071-e108c480-8dc6-11e9-82c2-62f98a8e1793.png)

**Comment by MurhafSousli** [comment]
Yea that pixel differs from a browser to browser, also to the window size. I am not sure what we can do about it, if you have an idea please share it here
