### ISSUE TITLE
How to make the thumbnails stay still

### ISSUE THREAD

**Issue by astanley86** [MurhafSousli/ngx-gallery#289]
Awesome gallery!  Is it possible to have the thumbnails stay in the same place regardless of which image is being displayed?  The default experience is moving and sliding around.  

I'd like to use this project for an ecommerce product page image gallery, similar to the amazon.com product page.

Thank you!

**Comment by MurhafSousli** [comment]
Hi @astanley86 thanks a lot!

It is not possible to disconnect thumbnails from the main slider compeletely, currently you can use `thumbMode="free"` but that would still highlight and scroll to the selected item in the thumbnail when the selected item in the main slider is changed

Would we add this on later version? I am not sure about it, I was working on a similar library that is more flexible and does this but currently the project it is paused

**Comment by Saiok** [comment]
@MurhafSousli hi there. is it possible to add nav icons (left and right chevron icon) for thumblist navigation?

[https://prnt.sc/rcDcM9YPc-0x](url) - example image here

**Comment by MurhafSousli** [comment]
This should be fixed in v8.0.0-beta.0, there is new option called `thumbDetached` which can be set to **true**

Install it `npm i ng-gallery@beta` and `npm i bezier-easing`
