### ISSUE TITLE
Ivy Support

### ISSUE THREAD

**Issue by nadhir-falta** [MurhafSousli/ngx-gallery#290]
#### What is the expected behavior?
Currently Angular 8 Ivy is not supported, getting this error:

#### What is the current behavior?
`ERROR in ENOENT: no such file or directory, open 'C:/Users/develoepr/Desktop/myProj/node_modules/ngx-gallery/ngx-gallery.js'`

#### What are the steps to reproduce?
Steps to enable Ivy are:
https://github.com/angular/angular/blob/master/aio/content/guide/ivy.md

#### Which versions are you using for the following packages?

Angular: 8.0.3
Angular CDK: 8.0.1
Angular CLI: 8.0.4
Typescript: 3.4.1
Gallery: 5.10.0

**Comment by smile2014** [comment]
Angular8 integrated ngx-imageviewer does not support scaling
