### ISSUE TITLE
[counterPosition]="bottom" does not work

### ISSUE THREAD

**Issue by ragnhildlarsen** [MurhafSousli/ngx-gallery#295]
#### What is the expected behavior?
Adding `[counterPosition]="bottom"` to `<gallery>` does not move the image counter to the bottom.

#### What is the current behavior?
Only shown on top.

#### What are the steps to reproduce?
Add `[counterPosition]="bottom"` to the `<gallery>` tag in home.component.html in https://stackblitz.com/edit/ngx-gallery and see that the counter stays on the top.

#### Which versions are you using for the following packages?
Angular: 8.0.0
Angular CDK: 8.0.0
Angular CLI: 8.0.1
Typescript: 3.4.4
Gallery: 4.0.3

**Comment by MurhafSousli** [comment]
@ragnhildlarsen it does work properly! https://stackblitz.com/edit/ngx-gallery-ohgwe5?file=src/app/home/home.component.html

**Comment by ragnhildlarsen** [comment]
Thank you! It works 👍
