### ISSUE TITLE
How do i set loadingMode to indeterminate for Gallerize?

### ISSUE THREAD

**Issue by maurice85** [MurhafSousli/ngx-gallery#296]
Hello,

I have the annoying CORS issue when trying to load images in the hooked gallerize component of the gallery component. Images load fine in the gallery component because i have set loadingMode to indeterminate. But how do i do the same for the gallerize component? Thank you.

**Comment by MurhafSousli** [comment]
Have you tried setting the global config?

```ts
GalleryModule.withConfig({
  loadingMode: 'indeterminate'
}),
```
Here is a demo https://stackblitz.com/edit/ngx-gallery-multiple-gallerize

To set config for a specific gallery

```ts
constructor(private gallery: Gallery) {
  gallery.ref('gallery-1').setConfig({
    loadingMode: 'indeterminate'
  })
}
```

**Comment by maurice85** [comment]
Works like a charm thx, don't understand why you have to set the
GalleryModule though, i tried applying this to GallerizeModule but it
doesn't seem to have such a method.

Thx

**Comment by MurhafSousli** [comment]
`GalleryModule` is meant for the gallery component, use `withConfig()` to set global config that applies on all gallery components, `GallerizeModule` on the other hand is meant for `gallerize` directive usage
