### ISSUE TITLE
Image is downloaded twice

### ISSUE THREAD

**Issue by fasterfish** [MurhafSousli/ngx-gallery#297]
#### What is the expected behavior?
Image should be downloaded once

#### What is the current behavior?
Image is downloaded twice

Angular: 8.1.3
Angular CDK: 8.1.3
Angular CLI: 8.1.3
Typescript: 3.4.3
Gallery: 4.0.3

**Comment by MurhafSousli** [comment]
Add reproduction or a proof

**Comment by RustamGulamov** [comment]
> Please add a reproduction or a proof

![image](https://user-images.githubusercontent.com/25031460/65605585-07d3bb00-dfb2-11e9-87cd-34c6ac914485.png)

**Comment by RustamGulamov** [comment]
> > Please add a reproduction or a proof
> 
> ![image](https://user-images.githubusercontent.com/25031460/65605585-07d3bb00-dfb2-11e9-87cd-34c6ac914485.png)

it is lightbox configs 
![image](https://user-images.githubusercontent.com/25031460/65605930-99432d00-dfb2-11e9-9ed0-d0e494b21705.png)

**Comment by AnthonyNahas** [comment]
@fasterfish  please check whether you are disabling cache in your browser!

**Comment by nicosaliagas** [comment]
Same problem.
Fullscreen mode, next or prec picture, each of them is downloaded twice.

You can see that on your demo https://stackblitz.com/edit/ngx-gallery

Angular : 13.1.0

Thanks

**Comment by MurhafSousli** [comment]
@nicosaliagas In the stackblitz, we use the same image URL for both thumbnail and main slider, so that is probably the reason why you see it twice
