### ISSUE TITLE
While traversing the carousel 2nd time the image is not displayed

### ISSUE THREAD

**Issue by rahul199939** [MurhafSousli/ngx-gallery#301]
#### What is the expected behavior?
The images should loop perfectly..
![image](https://user-images.githubusercontent.com/50900448/65690346-771ddd80-e08c-11e9-8cc6-bd57584f013d.png)---->this is what i excepet

#### What is the current behavior?
While traversing the carousel 2nd time the image is not displayed
![image](https://user-images.githubusercontent.com/50900448/65690472-be0bd300-e08c-11e9-923c-c75dbea83eab.png)----->this is the behaviour if the carousel run 2nd time 

#### Which versions are you using for the following packages?

Angular: angular 8
Angular CDK: "^8.2.1"
Angular CLI:"~8.3.0"
Typescript:"~3.5.3"
Gallery: Basic Gallery

**Comment by Squidy06** [comment]
Same here. @rahul199939, did you figure it out somehow?

**Comment by MurhafSousli** [comment]
Did you try `[loadingMode]="indeterminate"`

**Comment by rahul199939** [comment]
ohh thanks @MurhafSousli  now it's working. @Squidy06 you can also try this.

**Comment by rahulkathar** [comment]
[loadingMode]="indeterminate" @MurhafSousli I put this code in html but it gives error "Can't bind to 'loadingMode' since it isn't a known property of 'img'."

**Comment by D-Sokolovskyi** [comment]
@MurhafSousli works perfectly with `loadingMode: 'indeterminate'` until the gallery gets a png file

**Comment by kolkov** [comment]
The same problem for me too.

**Comment by zeus1200** [comment]
The same is happening with lightbox

**Comment by RomainSanchez** [comment]
thanks @MurhafSousli

**Comment by MurhafSousli** [comment]
Closing this, the `determinate` loading mode has been deprecated in the recent version.

**Comment by fjanon** [comment]
In which version was this issue fixed? I just tried 5.0.0 beta and it's still there.

**Comment by MurhafSousli** [comment]
> In which version was this issue fixed? I just tried 5.0.0 beta and it's still there.

@fjanon this was removed in v5.0.0-beta.0 https://github.com/MurhafSousli/ngx-gallery/blob/master/CHANGELOG.md#500-beta0
