### ISSUE TITLE
Dynamically changing the galleryOptions 

### ISSUE THREAD

**Issue by jjkayani** [MurhafSousli/ngx-gallery#303]
Hi, is there any way to change the galleryOptions based on some event? In my case I want to add the thumbnailActions based on an action, but I am unable to do by updating the model on action. Is there any way to do it dynamicall

**Comment by MurhafSousli** [comment]
Yea, you can set new config any time like this

```ts
constructor(private gallery: Gallery) {
  gallery.ref('gallery-1').setConfig({
    loadingMode: 'indeterminate'
  })
}
```
