### ISSUE TITLE
Lightbox Video Autoplay

### ISSUE THREAD

**Issue by Squidy06** [MurhafSousli/ngx-gallery#304]
Hello,

I'd like to play the video immidiately after opening the lightbox. 

By now I've acheived this in a not so elegant way:
```
this.lightbox.opened.subscribe(res => {
  setTimeout(() => {
    const video: HTMLMediaElement = document.querySelector("#lightbox-video-gallery .g-active-item video");
    if(video) {
      video.play();
    }
  });
});
```

I reviewed `gallery-video.component`'s template, but I see no autoplay things.
Is it possible in an angular way?

Thank you :)

**Comment by DeveloperAdd007** [comment]
Yeah same issue "autoPlay" does't work in lightbox

**Comment by jaydeep9rl** [comment]
Still seeing the same issue.
