### ISSUE TITLE
Close icon in lightbox container being rerendered all the time due to bug in template

### ISSUE THREAD

**Issue by daelmaak** [MurhafSousli/ngx-gallery#307]
#### What is the expected behavior?
Close icon doesn't get rerendered all the time so that it can be clicked.

#### What is the current behavior?
Due to `[innerHTML]="sanitizer.bypassSecurityTrustHtml(closeIcon)"` in the lightbox.component.ts, if change detection runs often enough, it causes the close icon to be rerendered all the time and prevents it effectively from being clicked -> the lightbox doesn't get closed.

#### What are the steps to reproduce?

https://stackblitz.com/edit/ngx-gallery-imageviewer-k2e3qu

1) Open the full screen lightbox
2) Try to close it with the cross close-icon
3) It doesn't get closed

#### Which versions are you using for the following packages?

Angular: 8.2.11
Angular CDK: 8.2.3
Angular CLI: 8.3.9
Typescript: 3.4.5
Gallery: 4.0.3

**Comment by MurhafSousli** [comment]
The problem is obviously caused by ngx-imageviewer, even the navigation is very slow. I think this issue should be opened on that project!
