### ISSUE TITLE
Angular 9 Ivy Renderer2 compile errors

### ISSUE THREAD

**Issue by darthsitthiander** [MurhafSousli/ngx-gallery#308]
#### What is the expected behavior?
The expected behavior is for ngx-gallery to work with Ivy since Angular 9 will have that onboard by default

#### What is the current behavior?
Currently when trying to use ngx-gallery with Angular 9 following compile errors occur: 

```
ERROR in node_modules/ngx-gallery/ngx-gallery-helper.service.d.ts:1:22 - error TS2724: Module '"C:/Users/sande/OneDrive/Dokumente/ng-ss-portfolio/node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer } from '@angular/core';
                       ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5555:31
    5555 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
node_modules/ngx-gallery/ngx-gallery-preview.component.d.ts:1:89 - error TS2724: Module '"C:/Users/sande/OneDrive/Dokumente/ng-ss-portfolio/node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ChangeDetectorRef, EventEmitter, OnInit, OnChanges, SimpleChanges, ElementRef, Renderer } from '@angular/core';
                                                                                          ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5555:31
    5555 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

#### What are the steps to reproduce?
Build an Angular project with the latest Angular 9 release and add ngx-gallery

#### What is the use-case or motivation for changing an existing behavior?
To make it compatible with the soon to be released version 9 of Angular

#### Which versions are you using for the following packages?

Angular: ~9.0.0-rc.2
Angular CDK: ^8.2.3
Angular CLI: ~9.0.0-rc.2
Typescript: ~3.6.4
Gallery: ^5.10.0

**Comment by kolkov** [comment]
Hi! Do you use latest version of library? I don't see any reference to old renderer in the source code.

**Comment by MurhafSousli** [comment]
@darthsitthiander I think you are using the wrong package, use `@ngx-gallery/core` instead of `ngx-gallery`

**Comment by darthsitthiander** [comment]
You're right! Thanks you guys, I don't know how I got the wrong repository.

**Comment by TheNemus** [comment]
> @darthsitthiander I think you are using the wrong package, use `@ngx-gallery/core` instead of `ngx-gallery`

sorry, what does this means? I'm using ngx-gallery too, why it is the "wrong" package after upgrading to Ang9

**Comment by eliudfromkenya** [comment]
Me too...
I'm using ngx-gallery too, why it is the same error? Ang9

**Comment by narayandropshop** [comment]
I am too getting same error
