### ISSUE TITLE
I can't use touch gestures to move on to the next photo.

### ISSUE THREAD

**Issue by playkang** [MurhafSousli/ngx-gallery#314]
This phenomenon occurs on the iPhone.

The same goes for the official homepage.

#### Which versions are you using for the following packages?

Angular: 8.2.12
Angular CDK:
Angular CLI:
Typescript:
Gallery:

**Comment by playkang** [comment]
Updating the iPhone solved it. Thank you.

**Comment by jaydeep9rl** [comment]
I am having the same issues with iPhone 11 pro and latest iOS v13.3.1.
I tried couple of versions of the following packages including the latest versions.

Angular: 8.2.14
Angular CLI: 8.3.23,


"@angular/cdk": "^7.1.1",
"@ngx-gallery/core": "^4.0.1",
"@ngx-gallery/lightbox": "^4.0.1",
"hammerjs": "^2.0.8",

VS

"@angular/cdk": "^8.2.3",
"@ngx-gallery/core": "^5.0.0-beta.0",
"@ngx-gallery/lightbox": "^5.0.0-beta.0",
"hammerjs": "^2.0.8",

Any help is appreciated!

**Comment by playkang** [comment]
@jaydeep9rl I don't know if it will help. The version I am currently using is.

Angular: 8.2.12
Angular CLI: 8.3.14
"@angular/cdk": "^8.2.3",
"@ngx-gallery/core": "^4.0.3",
"@ngx-gallery/lightbox": "^4.0.3",
"hammerjs": "^2.0.8",

Same version as when the problem occurred, only the iOS version was upgraded from 12 to 13.

I hope your problem solve well. :)

**Comment by MurhafSousli** [comment]
The plugin relies on hammerjs for the gestures, you may want to search for a similar issue on their repo. but it is out of my control.

**Comment by jaydeep9rl** [comment]
@playkang Thanks! I just tried those versions as well, but no luck :(
