### ISSUE TITLE
unable to load image 

### ISSUE THREAD

**Issue by bishoe** [MurhafSousli/ngx-gallery#316]
[img1](https://imgur.com/oHGG1Ad)
[img2](https://imgur.com/iy7raUh)
`PhotoList :GalleryItem[];
private  SliderPath :string='https://localhost:44318/api/Slider';
`
`private PathFolder : string="https://localhost:44318/Resources/Images/" `

`public Get(){
  return this._httpClient.get(this.SliderPath) .subscribe((res : GalleryItem[])=>{
 this.PhotoList = res;console.log(this.PhotoList); });
`

`import { GalleryModule, GalleryConfig ,Gallery} from 'ng-gallery';
import { GallerizeModule ,} from  '@ngx-gallery/gallerize';
import { LightboxModule } from  '@ngx-gallery/lightbox';
import { GALLERY_CONFIG } from '@ngx-gallery/core';
import 'hammerjs';
export const config : GalleryConfig = {
  // ...
`
`GalleryModule.forRoot(config)
`
`  providers: [
    {
      provide: GALLERY_CONFIG,
      useValue: {
        dots: true,
        imageSize: 'cover'
      }
    }
  ]
`
Angular:_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 12.14.0
OS: win32 x64
Angular: 7.2.1
... common, compiler, core, forms, http, language-service
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/animations               8.2.14
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/compiler-cli             7.2.5
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.4
typescript                        3.1.6
webpack                           4.29.0

Angular CDK:    "@angular/cdk": "^7.3.7",

Angular CLI:    "@angular/cli": "^7.3.9",

Typescript:    "typescript": "~3.1.6"

Gallery:     "@ngx-gallery/core": "^4.0.3",
    "@ngx-gallery/gallerize": "^4.0.3",
    "@ngx-gallery/lightbox": "^4.0.3",
    "ng-gallery": "^1.0.1",

**Comment by MurhafSousli** [comment]
You need to add reproduction https://stackblitz.com/edit/ngx-gallery

**Comment by MurhafSousli** [comment]
Add `loadingMode: 'indeterminate'` to you gallery config and the problem will be fixed.

**Comment by bishoe** [comment]
Property 'withConfig' does not exist on type 'typeof GalleryModule'.ts(2339)
     GallerizeModule,
    LightboxModule,

    GalleryModule.withConfig({
      loadingMode: 'indeterminate'
    }),



    GalleryModule,
    GallerizeModule,
    LightboxModule.withConfig({
      loadingMode: 'indeterminate'

    }),

(property) loadingMode: string
Argument of type '{ loadingMode: string; }' is not assignable to parameter of type 'LightboxConfig'.
  Object literal may only specify known properties, and 'loadingMode' does not exist in type 'LightboxConfig'.ts(2345)

**Comment by MurhafSousli** [comment]
This issue has been answered many times, if you are using a lightbox then get a reference of that gallery and use the function `galleryRef.setConfig({ loadingMode: 'indeterminate' })` as stated in this comment https://github.com/MurhafSousli/ngx-gallery/issues/267#issuecomment-469036914

**Comment by bishoe** [comment]
problem still not work
[img](https://imgur.com/CjJExtv)
[img2](https://imgur.com/mSqAJYb)
I have to use two elements to work and the main problem is not resolved yet

` <gallery gallerize [items]="pathFolder+PhotoList.ImageNameO">

 
</gallery>
<div class="container" gallerize>
  img *ngFor="let image of PhotoList"
       src="{{PathFolder+image.ImageNameO}}"
       [attr.imageSrc]="PathFolder+image.ImageNameO"
       [attr.thumbSrc]="PathFolder+image.ImageNameO">
</div>  
`

`GalleryModule.withConfig({
  loadingMode: 'indeterminate'
}),
`

I see your example but not working
