### ISSUE TITLE
NullInjectorError: No provider for Renderer!

### ISSUE THREAD

**Issue by anishchcenko** [MurhafSousli/ngx-gallery#317]
#### What is the expected behavior?
after enable Ivy on Angular 8 -  have errore

#### What is the current behavior?
ERROR NullInjectorError: R3InjectorError(GyModule)[Renderer -> Renderer -> Renderer -> Renderer]: 
  NullInjectorError: No provider for Renderer!

#### Which versions are you using for the following packages?

Angular: 8.2.14
Angular CDK: 8.2.3
Angular CLI: 8.3.22
Typescript: 3.5.3
Gallery:  5.10.0

**Comment by MurhafSousli** [comment]
There is no such Gallery v5.10.0? the latest current version is v4.0.3 you are probably mistaken in the repo
