### ISSUE TITLE
Gallery do not show large image

### ISSUE THREAD

**Issue by TheNemus** [MurhafSousli/ngx-gallery#320]
I installed the gallery in my Angular 9 project with the most basic approach:

`<gallery [items]="galleryModel" thumbPosition="left"></gallery>`

While thumbnails are loaded and showed correctly, the large images are not visible. Instead it shows me a yellow triangle and this message:

> "unable to load the image"

No errors, no warning, **but in the network panel I can see the image XHR calls that successed**. Here is the object I passed to it (i tested personally the urls, they works):

```
[ 
  { 
    "data":{ 
      "thumb":"/api/sbk-img?id=d4eba93c-2917-4de1-90c0-1e4110a1c67b_t&session=3331a386-f718-4ec0-a7ee-27567695d3e6",
      "src":"/api/sbk-img?id=d4eba93c-2917-4de1-90c0-1e4110a1c67b&session=3331a386-f718-4ec0-a7ee-27567695d3e6"
    },
    "type":"image"
  },
  { 
    "data":{ 
      "thumb":"/api/sbk-img?id=52a00027-a9f9-4a46-b517-20f9452d49c6_t&session=3331a386-f718-4ec0-a7ee-27567695d3e6",
      "src":"/api/sbk-img?id=52a00027-a9f9-4a46-b517-20f9452d49c6&session=3331a386-f718-4ec0-a7ee-27567695d3e6"
    },
    "type":"image"
  }
]
```

And here the rendered image component:

`<gallery-image class="ng-tns-c118-3 ng-star-inserted g-image-error" ng-reflect-src="/api/sbk-img?id=d4eba93c-2917-" ng-reflect-mode="determinate">`

As you can see, the url is truncated. Can you give me some advice in order to fix this?

Thank you.

**Comment by MurhafSousli** [comment]
I cannot help without reproduction, I am sorry
