### ISSUE TITLE
<gallery> component  unable to render YouTube video consistently in Angular 9

### ISSUE THREAD

**Issue by ironstine** [MurhafSousli/ngx-gallery#321]
#### What is the expected behaviour?

<gallery> component can render YouTube video without a TypeError in Angular 9

I.e. this.galleryRef.addYoutube({...}) 

#### What is the current behaviour?

TypeError: Cannot read property 'nativeElement' of undefined.

The stackblitz below shows the video unable to render at all in the component. I do however have the video rendering and functioning outside of stackblitz, the TypeError is still present though.

#### What are the steps to reproduce?

https://stackblitz.com/edit/ngx-gallery-g5bijs

#### Which versions are you using for the following packages?

Angular: 9.0.1
Angular CDK: 9.0.0
Angular CLI: 9.0.1
Typescript: 3.7.4
Gallery: 4.0.3

#### Is there anything else we should know?

Starting with version 9, the resolution strategy for @ViewChild and @ContentChild queries defaults to false , which means query results will be available in ngAfterViewInit unless specified otherwise (i.e. {static: true}).

https://angular.io/guide/static-query-migration

The ngx-gallery core code in the file gallery-iframe.component.ts looks to be affected by this change.

https://github.com/MurhafSousli/ngx-gallery/blob/8dea5fc1bfbe9767824e0b9e69601e794ed7a5e7/projects/core/src/lib/components/templates/gallery-iframe.component.ts#L29

and

https://github.com/MurhafSousli/ngx-gallery/blob/8dea5fc1bfbe9767824e0b9e69601e794ed7a5e7/projects/core/src/lib/components/templates/gallery-iframe.component.ts#L22

**Comment by MurhafSousli** [comment]
This will be fixed in v5 beta, you can install it now `npm i ng-gallery`

**Comment by ironstine** [comment]
Hey Murhaf,

I refactored to use the new Angular 9 package as described here => https://github.com/MurhafSousli/ngx-gallery/pull/326

My build process now fails with the message: 

```
ERROR in The target entry-point "ng-gallery/lightbox" has missing dependencies:
 - ngx-gallery
```

From what I can see, the lightbox module has a dependency on and external lib called 'ngx-gallery

https://github.com/MurhafSousli/ngx-gallery/blob/ae2fa0d4376680f5e903d99c94788b82cdf4a2fe/projects/ngx-gallery/lightbox/src/lightbox.module.ts#L5

Let me know if you need any further info.

**Comment by MurhafSousli** [comment]
I mentioned in the changelog it is `ng-gallery` not `ngx-gallery` ... that package is not mine!

**Comment by ironstine** [comment]
@MurhafSousli perhaps you may not have understood what I was trying to convey above. It looks like it is _your_ `ng-gallery` package which contains the references to ngx-gallery.

Apologies if I am missing something here.

**Comment by ironstine** [comment]
Hey @MurhafSousli, wondering if you could please point me in the right direction? Am I missing something here?

**Comment by MurhafSousli** [comment]
Oh good catch!! thanks

**Comment by ironstine** [comment]
Confirming 5.0.0-beta.2 closes this issue, thanks a lot for your help with his @MurhafSousli, really appreciate it!
