### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by omardoma** [MurhafSousli/ngx-gallery#322]
#### What is the expected behavior?
Gallery should adapt to the document's direction (LTR, RTL)

#### What is the current behavior?
Images are offscreen, the translation logic is in the LTR direction so its not showing.

#### What are the steps to reproduce?
Adjust the html element direction to rtl

#### What is the use-case or motivation for changing an existing behavior?
Support bilingual webapps that requires RTL such as Arabic

#### Which versions are you using for the following packages?

Angular: ~8.2.14
Angular CDK: ^8.2.2
Angular CLI: ~8.3.24
Typescript: ~3.5.3
Gallery: ^4.0.3

**Comment by MurhafSousli** [comment]
Can you reproduce it in a stackblitz?

**Comment by samizarraa** [comment]
Still not work correctly when use it on RTL app direction

Angular: 9.1.11
Angular CDK: 9.2.4
Angular CLI: 9.1.8
Typescript: 3.7.5
Gallery: 5.0.0-beta.0

**Comment by aosaimy** [comment]
As a workaround, you can add:
`lightbox {
    direction: ltr;
}`

The navigation is still left-to-right (unpreferable).

**Comment by MurhafSousli** [comment]
This will be fixed in the next major version

**Comment by kfirufk** [comment]
I didn't notice that that's what breaks lightbox, direction:rtl resolves it.

what happens now in lightbox with direction rtl with latest angular is that only the first image is visible and the thumbnails 
are rotated to the wrong direction
