### ISSUE TITLE
Different config for Lightbox and Gallery?

### ISSUE THREAD

**Issue by ImTung** [MurhafSousli/ngx-gallery#327]
Hi there,
I'm using a gallery with options:
```
<gallery [id]="galleryId" [items]="photos" [imageSize]="'cover'" [counter]="false"
        (itemClick)="onGalleryClick($event)" [dots]="true" [thumb]="false"></gallery>
```

When an item clicked, I want to call a lightbox with Thumb = true, imageSize="contains".
How can I open a lightbox with a different config?

#### Which versions are you using for the following packages?

Angular: 9.0
Angular CDK: 9.1
Angular CLI: 9.0
Typescript:
Gallery: 5.0.0-beta.0

**Comment by MurhafSousli** [comment]
@ImTung Assume your lightbox gallery id is "lightbox", get the galleryRef e.g. `const galleryRef = gallery.getRef('lightbox')` of that lightbox, then use `galleryRef.setConfig(...)`

**Comment by ImTung** [comment]
Oh wow, thank you so much @MurhafSousli
