### ISSUE TITLE
Swipes do not work after updating from Angular 6 to Angular 9

### ISSUE THREAD

**Issue by Never7Dice** [MurhafSousli/ngx-gallery#328]
Horizontal swipes from image to image stopped working after upgrading angular, it was working before, I installed hammerjs of version 2.0.8 and imported HammerModule to App.module, but it still doesn't work.

I use gallery like this
`<gallery *ngIf="multipleImages" [items]="multipleImages" [counter]="false"></gallery>`

```
      this.multipleImages = data.map(i => {
        return new ImageItem({ src: i, thumb: i});
      });
```

Angular: 9.0.6
Angular CDK: 9.1.3
Angular CLI: 9.06
Typescript: 3.7.5
Gallery: 5.0.0-beta.0

**Comment by MurhafSousli** [comment]
You still have to import hammerjs yourself as mentioned in the docs

**Comment by Never7Dice** [comment]
Angular migration deleted the import from code :(
`import 'hammerjs';`
Introducing it back fixed the issue, thanks.
