### ISSUE TITLE
Custom Template for Gallerize?

### ISSUE THREAD

**Issue by seanmavley** [MurhafSousli/ngx-gallery#334]
I'm currently using gallerize like this, and it's working fine

```
<mat-grid-list
    class="mt-3"
    cols="3"
    rowHeight="1:1"
    *ngIf="images$ | async as images"
    gallerize
  >
    <mat-grid-tile *ngFor="let image of images">
      <img
        [src]="
          myImage.getResizedImage('/storage/uploads/' + image.path, 1920, 1080)
        "
        [attr.imageSrc]="
          myImage.getResizedImage('/storage/uploads/' + image.path, 1920, 1080)
        "
        [attr.thumbSrc]="
          myImage.getResizedImage('/storage/uploads/' + image.path, 200, 150)
        "
      />
    </mat-grid-tile>
  </mat-grid-list>
```

I happen to have description for the images, which I want shown up when the gallery modal shows up.

Using `gallerize` what are my options? 

Would I have to resort to using the `<gallery ...></gallery>` component to get the beauty of custom templates? And would the `<gallery>` component offer the flexibility of using, say my own `<mat-grid>`?

**Comment by MurhafSousli** [comment]
Yes, you can, by setting the itemTemplate in the gallery ref config

Define your custom gallery item template like:
```html
<ng-template #itemTemplate
             let-index="index"
             let-type="type"
             let-data="data"
             let-currIndex="currIndex">
  <span *ngIf="type === 'image' && index === currIndex" 
        [@slideAnimation] 
        class="item-text">
    {{data?.title}}
  </span>
</ng-template>
```
```ts
@ViewChild('galleryCustomTemplate') galleryCustomTemplate;

ngAfterViewInit() {
  this.gallery.ref('galleryId').setConfig({
    itemTemplate: this.galleryCustomTemplate
  });
}
```

**Comment by seanmavley** [comment]
> Yes, you can

Awesome. For the above example, you're using the `gallerize` directive or the `<gallery>` component?

**Comment by MurhafSousli** [comment]
gallerize

**Comment by seanmavley** [comment]
Closed? Okay, well, I'm still lost with all how that comes together to get it working.

Again, this is what I have

```
  <mat-grid-list
    class="mt-3"
    cols="3"
    rowHeight="1:1"
    *ngIf="images$ | async as images"
    gallerize
  >
    <mat-grid-tile *ngFor="let image of images">
      <img
        [src]="
          myImage.getResizedImage('/storage/uploads/' + image.path, 1920, 1080)
        "
        [attr.imageSrc]="
          myImage.getResizedImage('/storage/uploads/' + image.path, 1920, 1080)
        "
        [attr.thumbSrc]="
          myImage.getResizedImage('/storage/uploads/' + image.path, 200, 150)
        "
      />
    </mat-grid-tile>
  </mat-grid-list>
```

You say I should add in a custom gallery itemtemplate like so:

```
<ng-template #itemTemplate
             let-index="index"
             let-type="type"
             let-data="data"
             let-currIndex="currIndex">
  <span *ngIf="type === 'image' && index === currIndex" 
        [@slideAnimation] 
        class="item-text">
    {{data?.title}}
  </span>
</ng-template>
```

Fine, added

Now, this is what confuses me. You say I should create this. Why? 

```
@ViewChild('galleryCustomTemplate') galleryCustomTemplate;
```

I don't have any `galleryCustomTemplate`. I'm not sure where you got that from. Are you implying I should create a `galleryCustomTemplate`? What contents do I put in it?

And then this:

```
ngAfterViewInit() {
  this.gallery.ref('galleryId').setConfig({
    itemTemplate: this.galleryCustomTemplate
  });
}
```

I assume I should do a 

```
constructor(private gallery: Gallery) {}
```

And then the `galleryId`, I set it in the component and template as `gallerize="galleryId"` or I set it only on component, or only on template?

Will appreciate a full picture help. I don't necessarily need a copy pasted code answer from you. I need what to do, as this wasn't any helpful in a complete way.

> Yes, you can, by setting the itemTemplate in the gallery ref config. Define your custom gallery item template like:

**Comment by MurhafSousli** [comment]
Oh sorry,
```
<ng-template #galleryCustomTemplate
             let-index="index"
             let-type="type"
             let-data="data"
             let-currIndex="currIndex">
  <span *ngIf="type === 'image' && index === currIndex" 
        [@slideAnimation] 
        class="item-text">
    {{data?.title}}
  </span>
</ng-template>
```

**Comment by seanmavley** [comment]
Thanks for the help. Got it working.

Change I made was comment out this part (that's if one is getting response from endpoint, and using an observable in template, like `images$ | async`
```
  // changeDetection: ChangeDetectionStrategy.OnPush,
```

**Comment by MurhafSousli** [comment]
It should work fine with `OnPush`
