### ISSUE TITLE
How to remove those black bars on small screen ?

### ISSUE THREAD

**Issue by duongle26** [MurhafSousli/ngx-gallery#337]
![image](https://user-images.githubusercontent.com/28813618/82424465-6c96d500-9aaf-11ea-938f-42a648ad43ac.png)

**Comment by MurhafSousli** [comment]
It is written in the docs https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-component-api

```html
<gallery imageSize="cover"></gallery>
```
