### ISSUE TITLE
How to get instance for each images when i use Gallerize

### ISSUE THREAD

**Issue by 51303014** [MurhafSousli/ngx-gallery#339]
I have a chat application with each message is one or more images. 
When the user sends each image input is the latest data. 
I have a question: I want to each image is instance individually.

#### What is the expected behavior?
I want to each image is an instance individually.

#### What is the current behavior?
Data is not independent.

#### What are the steps to reproduce?
When the message sent. I will update the message into the component gallery.
But when I click any images and then it gets images latest that do not latest I click

#### What is the use-case or motivation for changing an existing behavior?

  <div class="container"
         gallerize="gallery-1">
      <img *ngFor="let image of files"
           [src]="image.src"
           [attr.imageSrc]="image.src"
           [attr.thumbSrc]="image.src">
    </div>

#### Which versions are you using for the following packages?

Angular:latest
Angular CDK:latest
Angular CLI: latest
Typescript: 3.7.5
Gallery: latest

#### Is there anything else we should know?

![82536519-c90ef880-9b72-11ea-87cb-6dd266e36ae9](https://user-images.githubusercontent.com/17430644/82537436-396a4980-9b74-11ea-8f4e-743b7b5472fd.png)

**Comment by MurhafSousli** [comment]
Gallerize directive works on pre rendered items, so you should do it manually with the lightbox without the gallerize directive.
