### ISSUE TITLE
Thumbnails should always use the available space

### ISSUE THREAD

**Issue by axos88** [MurhafSousli/ngx-gallery#340]
Related #289

in the gallery component:

Currently when the first thumnail (and respectively the last) is selected, the thumnails are pushed to the right, half of the available space being empty.
This sliding behaviour looks awesome, and is super useful but I would like an option to keep as many thumnails in view as there is space for, and when the first or last thumnails are selected, they should be moved the the far left or far right edge of the container. Having half of the thumnail view empty looks odd to me, and unnecesarily constrains the number of thumnails i can see and move to with a single click.

When the 10th thumbnail of 40 is selected, it should be moved to 25% of the container,
When the middle thumnail is selected, it should be positioned in the middle, 
when the last thumnail is selected it should be positioned at the far right / bottom, etc.

**Comment by MurhafSousli** [comment]
Unfortunately, this is currently not possible

**Comment by axos88** [comment]
Yes, I'm aware, that's why this is a feature request :)

**Comment by MurhafSousli** [comment]
Fixed in v5.1.1
