### ISSUE TITLE
Opening lightbox from <gallery>

### ISSUE THREAD

**Issue by axos88** [MurhafSousli/ngx-gallery#341]
How can I open the lightbox when an item (not thumnail) is clicked in a <gallery>?

**Comment by MurhafSousli** [comment]
Same usage

```html
<a lightbox="{{index}}">
```

if you want to target a specific gallery instance

```html
<a lightbox="{{index}}" gallery="{{galleryId}}">
```

**Comment by axos88** [comment]
But there are no anchors to target!

<gallery [items]="galleryItems></gallery>

Where to put the lightbox directive here? The images are generated by the gallery component internally. Not even from the item-template do I have access to that.

**Comment by MurhafSousli** [comment]
@axos88 ahh if you want to open gallery item inside a lightbox, see the docs here https://github.com/MurhafSousli/ngx-gallery/wiki/Gallerize-Examples#gallerize-on-gallery-component

**Comment by axos88** [comment]
Ah gotcha. Thanks
