### ISSUE TITLE
Cannot add multiple gallery component on a page

### ISSUE THREAD

**Issue by fiegam** [MurhafSousli/ngx-gallery#343]
#### What is the expected behavior?
When adding multiple instances of the gallery component on a page, I would expect instances do not influence each other. 

#### What is the current behavior?
Currently all instances always show exactly the same content. The state is shared between instances.

#### What are the steps to reproduce?
The simple way to reproduce this is just add two or more instances of the gallery component in the same page. 
https://stackblitz.com/edit/ngx-gallery-kasmty
Each action on one of the instance is taken on all instances

**Comment by MurhafSousli** [comment]
You are using the same id for different galleries, each gallery must have a unique id, here is a fixed usage https://stackblitz.com/edit/ngx-gallery-6emfhp?file=src/app/home/home.component.html
