### ISSUE TITLE
Angular 9 with universal & lazyload module error

### ISSUE THREAD

**Issue by annndddy** [MurhafSousli/ngx-gallery#345]
#### What is the expected behavior?
Run without error

#### What is the current behavior?
When the app init, 
ERROR ReferenceError: XMLHttpRequest is not defined
will occur at server side

#### What are the steps to reproduce?
1. add ngx-gallery component to a feature lazyload module
2. import GalleryModule in a feature lazyload module
3. start the server using npm run build:ssr && npm run serve:ssr
4. go to the lazyload route and the error occur

#### What is the use-case or motivation for changing an existing behavior?
fix error

#### Which versions are you using for the following packages?

Angular: 9.1.9
Angular CDK: 9.2.4
Angular CLI: 9.1.7
Typescript: 3.8.3
Gallery: 5.0.0-beta.0

#### Is there anything else we should know?
Same error happen if HttpClientModule is import in feature lazyload module, I think it is a similar case

**Comment by mishkamishka47** [comment]
This issue has been fixed since 0433d7080fe72abdac3bde4500f2a781f2236ae5 but has yet to be published to NPM, unfortunately.

**Comment by MurhafSousli** [comment]
[](url)
