### ISSUE TITLE
Lightbox start/exit animation options

### ISSUE THREAD

**Issue by ivanbeldad** [MurhafSousli/ngx-gallery#346]
#### What is the expected behavior?
Lightbox closes with a nice animation.

#### What is the current behavior?
Lightbox closes immediately, in my case using a custom item template the problem is bigger, causing flickering on the screen.

#### What are the steps to reproduce?

- Install any version over 3.3.1
- Open a lightbox and close it

Example (using an already working example from 3.3.1):
https://stackblitz.com/edit/ngx-gallery-imageviewer-dftnpz

#### Which versions are you using for the following packages?

Angular: 6 - 9
Angular CDK: 6 - 9
Angular CLI: 6 - 9
Typescript: 2.7 - 3.8
Gallery: 4.0.0 - 5.0.0-beta.2

**Comment by MurhafSousli** [comment]
It turned out that the animation is working properly, it just has tiny time 75ms, we are using the same Material dialog animation

https://github.com/angular/components/blob/master/src/material/dialog/dialog-animations.ts

**Comment by MurhafSousli** [comment]
I will convert this into a feature and add options to change the default start and exit times for the lightbox animation
