### ISSUE TITLE
Open lightbox for one image without thumb

### ISSUE THREAD

**Issue by samizarraa** [MurhafSousli/ngx-gallery#348]
#### What is the expected behavior?
Use lightbox like directive for one image only and without thumb

#### What is the current behavior?
We should use it for gallery only

#### Which versions are you using for the following packages?

Angular: 9.1.11
Angular CDK: 9.2.4
Angular CLI: 9.1.8
Typescript: 3.7.5
Gallery: 5.0.0-beta.0

**Comment by MurhafSousli** [comment]
Didn't get the issue! you can ofcourse decide not to show thumbnails 

```ts
const galleryRef = this.gallery.ref(this.galleryId, {
      thumb: false
});
```
