### ISSUE TITLE
Caption support

### ISSUE THREAD

**Issue by samizarraa** [MurhafSousli/ngx-gallery#349]
#### What is the expected behavior?
Caption on gallery footer

#### What is the current behavior?
No caption support

#### Which versions are you using for the following packages?

Angular: 9.1.11
Angular CDK: 9.2.4
Angular CLI: 9.1.8
Typescript: 3.7.5
Gallery: 5.0.0-beta.0

**Comment by MurhafSousli** [comment]
https://ngx-gallery.netlify.app/#/advanced
