### ISSUE TITLE
Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by ankitjainOfficial** [MurhafSousli/ngx-gallery#353]
#### What is the expected behavior?
There should be no error

#### What is the current behavior?
TypeError: Cannot read property 'nativeElement' of undefined
    at GalleryVideoComponent.set pauseVideo [as pauseVideo] (ngx-gallery-core.js:1512)
    at setInputsForProperty (core.js:8657)
    at elementPropertyInternal (core.js:7703)
    at ɵɵproperty (core.js:13788)
    at GalleryItemComponent_ng_container_0_gallery_video_2_Template (ngx-gallery-core.js:254)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ivy-aap6wb

#### Which versions are you using for the following packages?

Angular: 10
Angular CDK: 10
Angular CLI: 10
Typescript: 3.9
Gallery: 4

#### Is there anything else we should know?
I don't think so. 

Please let me know, if I did a mistake somewhere. Thanks. :)

**Comment by MurhafSousli** [comment]
That's weird especially that it seems to work but still throwing the error

**Comment by ankitjainOfficial** [comment]
Yes, this is working. And, I could not find any problems in its working.

**Comment by cybercussion** [comment]
Same boat here - 
[Error] ERROR – TypeError: undefined is not an object (evaluating 'this.iframe.nativeElement')
TypeError: undefined is not an object (evaluating 'this.iframe.nativeElement')

Was using 5.0.0-beta0 getting ahead?

Also notice videos don't always load up, some do and some after some time.

**Comment by GlauberF** [comment]
same problem here

![Captura de Tela_selecionar área_20200722142017](https://user-images.githubusercontent.com/11314585/88207795-af4b6980-cc26-11ea-8171-856c33fff929.png)


![Captura de Tela_selecionar área_20200722142048](https://user-images.githubusercontent.com/11314585/88207800-b1152d00-cc26-11ea-9022-9f31f7d566b0.png)

**Comment by MurhafSousli** [comment]
@cybercussion I am aware of this, It is not related to the change detection, but it seems to be a browser issue, and it behaves differently in different browsers. it is caused by slide in the new video, try to disable the `transition` in your global styles and see if the videos load properly

```scss
.g-slider {
   transition: transform 400ms cubic-bezier(0.5, 0, 0.5, 1);
}
```
For this I will investigate a workaround in the future.

@GlauberF Thanks for pointing out, I will fix that when I get the time.

**Comment by cybercussion** [comment]
Seems somewhat related to https://github.com/vaadin/vaadin-grid/issues/411 and also seems like a issue with a element with a *ngIf on it.  The one post further down on that page seemed to wrap some code with a setTimeout (my classic go to when natively coding in JavaScript hah!
