### ISSUE TITLE
gallery is not known element in angular 9

### ISSUE THREAD

**Issue by shivabe** [MurhafSousli/ngx-gallery#355]
thumbnail image not showing and with following error
'gallery' is not a known element:
    1. If 'gallery' is an Angular component, then verify that it is part of this module.
    2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by MurhafSousli** [comment]
Use the latest version beta version, you can find the new instruction here https://github.com/MurhafSousli/ngx-gallery/pull/326
