### ISSUE TITLE
Content Projection Within Item Template Does Not Work When Navigating To Previous Item

### ISSUE THREAD

**Issue by jrosenbecker** [MurhafSousli/ngx-gallery#356]
I'm not sure if this is a bug or a feature request, but the behavior I found felt odd to me because it partially worked. Clicking on the back button when viewing the lightbox image stops my content projection from rendering.

#### What is the expected behavior?
When I use an `itemTemplate` to place content on the lightbox item, `ng-content` should render as you navigate between gallery items.

#### What is the current behavior?
The content projected using `ng-content` displays when you open the lightbox, and when you click on the arrow icon to view the next image, but it disappears when you click on the arrow icon to view the previous image

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/ngx-gallery-item-template-projection

#### What is the use-case or motivation for changing an existing behavior?
I would like to be able to overlay items over the lightbox dynamically in a reliable way.

#### Which versions are you using for the following packages?

Angular: 9.1.0
Angular CDK: 9.2.0
Angular CLI: 9.1.0
Typescript: 3.8.3
Gallery: 5.0.0-beta.2

**Comment by MurhafSousli** [comment]
Well, it is an `*ngIf` that show/hide the element, I am not sure if you can do it with ng-content, you may want try animations to achieve to delay hiding the element like in the demo https://ngx-gallery.netlify.app/#/advanced
