### ISSUE TITLE
Wrong npm package badge in demo

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-gallery#362]

**Comment by pmroczko9** [comment]
Could it be this is meant here? On page https://ngx-gallery.netlify.app/#/getting-started/

We've got the following:

![obraz](https://user-images.githubusercontent.com/78854159/131266346-d16005d3-268e-46e3-a14e-832c968d940e.png)

**Comment by MurhafSousli** [comment]
Fixed the demo
