### ISSUE TITLE
Ng-gallery load error on Stackblitz

### ISSUE THREAD

**Issue by marasi** [MurhafSousli/ngx-gallery#363]
Hi,

I am struggling with the Gallerize feature on `<gallery gallerize></gallery>` in VSCode.

So I have started to use Sackblitz... But if I started an App from scratch and try to import ng-gallery it returns an error:

> Error in ~/src/main.ts
> ngcc failed to run on ng-gallery@5.0.0.

Live app test:

[https://stackblitz.com/edit/angular-ng-gallery-test?file=src/app/app.component.html](url)

Well, I need some help. Because I am using Angular for three weeks by now.

Thanks in advice. I will appreciate any advice.

Maurício

**Comment by MurhafSousli** [comment]
You haven't imported the module in your stackblitz. here is how it should look like https://stackblitz.com/edit/ngx-gallery?file=src%2Fapp%2Fapp.module.ts

**Comment by marasi** [comment]
Thank you @MurhafSousli
