### ISSUE TITLE
Configuration of item/thumb templates for lightbox

### ISSUE THREAD

**Issue by christian-laakmann** [MurhafSousli/ngx-gallery#364]
#### What is the expected behavior?
I would like to configure custom thumb- and item templates for lightboxes as well. 
When using `gallerize` on a `gallery`, the configured templates of the host component should be used to configure the lightbox as well (with options to provide separate templates for the lightbox, if required)

#### What is the current behavior?
Lightbox does not support configuring custom templates

#### What is the use-case or motivation for changing an existing behavior?
I would like to enable the zoom feature in the lightbox (described here: https://github.com/MurhafSousli/ngx-gallery/wiki/Image-zoom-example) 

#### Which versions are you using for the following packages?

Angular: 10.x
Angular CDK: 10.x
Angular CLI: 10.x
Typescript: 3.9
Gallery: 5.0

**Comment by MurhafSousli** [comment]
You can already do that, set the `thumbTemplate` or `itemTemplate` in the gallery config 

```html
<ng-template #itemTemplate let-index="index" let-type="type" let-data="data" let-currIndex="currIndex">
  <ng-container *ngIf="type === 'imageViewer' && index === currIndex">

    <ngx-imageviewer [src]="data.src"></ngx-imageviewer>

  </ng-container>
</ng-template>
```
```ts
@ViewChild('itemTemplate') itemTemplate: TemplateRef<any>;

ngAfterViewInit() {
  this.gallery.ref('lightbox').setConfig({
    itemTemplate: this.itemTemplate
  })
}
```

I updated the image zoom example here https://stackblitz.com/edit/ngx-gallery-imageviewer?file=src%2Fapp%2Fhome%2Fhome.component.ts
