### ISSUE TITLE
ERROR TypeError: Cannot read property 'nativeElement' of undefined  at GalleryVideoComponent.set pauseVideo [as pauseVideo]

### ISSUE THREAD

**Issue by sahithpaidi** [MurhafSousli/ngx-gallery#366]
#### What is the expected behavior?
Unexpected error 
![image](https://user-images.githubusercontent.com/40169123/97671688-c06e0700-1aae-11eb-8ec2-3360337a30aa.png)

Please suggest me the solution to get through

**Comment by MurhafSousli** [comment]
Please fill the template issue, add which version you are using and try to reproduce the error reproduce it in https://stackblitz.com/edit/ngx-gallery

**Comment by Ash-kosakyan** [comment]
As I see you fixed this issue in version 5.0.0. Can you say when you will push it in NPM.

**Comment by MurhafSousli** [comment]
Sorry for late response, v5.0.0 was published a month ago
