### ISSUE TITLE
Multiple instances of the gallery returns same result

### ISSUE THREAD

**Issue by psemdel** [MurhafSousli/ngx-gallery#369]
Hello,

I have a component where I use twice the gallery. I have 2 sets of images, and different html calls:

<gallery [items]="images_set1"></gallery>
<gallery [items]="images_set2"></gallery>

#### What is the expected behavior?
The two galleries should be different.

#### What is the current behavior?
The two galleries display the same set of image (the last called in the html it seems)

#### What are the steps to reproduce?
https://stackblitz.com/edit/ngx-gallery-l7dood

#### Which versions are you using for the following packages?
Angular: 9
Gallery: 5.0.0

**Comment by MurhafSousli** [comment]
Hi,

For multiple instances use the id input

```html
<gallery id="myFirstGallery"></gallery>
<gallery id="mySecondGallery"></gallery>
```

**Comment by psemdel** [comment]
Thank you, it works!
Issue can be closed.
