### ISSUE TITLE
Lightbox not showing Image

### ISSUE THREAD

**Issue by thomastardy** [MurhafSousli/ngx-gallery#370]
#### What is the expected behavior?
Lightbox should show the configured image.

#### What is the current behavior?
Lightbox only showing a black background.

#### What are the steps to reproduce?
Go to https://ngx-gallery.netlify.app/#/lightbox and click on one of the demo images.
In my case, I've implemented a component very similar to https://github.com/MurhafSousli/ngx-gallery/tree/master/projects/ng-gallery-demo/src/app/pages/lightbox-example.

#### What is the use-case or motivation for changing an existing behavior?
Demo should work.

#### Which versions are you using for the following packages?

Angular: 11.0.4
Angular CDK: 11.0.2
Angular CLI: 11.0.4
Typescript: 4.0.5
Gallery: 5.0.0

**Comment by MurhafSousli** [comment]
Never mind the lightbox demo, I fixed it the src files but haven't built and published the demo, if you follow the docs it will work fine

**Comment by thomastardy** [comment]
Hi @MurhafSousli 

I've only found v4 stackblitz demos and I'm using v5 with the gallery items in an observable.

Can you point me to the stackblitz demo using v5?

**Comment by MurhafSousli** [comment]
Hi @thomastardy, I updated it now https://stackblitz.com/edit/ngx-gallery?file=src%2Fapp%2Fapp.module.ts

Note that the package name is `ng-gallery` not `@ngx-gallery/*`
