### ISSUE TITLE
Prerender via Universal / SSR does not properly render in html

### ISSUE THREAD

**Issue by Judp0m** [MurhafSousli/ngx-gallery#372]
This gallery looks great. I tried it but ran into the following issue:
I need to be able to prerender my pages to html (via Universal SSR).

It all looks good in the client when not using SSR.
But when using SSR, the server hangs indefinitely. (bug #1)
To work around this issue, I set autoplay to true only in the client via [autoPlay]="isBrowser"
The server does not hang anymore (yay)... but the gallery is not loading the images (black image with the white loading circle).
When inspecting the generated html, I can see that the images are not there, even though they have been properly provided to the gallery via [items]="items". Displaying the items manually shows that the server properly populated the "items", but the gallery remains in its initial state.
I tried adding a timeout of 5 seconds, or manually triggering the gallery to set(0) or load(items) but none solve the issue.

This issue is related:
https://github.com/MurhafSousli/ngx-gallery/issues/262#issuecomment-500422662

#### What is the expected behavior?
Properly expand the gallery in the html generated by Angular Universal.

#### What is the current behavior?
The gallery is in its initial state (loading circle)

#### Which versions are you using for the following packages?

Angular: 11.0.5
Angular CDK: 11.0.3
Angular CLI: 11.0.5
Typescript: 4.0.5
Gallery: 5.0.0

**Comment by MurhafSousli** [comment]
I tested it with v7.0.5 and it works fine! closing this... if you still have an issue with SSR please open a new one!
