### ISSUE TITLE
Cannot read property 'nativeElement' of undefined, this time caused by GalleryIframeComponent

### ISSUE THREAD

**Issue by maurice85** [MurhafSousli/ngx-gallery#373]
#### What is the expected behavior?
The gallery must properly show and play an embedded youtube video

#### What is the current behavior?
I am getting the same error that was reported in https://github.com/MurhafSousli/ngx-gallery/issues/353
and its coming from the same method only this time its in  `GalleryIframeComponent`

#### What are the steps to reproduce?
Please see the closed issue mentioned above, its is nearly the exact same error only this time it is not `GalleryVideoComponent`
But `GalleryIframeComponent` that is causing the issue. You've pushed a fix for the bug in `GalleryVideoComponent` in this commit https://github.com/MurhafSousli/ngx-gallery/commit/ff10363e03090d8dfc88fd44674b3cb655399c58

#### Which versions are you using for the following packages?

Angular: 9
Angular CDK: 9
Angular CLI: 9
Typescript:
Gallery: 5.0.0.Beta.0

#### Is there anything else we should know?

 Could you please make the same fix for `GalleryIframeComponent` and any other components that may still have the same bug?
Right now only `GalleryVideoComponent` has the fix.

Thank you!

**Comment by MurhafSousli** [comment]
This should be fixed in v5.0.0, try it out and let me know if it still happens in v5.0.0, closing for now....
