### ISSUE TITLE
closeIcon

### ISSUE THREAD

**Issue by iAVP** [MurhafSousli/ngx-gallery#377]
Hi, I need to change closeIcon in Lightbox. You have in the lightbox configuration those property. But it stay the old svg forever.

```
<i _ngcontent-vnj-c22="" aria-label="Close" class="g-btn-close ng-tns-c22-18"><!--?xml version="1.0" encoding="UTF-8"?-->
<svg width="512px" height="512px" enable-background="new 0 0 47.971 47.971" version="1.1" viewBox="0 0 47.971 47.971" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
	<path d="M28.228,23.986L47.092,5.122c1.172-1.171,1.172-3.071,0-4.242c-1.172-1.172-3.07-1.172-4.242,0L23.986,19.744L5.121,0.88   c-1.172-1.172-3.07-1.172-4.242,0c-1.172,1.171-1.172,3.071,0,4.242l18.865,18.864L0.879,42.85c-1.172,1.171-1.172,3.071,0,4.242   C1.465,47.677,2.233,47.97,3,47.97s1.535-0.293,2.121-0.879l18.865-18.864L42.85,47.091c0.586,0.586,1.354,0.879,2.121,0.879   s1.535-0.293,2.121-0.879c1.172-1.171,1.172-3.071,0-4.242L28.228,23.986z" fill="#fff"></path>
</svg>
</i>
```

..and it replaced my own icon at each gallery navigation :(

Also some "nice to have": why only closeIcon? I need our set our Prev/Next/Close icons. 
Prev and Next buttons working over insertAdjacentHTML perfect. But the problem with closeIcon makesproblems

**Comment by MurhafSousli** [comment]
Please add a reproduction [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)

**Comment by MurhafSousli** [comment]
the close and nav icons options are working properly, here is a [demo](https://stackblitz.com/edit/ngx-gallery-qfwymg?file=src%2Fapp%2Fhome%2Fhome.component.ts)
