### ISSUE TITLE
Lightbox does not show images of large gallery when browser has certain width

### ISSUE THREAD

**Issue by androman** [MurhafSousli/ngx-gallery#378]
#### What is the expected behavior?

Lightbox should display image when opening on gallery with many images.

#### What is the current behavior?

If the gallery has something like 190 images and you click on one image to open Lightbox then, depending on the width of the browser window, the image is not shown. The thumbnails are.

Actually I think, the more images you have in the gallery, the smaller the browser window has to be in order to display the image.

#### What are the steps to reproduce?

Tested on Chrome 88.0 and Firefox 85.0:

- open the file [home.components.ts on Stackblitz](https://stackblitz.com/edit/ngx-gallery-lightbox?file=src%2Fapp%2Fhome%2Fhome.component.ts)
- increase the number of items in `const data` until you have about 190 - 200 images. (I copied the existing 4 images many times)
- Click on _Open in new window_
- Click on one of the images
- If you see the image (the large image, not the thumbnails) then make your browser wider until it disappears. (with 192 images I had to make the browser window wider than 1040 pixels).

#### What is the use-case or motivation for changing an existing behavior?

- it's a bug

#### Which versions are you using for the following packages?

Angular: 11.1
Angular CDK: 11.1.1
Angular CLI: 11.1.1
Typescript: 4.1.2
Gallery: 5.0.0

#### Is there anything else we should know?

The browser debugger shows that the large images are loaded correctly and it shows me the image. Lightbox does not.

**Comment by androman** [comment]
I don't really see how it works, but I think I think this [line](https://github.com/MurhafSousli/ngx-gallery/blob/fe5dbc88c441e8cfb2733a1a35118842ffe86a65/projects/ng-gallery/src/lib/components/gallery-slider.component.ts#L163) in gallery-slider.ts might cause an overflow.

**Comment by MurhafSousli** [comment]
This was brought up before, you can have maximum up to 20-30 items per gallery.

**REASON**

The maximum width allowed is different from a browser to a browser, with the current implementation, we reserve the sum of all items width, so the slider can work.

If the sum of your items width is bigger than the maximum width allowed by the browser, it will not work.

The solution is by using a virtual scroll which I am working on for the next version, so for the current version it is a no fix.

**Comment by androman** [comment]
Ok, thank you for the explanation. I will have to look for another gallery/lightbox then. 

Did I miss it or is this limitation missing in the documentation?

**Comment by NegruAncuta** [comment]
Hi, has this issue been solved and if so, which version covers it?
