### ISSUE TITLE
Can't scroll to the top of the thubmnails

### ISSUE THREAD

**Issue by draganpodvezanec** [MurhafSousli/ngx-gallery#382]
When thumbnails are on left or right, and there's more thumbnails (so they overflow parent container), a vertical scroll appears and that's ok. But when you select the last thumbnail, the scrollbar is not visible anymore and g-slider is not scrollable anymore to the beginning, so you can't scroll back to the first slide. Panning the slides to the top works, but scroll doesn't.

I guess there is some CSS issue with the flexbox container which overflows the parent container.

#### What is the expected behavior?

Scroll should work normally always.

#### What is the current behavior?

The scrollbar disappears when the last item is selected, and scrolling up is not possible anymore.

**Comment by JosepAlacid** [comment]
10 months with no updates. This is a dead project.

**Comment by MurhafSousli** [comment]
@draganpodvezanec I could not reproduce it. your issue is not descriptive enough, what option did you use? please follow the issue instruction and either a reproduction or a screenshot

**Comment by MurhafSousli** [comment]
Closing as doesn't have reproduction
