### ISSUE TITLE
Multiple gallerize in one document load only last used

### ISSUE THREAD

**Issue by memee** [MurhafSousli/ngx-gallery#384]
When using `[gallerize]` directive multiple times in document and clicking on any image within those galleries, brings preview only for last defined gallery (images contained within last occurence of `[gallerize]`)

#### What is the expected behavior?
I can preview images for each instance of `[gallerize]` directive.

#### What is the current behavior?
I can preview images only for last `[gallerize]` directive used and when clicking on images from previous instances the last instance gallery image is shown with some glitches.

#### What are the steps to reproduce?
Use `[gallerize]` multiple times.

https://stackblitz.com/edit/ngx-gallery-hife9s?file=src/app/home/home.component.html

#### What is the use-case or motivation for changing an existing behavior?
Having multiple galleries in the document

#### Which versions are you using for the following packages?

Angular: 10.1.5
Angular CDK: 10.2.7
Angular CLI: 10.1.6
Typescript: 4.0.3
Gallery: 5.0.0

**Comment by lgaida** [comment]
Hi @memee
you need to use distinct ids when using `gallerize` multiple times.
```
<div class="gallerize-example">
  <h2>Gallerize Example</h2>
  <h3>First gallery</h3>
  <p class="container" gallerize="galleryOne">
    <img *ngFor="let img of imageData3" [src]="img">
  </p>
  <h3>Second gallery</h3>
  <p class="container" gallerize="galleryTwo">
    <img *ngFor="let img of imageData2" [src]="img">
  </p>
</div>
```
If you don't use distinct ids the `gallerize` directive will fallback to the [default gallery-id "lightbox"](https://github.com/MurhafSousli/ngx-gallery/blob/aae0725b40eb9472bfb139b83485fc51a3102642/projects/ng-gallery/lightbox/src/gallerize.directive.ts#L42), so every use of `gallerize` will override the previous gallerized component.

**Comment by MurhafSousli** [comment]
in ur stackblitz, you did not add `gallerize="galleryOne"` and `gallerize="galleryTwo"`, here is a fixed one https://stackblitz.com/edit/ngx-gallery-nmqxvo?file=src/app/home/home.component.html
