### ISSUE TITLE
navigating a gallery with only youtube videos using galleryRef.addYoutube causes the application to reload and sometimes one or more of the videos does not load

### ISSUE THREAD

**Issue by finrojo** [MurhafSousli/ngx-gallery#385]
#### What is the expected behavior?
To be able to have a gallery of youtube videos and for it to load everytime

#### What is the current behavior?
I load 3 videos using the galleryRef.addYoutube function. All videos appear as they should but when navigating to the end and then going back I can see my application.component.ts is firing and sometimes I get a blank page where a video should be

#### What are the steps to reproduce?

Adapt the basic example on StackBlitz to use the AddYouTubeVideo function
https://stackblitz.com/edit/ngx-gallery-rnes1x?file=src%2Fapp%2Fhome%2Fhome.component.html

#### Which versions are you using for the following packages?

Angular: 11.2.11
Angular CDK: 10.2.7
Angular CLI: 11.2.10
Typescript: 4.1.5
Gallery: ^5.0.0

**Comment by MurhafSousli** [comment]
Tested with ngx-gallery@7.0.4 and could not reproduce it, the items are displayed as should be even after navigating, I think this happens only in stackblitz environment
