### ISSUE TITLE
Can't set config

### ISSUE THREAD

**Issue by MarcManhart** [MurhafSousli/ngx-gallery#393]
My template looks like that:
```html
<mat-dialog-content>
  <gallery id="bilderGallery"></gallery>
</mat-dialog-content>
```

my Component like that:
```typescript
public galleryConf: GalleryConfig = {
    thumb: false
  };

//...

ngOnInit() {
    let imagesToRender = this.data.bilder.map((bild: any) => {
         //...  (already working)
    });

    this.galleryRef = this.gallery.ref('bilderGallery');
    this.galleryRef.setConfig(this.galleryConf); // <-- seems not to do anything
    this.galleryRef.load(imagesToRender);
  }

//...
```
Unfortunately the config get ignored. The image loading works but calling setConfig(...) or even writing `<gallery id="bilderGallery" [thumbs]=false></gallery>` won't changing anything. The gallery is loaded always with the default configuration.

What am Im doing wrong?
Thx

**Comment by MurhafSousli** [comment]
Looking at your code, it should work.. but maybe it make sense to try to reproduce in stackblitz

**Comment by EchopixUser** [comment]
What if you try to set the config in the ref() function?
`this.galleryRef = this.gallery.ref('bilderGallery', this.galleryConf);`

**Comment by EchopixUser** [comment]
Also @MurhafSousli if you try to load config in the GalleryModule using forRoot method (you call it withConfig) it will not work. I believe the reason for it not working is following:

In your[ gallery.service.ts](https://github.com/MurhafSousli/ngx-gallery/blob/bc52cf8aeae0f7cc77c6a1369cea7b3399ee73d3/projects/ng-gallery/src/lib/services/gallery.service.ts) you are injecting the config with [GALLERY_CONFIG](https://github.com/MurhafSousli/ngx-gallery/blob/bc52cf8aeae0f7cc77c6a1369cea7b3399ee73d3/projects/ng-gallery/src/lib/services/gallery.service.ts#L18)

However, the service itself is provided in root, and gets created sooner than the module, where the config value is resolved. Therefor [this line](https://github.com/MurhafSousli/ngx-gallery/blob/bc52cf8aeae0f7cc77c6a1369cea7b3399ee73d3/projects/ng-gallery/src/lib/services/gallery.service.ts#L19) will only spread **defaultConfig** and **config** will still be undefined.

**Comment by MurhafSousli** [comment]
@EchopixUser you can inject the token in the root module to set the default config.. regarding withConfig function I am not sure, I haven't tested it after upgrading the service with `providedIn` feature

**Comment by EchopixUser** [comment]
I am providing it in my gallery module which amongst other things sets up your gallery module and hence the issue arises. I don't want to provide it in root, I have a modular architecture and the modules are sealed and independent.

**Comment by AlexType** [comment]
```
ngAfterViewInit(): void {
    this.galleryRef.setConfig(this.config);
}

```
в ngOnInit не успевает

**Comment by MurhafSousli** [comment]
@EchopixUser Providing a token in the root won't effect the modular structure, and won't add the plugin size to your main script if that what concerns you.

**Comment by EchopixUser** [comment]
I have a monorepo with multiple projects, so what concerns me is that I need to provide token with same value in every project. I would rather encapsulate it in my Module that would setup the config in one place for all my apps.

**Comment by MurhafSousli** [comment]
@EchopixUser Can you think of a solution?

**Comment by EchopixUser** [comment]
> @EchopixUser Can you think of a solution?

Don't provide gallery in root by default. let the user chose the providing point.
