### ISSUE TITLE
Lightbox is opening blank, even in your demo

### ISSUE THREAD

**Issue by AlbertoMontalesi** [MurhafSousli/ngx-gallery#395]
![image](https://user-images.githubusercontent.com/23130353/122218952-25109180-ced9-11eb-9f22-0333ba1bc6b1.png)

https://ngx-gallery.netlify.app/#/lightbox

clicking on an image opens up the lightbox in black. The same behavior happens in my app

**Comment by MurhafSousli** [comment]
Dup #370 #375 , there is nothing wrong in the library, if you have an issue, add a reproduction stackblitz

**Comment by pmroczko9** [comment]
Hello! I have noticed the same behavior looking at the demo for the first time. Web page https://ngx-gallery.netlify.app/#/lightbox , viewed with Firefox 91.0.2.

Clicking on one of the pictures:
![obraz](https://user-images.githubusercontent.com/78854159/131266043-59971bcc-f50b-407b-8226-b82dd7afe025.png)

gets you something like this:
![obraz](https://user-images.githubusercontent.com/78854159/131266067-dce0ef35-ba4e-41ed-8e07-be98a172dcb3.png)

I'd say the index isn't being passed right - but I'm still learning how to use this...

**Comment by MurhafSousli** [comment]
there is only a bug in demo usage, but there's nothing wrong in the library https://stackblitz.com/edit/ngx-gallery

**Comment by MurhafSousli** [comment]
Fixed the demo
