### ISSUE TITLE
Library is breaking the app in Internet Explorer.

### ISSUE THREAD

**Issue by barkin94** [MurhafSousli/ngx-gallery#396]
Is there a way to make it work without too much hassle?

**Comment by MurhafSousli** [comment]
I cannot debug the library in IE, if you find out the problem / solution you can post it here

**Comment by barkin94** [comment]
I did fix the problem... kinda.

Apparently, the support for IE had been dropped in Angular 10, which was forcing the builder to skip generating es5 specific files (aka esm5 folder). And since IE cannot recognize es6 syntax, my app was crashing before it even starts. I could not make the builder generate esm5 folder, so I installed v5.0.0-beta.2 because it uses an earlier version of Angular, and the app stopped breaking. However, there seem to be some style issues. For example, the lightbox gallery appears to be aligned to the screen's right.

**Comment by MurhafSousli** [comment]
Honestly, there is no motivation to support IE at all, it has been dropped everywhere including Angular as you mentioned.. You can try to override the styles and if you find the fixes, you can drop your what worked for you in this issue.

I am closing it for now...
