### ISSUE TITLE
Having a mixed images/videos gallery displays the application instead of video

### ISSUE THREAD

**Issue by gherci** [MurhafSousli/ngx-gallery#397]
Hi,

I used it to build this page having some mixed content in it, pictures and some random youtube video: 
![image](https://user-images.githubusercontent.com/10848502/127039172-3b6fc4c7-e5e3-4079-b439-9fe4853adaf9.png)

If i click on arrows to slide next picture after the video and then i return to it it somehow renders the app instead of the video, like this: 
![image](https://user-images.githubusercontent.com/10848502/127039369-ae98beff-3e1f-499c-9885-4e47d4078711.png)

If i continue to click right and the list starts again this is not happening and the video slide displays correctly.
I am using Angular 12. 
Have this ever happened to you? What could trigger this behaviour?

**Comment by MurhafSousli** [comment]
It is unclear what you're asking for, please fill the template issue properly!

**Comment by gherci** [comment]
hi,

i have the gallery implemented like this in template:
```<gallery [items]="images" gallerize></gallery>```
and in the component: 
```
this.images = [
      new ImageItem({
        src: 'https://www.gettyimages.com/gi-resources/images/500px/983794168.jpg',
        thumb: 'https://www.gettyimages.com/gi-resources/images/500px/983794168.jpg'
      }),
      new ImageItem({
        src: 'https://i.pinimg.com/originals/74/64/49/7464497f78fe88669948fe177c6916fe.jpg',
        thumb: 'https://i.pinimg.com/originals/74/64/49/7464497f78fe88669948fe177c6916fe.jpg'
      }),
      new YoutubeItem({
        type: 'video',
        src: '9dblgPmgwU8',
      }),
    ];

```



And it is functioning but with this bug. 
I have 2 pictures and 1 youtube video, when i scroll to the video and then i go back left to a picture, and then i again come back to the video instead of the video, it displays the application as you can see in the recorded.

Check the record screen. 
![youtubeVideoBug](https://user-images.githubusercontent.com/10848502/127123687-5d81cfcc-8490-417c-939f-432c9c22aaad.gif)

**Comment by MurhafSousli** [comment]
Please reopen the issue and don't remove the template, just fill it properly and add the version!
