### ISSUE TITLE
NullInjectorError: No provider for Gallery!

### ISSUE THREAD

**Issue by atoyansk** [MurhafSousli/ngx-gallery#399]
What is the expected behavior?

Image gallery loaded with no errors

What is the current behavior?

Displays the following error:
```
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[GalleryComponent -> Gallery]: 
  StaticInjectorError(Platform: core)[GalleryComponent -> Gallery]: 
    NullInjectorError: No provider for Gallery!
NullInjectorError: StaticInjectorError(AppModule)[GalleryComponent -> Gallery]: 
  StaticInjectorError(Platform: core)[GalleryComponent -> Gallery]: 
    NullInjectorError: No provider for Gallery!
```

In app.module.ts
```
import { GalleryModule } from 'ng-gallery';

imports: [
    ...
    GalleryModule
  ]
```

What are the steps to reproduce?

What is the use-case or motivation for changing an existing behavior?

Which versions are you using for the following packages?

Angular: 8.2.3
Angular CDK: 8.2.3
Angular CLI: 8.3.0
Typescript: 3.5.3
Gallery: 5.0.0

Is there anything else we should know?

**Comment by MurhafSousli** [comment]
Closing as not info provided
