### ISSUE TITLE
Please make the latest version (5.0.0) available for download on npm.

### ISSUE THREAD

**Issue by maurice85** [MurhafSousli/ngx-gallery#404]
You have pushed version 5.0.0 to github on august 9 2020, yet on npmjs the latest version is still set to 5.0.0-beta.
https://www.npmjs.com/package/@ngx-gallery/gallerize
This version still contains the video related bug and i'm unable to update my gallerize version from beta to 5.0.0 using npm.
Could you please change this soon? Thanks!

Regards,

#### Which versions are you using for the following packages?

Angular:
Angular CDK:
Angular CLI:
Typescript:
Gallery:

**Comment by MurhafSousli** [comment]
Use the package https://www.npmjs.com/package/ng-gallery `ng-gallery` not `@ngx-gallery/...`
