### ISSUE TITLE
Responsive height

### ISSUE THREAD

**Issue by priatelko** [MurhafSousli/ngx-gallery#418]
#### What is the expected behavior?
When I have some text content on the slide and I am resizing window, the text is going down and need more container height. Is there a possibility turn on some height reponsivity by its content? Or any solution?

#### What is the current behavior?
Static height. It is needed to make all CSS breakpoints for now.

**Comment by MurhafSousli** [comment]
Can you add a reproduction?

**Comment by priatelko** [comment]
Sure. 
But first question if I don't mistake. Your gallery need fixed height, right? So example bellow in images. gallery has 450px height. But it could be less. This height is a little increased for lower screen resolutions to fix the text in the content, but even if it is 300px height - responsiveness going down, the carousel height should increasing height automatically because of its content. See image 2.

1.
![1](https://user-images.githubusercontent.com/32601471/144580318-1e74d532-a46b-46df-9da4-ce9f410908d1.jpg)

2.
![2](https://user-images.githubusercontent.com/32601471/144580312-a94cea81-fa69-41d0-b068-699015af21fc.jpg)

**Comment by MurhafSousli** [comment]
Ok, I understand the issue, but currently there is the height of the gallery is fixed to user CSS and cannot be dynamic automatically in code, user has to adjust manually.

I believe you can find a JS solution to change the height.

**Comment by priatelko** [comment]
I see.
And can you point me, how to get the heights of each slide in the gallery? I would get each `.ui-carousel-content`. I was looking in API but not sure. Thank you very much.

**Comment by MurhafSousli** [comment]
Here is a [stackblitz example](https://stackblitz.com/edit/ngx-gallery-quu2ac?file=src%2Fapp%2Fhome%2Fhome.component.ts)

**Comment by priatelko** [comment]
Hi Murhaf.
It is very nice solution, but I have an argument to extend that script. Problem is that, when carousel is on top a he is changing height, so the content bellow is moving up and down.  So the script should take the highest one, and stay on this. 👍
Have a nice day.
