### ISSUE TITLE
Gradual loading

### ISSUE THREAD

**Issue by maranmaran** [MurhafSousli/ngx-gallery#432]
#### What is the expected behavior?
Possibility to allow for array of images of different qualities and let them load in order
background: url(high-res), url(low-res) || background: url(low-res), src=url(high-res)

example fiddle: https://jsfiddle.net/45uaLenw/1/

#### What is the current behavior?
We can only provide single URL?

#### What is the use-case or motivation for changing an existing behavior?
Faster loading of lower-res images but allowing for higher-res load over time - better UX

**Comment by MurhafSousli** [comment]
This won't be implemented as a core feature, but you can implement it using your custom template with the `galleryItemDef` https://ngx-gallery-next.netlify.app/?path=/docs/documentations-customtemplates--customtemplatesusage
