### ISSUE TITLE
Copyright notice for images

### ISSUE THREAD

**Issue by nfMalde** [MurhafSousli/ngx-gallery#435]
#### What is the expected behavior?
Provide an option for copyright of the images, since some images with name of the owner and and optional url
Can place the copyright into all corners.
Example option for addImage:
```typescript
galleryRef.addImage({
      src: 'IMAGE_URL',
      thumb: '(OPTIONAL)IMAGE_THUMBNAIL_URL',
      cite: {
              title: 'image-side-i-use-pictures-from',
              url: 'https://....',
             position: 'top-left'//top-right, bottom-left, bottom-right  maybe as enum(?)
      }
    });
```

#### What is the current behavior?
No option available for copyright notices.

#### What is the use-case or motivation for changing an existing behavior?
To fullfill the need of citing images when using external images as built-in option.

#### Which versions are you using for the following packages?

Angular: 13.x
Angular CDK: 13.x
Angular CLI: 13.x
Typescript:4.5.5
Gallery: 6.0.1

**Comment by MurhafSousli** [comment]
Currently you can achieve that using a custom template https://github.com/MurhafSousli/ngx-gallery/wiki/Advanced-Usage

**Comment by nfMalde** [comment]
Thanks....that wil l work...thought this will override the whole display template of the image.
