### ISSUE TITLE
Swipe doesn't work with videos in the gallery

### ISSUE THREAD

**Issue by Sourav-Agarwalla** [MurhafSousli/ngx-gallery#439]
#### What is the expected behavior?
Expected behavior would be - it must swipe left or right same as it works for images.

#### What is the current behavior?
It's not swiping at all. Neither navigation button works.

#### What are the steps to reproduce?
https://stackblitz.com/edit/ngx-gallery-mcyvwt?file=src%2Fapp%2Fhome%2Fhome.component.ts
Will be able to reproduce in this sand-box on mobile resolution.

#### What is the use-case or motivation for changing an existing behavior?
It will make this library more stable on certain use case where we will be using videos in the gallery.

#### Which versions are you using for the following packages?

Angular: 12.2.8
Angular CDK: 12.2.8
Angular CLI: 12.1.1
Typescript: 4.2.3
Gallery: 5.0.0

#### Is there anything else we should know?
It's the scenario when I'm in mobile resolution and I'm not using thumbnails and navigation while being in this resolution, completely relied on gestures(swiping).

**Comment by MurhafSousli** [comment]
The Youtube video is different than the image, its `iframe` position is set to absolute so it blocks the layer that receives the swipe event, maybe it can be fixed by modifying the CSS but then it will block the interaction with the youtube player and you won't be able to play it.
