### ISSUE TITLE
Fails to load images from Cloudinary

### ISSUE THREAD

**Issue by sdroniv** [MurhafSousli/ngx-gallery#441]
So i have a component that gets a data from server throgh the service, and inside that data there are array of image links to Cloudinary. When I'm trying to map that array to ImageItem[] -> image gallery fails to load images, request url is https://localhost:44462/[object%20Object]. When i'm trying to hardcode that links [
      new ImageItem({
        src: 'photo.jpg',
        thumb:
          'photo.jpg',
      }),
    ]; everythink works good. What can it be?

**Comment by MurhafSousli** [comment]
You have to fill the template issue properly and add a reproduction stackblitz, otherwise, I am unable to look into your issue!
