### ISSUE TITLE
Showing images only for authorized users

### ISSUE THREAD

**Issue by MaticDiba** [MurhafSousli/ngx-gallery#442]
#### What is the expected behavior?
Some images are only available to authorized users. Using the JWT token, the backend decides whether the image is allowed to a specific user or not. 

#### What is the current behavior?
Currently, there is no way to pass JWT to the backend.

#### What is the use-case or motivation for changing an existing behavior?
I would like to have a way of passing JWT to GET requests when requesting an image from the backend.

**Comment by MurhafSousli** [comment]
This is outside the scope of this project!
