### ISSUE TITLE
You should be able to copy the image by right-clicking

### ISSUE THREAD

**Issue by GitHubish** [MurhafSousli/ngx-gallery#445]
#### What is the expected behavior?

It is difficult for a user to retrieve the image scrolling in the gallery. It would be great to be able to right-click on the image and use the "copy image" function in the native context menu. Why not also propose an option to add a button to download it, a bit like looking at the photos on Google Photos we have the possibility to do actions like downloading it.

#### What is the current behavior?

Currently this is not possible since images are inserted through the background-image property.

**Comment by vpetrusevici** [comment]
I also think so.
@MurhafSousli I can try to implement it after #452 PR

**Comment by vpetrusevici** [comment]
I think also should be a possibility to use srcset with [lazy loading attribute](https://www.w3schools.com/tags/att_img_loading.asp#:~:text=The%20loading%20attribute%20specifies%20whether,are%20positioned%20below%20the%20fold.)

**Comment by MurhafSousli** [comment]
@vpetrusevici Sure!

**Comment by MurhafSousli** [comment]
In v7.0.3, we now use img element instead of div with background-image, however, I am afraid that this will not be fixed because if we allowed img to be on the top, dragging will stop working.

**Comment by GitHubish** [comment]
@MurhafSousli I understand indeed. Maybe then the solution would be not to use an extra div to capture drag events but rather to use the parent `gallery-item` and `pointer-events: none;` on `gallery-image` ?

**Comment by vpetrusevici** [comment]
I think we could use here build-in directive also https://angular.io/api/common/NgOptimizedImage
