### ISSUE TITLE
Using gallery.set(index) adds another extra item if index is last item in array

### ISSUE THREAD

**Issue by yumi-aiassets** [MurhafSousli/ngx-gallery#446]
When using gallery.set(index) I noticed that if index is the last index in the array, then the component pushes an extra item to the array. This doesn't last though. Once you've clicked past the extra item, it is removed from the images array.

**Comment by MurhafSousli** [comment]
I didn't understand can you reproduce the issue in a stackblitz?

**Comment by yumi-aiassets** [comment]
https://stackblitz.com/edit/ngx-gallery-phc8vw?file=src/app/home/home.component.html

**Comment by MurhafSousli** [comment]
I don't see any issue in the reproduction, the index looks to be set correctly!

> the component pushes an extra item to the array

I didn't see an extra item pushed!

**Comment by MurhafSousli** [comment]
Ok, now I got it, the user is able to slide to a nonexisting slide at first.

**Comment by MurhafSousli** [comment]
Ok, after investigation, it appears to be NOT a bug.

The issue you have is that you were setting the active slide before the gallery is even displayed! Moving your code into `ngAfterViewInit` works fine! [Working stackblitz ](https://stackblitz.com/edit/ngx-gallery-pshmvh?file=src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.ts)

**Comment by yumi-aiassets** [comment]
Thanks for your help! @MurhafSousli

**Comment by yumi-aiassets** [comment]
Thanks for your help! @MurhafSousli
