### ISSUE TITLE
Settings change shouldn't require restart

### ISSUE THREAD

**Issue by TheDelta** [MurhafSousli/ngx-gallery#466]
#### What is the expected behavior?

When I change a setting (config) I shouldn't be forced to restart the gallery.
For example gestures support should be enabled/disabled dynamically

#### What is the current behavior?

If i want to disable gestures support temporarily, I must "restart" (reinint) the component.

#### What are the steps to reproduce?

This can be clearly seen in the lab component, where restart() is called for certain options.

#### What is the use-case or motivation for changing an existing behavior?

I'm implementing pan/zoom for the image and would like to temporarily disable the slide pan.
Also in general, it would be great if the library could react dynamically to config changes.

#### Which versions are you using for the following packages?

latest

#### Is there anything else we should know?

(I'm gathering features & improvements - if I find enough time I'll submit merge requests <3)

**Comment by MurhafSousli** [comment]
This only applies to gestures as far as I know, didn't think of a use case to make it dynamic before!

**Comment by TheDelta** [comment]
Yeah my usecase is rather special and eventually obsolete with a new version of ng-gallery, but atm I implemented pan / zoom of imgages myself (looks like latest dev branch has this now implemented as well) and therefore I must temp disable hammerjs.

According to labs component, "Thumbnails mode", "Autoplay" and "Gestures" require a restart.
Eventually also chaning dynamically from vertical to horizontal slide, because hammerjs is only init once with the direction.
