### ISSUE TITLE
Setting gestures: false breaks ngx-gallery

### ISSUE THREAD

**Issue by TheDelta** [MurhafSousli/ngx-gallery#467]
#### What is the expected behavior?

If I disable gestures, it should still work as expected

#### What is the current behavior?

When I disable gestures, all images are shown in one slide

#### What are the steps to reproduce?

https://ngx-gallery.netlify.app/#/lab -> uncheck Enable gestures

#### What is the use-case or motivation for changing an existing behavior?

No gestures

#### Which versions are you using for the following packages?

latest -> https://ngx-gallery.netlify.app/#/lab

#### Is there anything else we should know?

Some required styles are not applied

**Comment by MurhafSousli** [comment]
related to #464 , you can use version 6 for now until we fix it
