### ISSUE TITLE
Images not taking full height, thumbnails not showing

### ISSUE THREAD

**Issue by sandrumirceaioan** [MurhafSousli/ngx-gallery#469]
I am trying now for 3 days and still not able to show the gallery as in your demos. 

I have tried everything. Literally tried EVERYTHING (even new project only with this module, so no styles, not other stuff that could interfere with ng-gallery). Should I also change my PC ... ???

Images will just now show as in your demod, they are strethed to modal height, and with no thumbnails.

cover:
![image](https://user-images.githubusercontent.com/18594144/193456309-8dc3132c-9a7e-4d95-b5de-2675a830d36f.png)

contain:
![image](https://user-images.githubusercontent.com/18594144/193456265-a28aa4fd-02e7-4526-808f-82810aa85ad0.png)

no errors, no anything... documentation is useless as it is, you can't really know what are you installing when following the guides.

**Comment by MurhafSousli** [comment]
related to #464 and #467
