### ISSUE TITLE
Images not shown, when number of images get larger

### ISSUE THREAD

**Issue by soenkekueper** [MurhafSousli/ngx-gallery#484]
#### What is the expected behavior?
Even when the number of items is large, the images are displayed correctly.

#### What is the current behavior?
When the number of images gets larger, the images are not displayed any more.
When the window size gets below a certain point, they get shown again.
On my smartphone and regular desktop pc / laptop the default resolution will cause no images to be shown.

#### What are the steps to reproduce?
I've checked out the git repo and changed the image count within the ngx-gallery-app pixabay.service.ts to return 180 images instead of 18. See screenshots:

<img width="836" alt="gallery" src="https://user-images.githubusercontent.com/24605357/194751562-bb139a2e-7bb6-455d-9bf7-80fda0cc8bdb.PNG">
<img width="504" alt="gallery small" src="https://user-images.githubusercontent.com/24605357/194751563-5ffabb99-d3f9-4ddd-9a83-907de9b904a8.PNG">

See also the forked StackBlitz example:
https://ngx-gallery-grumsj.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
It's not a change of behavior, just a bugfix.

#### Which versions are you using for the following packages?

Angular: 14.2.4
Angular CDK: 14.2.4
Angular CLI: 
Typescript: 4.7.4
Gallery:  Latest git-checkout

#### Is there anything else we should know?
no

**Comment by MurhafSousli** [comment]
Yes, it is mentioned in a note that the current version handles around 30 images max, https://github.com/MurhafSousli/ngx-gallery/wiki#note due to the browser element maximum value. This will be fixed with the new major version since it will be using virtual scroll mechanism

**Comment by soenkekueper** [comment]
Hey,
thanks for your reply, i have missed that note, sorry for that.

Do you have any idea when the next major release will be available or do you have a simplem work around i could use?

**Comment by MurhafSousli** [comment]
Unfortunately, I don't know! I am currently working on the documentation but there is still a bug on mobile.. I will see if I can release a beta version soon.

**Comment by MurhafSousli** [comment]
This should be fixed in v8.0.0-beta.0

Install it `npm i ng-gallery@beta` and `npm i bezier-easing`

Could you try it and give me your feedback?

**Comment by soenkekueper** [comment]
Hey,
i've just updated my app and it works great.
All images are now shown.

Thanks for your great and fast work!
