### ISSUE TITLE
Allow Components in addition to TemplateRef

### ISSUE THREAD

**Issue by TheDelta** [MurhafSousli/ngx-gallery#486]
#### What is the expected behavior?

I would like to use a Component for `thumbTempalte` and `itemTemplate`.

#### What is the current behavior?

Currently I must use a TemplateRef.
My workaround is to wrap my component in a `ng-template`, get the ref to it and inject it via a custom service.

#### What are the steps to reproduce?

N/A

#### What is the use-case or motivation for changing an existing behavior?

I prefer to use a component instead, to reduce complexity and reuse it.

#### Which versions are you using for the following packages?

Angular: 14.2
Angular CDK: 14.2
Angular CLI: 14.2
Typescript: 4.7
Gallery: 7.1.2

#### Is there anything else we should know?

I would be willing to work on a Pull Request if this is wanted, but not important at the moment.

**Comment by MurhafSousli** [comment]
Yes, you must use your custom component inside the `TemplateRef`, I don't understand why you need to inject a custom service! can  you add a reproduction?

**Comment by TheDelta** [comment]
Here is an example https://ngx-gallery-aj9ovh.stackblitz.io

I would like to directly set the component in the config, rather doing the template workaround.
Probably via CdkPortal.

**Comment by MurhafSousli** [comment]
> Here is an example https://ngx-gallery-aj9ovh.stackblitz.io
> 
> I would like to directly set the component in the config, rather doing the template workaround. Probably via CdkPortal.

Why do you give me a stackblitz that does not show the code!

I didn't get it, can you show an example how is using the `ng-template`  harder than the way you want? isn't the `ng-template` way easy enough?

```html
<ng-template>
  <my-component></my-component>
</ng-template>
```

**Comment by TheDelta** [comment]
ah damn, my bad. It was early in the morning. I updated with the link to the editor.

I use the lightbox for examply dynamically on images and other components.
Now I could define one main component which is loaded with app.component and define there many ng-templates with various item templates. But I rather prefer to use a component approach and split everything into each file.

So using ng-template is not harder, it's just bloating up a component and I would like to create tiny components which I just can give to the lightbox config and it's ready to use. Right now I must create a component wrapped within ng-template and do a workaround. A solution would be to use CdkPortal, which seems to make this fairly easy.

Currently I use the workaround successful.

**Comment by MurhafSousli** [comment]
In the current version 7 and 8, I won't make a change, because in v9 everything will change as seen in the [MD file](https://github.com/MurhafSousli/ngx-gallery/blob/dev/projects/carousel-demo/src/assets/docs/carousel.md)!

The template will be even more bloated in v9, but for good reason! it will be very flexible to customize your gallery and will remove the main reference service, therefore, so its better to get it incapsulated in its own component and then reused in the pages
