### ISSUE TITLE
Image 1x 2x 3x support for retina display (webp, jpeg)

### ISSUE THREAD

**Issue by matte0080** [MurhafSousli/ngx-gallery#498]
Hi mate,

thank you for you great works. I have a question for you?

Is possible utilize webp format with 3x, 2x, 1x support and with fallback. Example:

```
<picture>
    <source srcset="/2a65f4a2-72e8-4cd7-95e8-d01b0cd2729a/thumbnail@1.webp 1x, /2a65f4a2-72e8-4cd7-95e8-d01b0cd2729a/thumbnail@2.webp 2x, /2a65f4a2-72e8-4cd7-95e8-d01b0cd2729a/thumbnail@3.webp 3x " type="image/webp">
    <img src="/2a65f4a2-72e8-4cd7-95e8-d01b0cd2729a/original.jpg">
</picture>
```

Is possible create a custom template inside gallery with the picture element. Picture element can support 1x 2x 3x (retina display). with fallback for old browser and devices.
Thank you.

**Comment by MurhafSousli** [comment]
Yes, you can use custom template, see the docs here https://github.com/MurhafSousli/ngx-gallery/wiki/Advanced-Usage
