### ISSUE TITLE
Error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments

### ISSUE THREAD

**Issue by DywiTom** [MurhafSousli/ngx-gallery#505]
#### What is the expected behavior?
No errors with "ng serve"

#### What is the current behavior?

```
Error: node_modules/ng-gallery/lib/components/gallery-core.component.d.ts:38:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

38     static ɵcmp: i0.ɵɵComponentDeclaration<GalleryCoreComponent, "gallery-core", never, { "galleryId": "galleryId"; "state": "state"; "config": "config"; }, { "itemClick": "itemClick"; "thumbClick": "thumbClick"; "error": "error"; }, never, never, false, never>;
```

#### Which versions are you using for the following packages?

Angular: 14.2.7
Angular CDK: 14.2.7
Angular CLI: 14.2.7
Typescript: 4..6.4
Gallery: 8.0

**Comment by MurhafSousli** [comment]
ng-gallery@8.0 built with Angular CDK 15, it could be the CDK version mismatch. could you try upgrading your project to 15? if that works, I then have to update the Angular peerDependencies version !

**Comment by DywiTom** [comment]
Thank you for your fast response.
I can't upgrade right now, so i will check that later.

**Comment by DavidIQ** [comment]
Ran into this same issue. Can't upgrade the project to Angular 15 yet and just installing the Angular CDK 15 wasn't enough. Have to stick to version 8 for the time being.
