### ISSUE TITLE
Simple video Url does not work

### ISSUE THREAD

**Issue by cmb0335** [MurhafSousli/ngx-gallery#514]
I am trying to setup a gallery with one video url item and it will not display. I have used the example code and cannot get anything to show up.

Stackblitz: https://ngx-gallery-yg4zwc.stackblitz.io

Code:
<gallery id="mixedExample"></gallery>

import { Component, ChangeDetectionStrategy, OnInit } from '@angular/core';
import { Gallery, GalleryItem, GalleryRef } from 'ng-gallery';
import { Lightbox } from 'ng-gallery/lightbox';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomeComponent implements OnInit {
  constructor(public gallery: Gallery, public lightbox: Lightbox) {}

  ngOnInit() {
    const galleryRef: GalleryRef = this.gallery.ref('mixedExample');
    galleryRef.addVideo({
      src: 'http://www.w3schools.com/html/mov_bbb.mp4',
      type: 'video/mp4',
    });
  }
}

**Comment by molnarm** [comment]
Your stackblitz doesn't load for me, but I just had a similar issue. You aren't setting `control` or `poster` for the video item, so nothing is visible and you cannot start the video.

**Comment by cmb0335** [comment]
I added controls: true and poster as the same url as the video and it still didn't work.

ngOnInit() {
    const galleryRef: GalleryRef = this.gallery.ref('mixedExample');
    galleryRef.addVideo({
      src: 'http://www.w3schools.com/html/mov_bbb.mp4',
      thumb: 'http://www.w3schools.com/html/mov_bbb.mp4',
      poster: 'http://www.w3schools.com/html/mov_bbb.mp4',
      controls: true,
      type: 'video/mp4',
    });
  }

Here is the corrected stackblitz URL:
https://stackblitz.com/edit/ngx-gallery-8ykqq6?file=src/app/home/home.component.ts

**Comment by MurhafSousli** [comment]
@cmb0335 This is because w3schools.com does NOT want you to play the video outside their website domain.

**Comment by molnarm** [comment]
No, that's wrong, he has the same issue as I reported in #515 -  note that the `type` that is set in his code is not the type of the video but the type discriminator field of `GalleryItem`. If you change `src` to contain the url and its type, it loads the video.

@cmb0335 it looks like we are going along the same path and running into the same problems while trying to use this component. For me, the next step was switching to another library ([Bigger Picture](https://github.com/henrygd/bigger-picture))...

**Comment by MurhafSousli** [comment]
Ok, I will take a deeper look soon

**Comment by MurhafSousli** [comment]
Will track this in #515, closing this a duplication.
