### ISSUE TITLE
Videos are unplayable if type not specified

### ISSUE THREAD

**Issue by molnarm** [MurhafSousli/ngx-gallery#515]
#### What is the expected behavior?
Video items where the type (video format) is not specified should be played correctly.

#### What is the current behavior?
The video is not recognized by the browser as playable.

#### What are the steps to reproduce?
Create a VideoItem with `src` set to either a simple string, or an array where one of the items has no `type` specified.

The rendered `video` tag will still always have `type="undefined"` on its source tag, so the browser is unable to play it. Same for using `null`. The only workaround I found is explicitly setting empty string as `type`, then the empty attribute is ignored by the browser.

StackBlitz: https://stackblitz.com/edit/ngx-gallery-fnassi?file=src/app/home/home.component.ts
Note how the only video to properly load and play is the third item.

#### Which versions are you using for the following packages?

Angular: 15.1.0
Angular CDK: 15.0.4
Angular CLI: 15.0.5
Typescript: 4.8.4
Gallery: 8.0.1

**Comment by MurhafSousli** [comment]
Fixed in v8.0.2
