### ISSUE TITLE
endless loading with one image in gallery

### ISSUE THREAD

**Issue by janosfarkas** [MurhafSousli/ngx-gallery#52]
```
- [x] bug report 
- [ ] feature request
- [ ] question
```

### OS and Version?
All (Windows 10, Windows 8.1, iOS 11.2.2, Android 8.0, Android 6.0.1 tested)

### Versions
Angular CLI: 1.6.3
Node: 8.9.0
Angular: 5.1.3

### Repro steps
If there is only 1 image in gallery and you swipe to the left or right control arrows disappear and starts endless loading.
![](https://i.imgur.com/ISRfv2X.png)

**Comment by MurhafSousli** [comment]
The arrows disappear on loading, but the photos are just too large!

**Comment by jgarciao** [comment]
I think I have the same problem when loading ng-gallery (1.0.1) with just one image:

- The image is loaded fine but when clicking on it results in loading animation.
- You can reproduce it here: https://beta.flathub.org/apps/details/org.gnome.gedit
- And here is the code using the component: https://github.com/jgarciao/linux-store-frontend/blob/master/src/app/shared/app-details-description/app-details-description.component.ts
- The screenshot size is about 86kB

Also I think when having only one image the left-right arrows could be hidden

Thank you for your awesome component!

Downstream bug: https://github.com/jgarciao/linux-store-frontend/issues/35

**Comment by MurhafSousli** [comment]
@janosfarkas can you reproduce the issue in https://stackblitz.com/edit/ng-gallery
What is the gallery state look like?
Add this to print it out
```ts
this.galley.state$.subscribe(res => console.log(res))
```

**Comment by janosfarkas** [comment]
in app.component.html just remove 3 out of 4 images, click on the remaining one, and then push left/right arrow.
gallery state looks like this:
`Object { action: "next", currIndex: 0, hasNext: false, hasPrev: false, play: false, loading: true, items: Array[1] }`

**Comment by MurhafSousli** [comment]
@janosfarkas fork the [stackblitz](https://stackblitz.com/edit/ng-gallery), make the change and give me the new link so I can see it

**Comment by janosfarkas** [comment]
https://ng-gallery-m2mmbf.stackblitz.io

**Comment by MurhafSousli** [comment]
@janosfarkas it is working! I don't see any issue

**Comment by janosfarkas** [comment]
@MurhafSousli https://youtu.be/pTCjyKhLP2c so this is how it should work?

**Comment by jgarciao** [comment]
Same issue as https://beta.flathub.org/apps/details/org.gnome.gedit

Clicking on the image when there is only one should do nothing or load it again

**Comment by jgarciao** [comment]
@janosfarkas I've made a workaround here https://github.com/jgarciao/linux-store-frontend/commit/ffc8ad951dff783e1d2c2febebe0d8ae7b6787d8

```
if(this.app.screenshots.length == 1){
        this.galleryConfig.loader = null;
        this.galleryConfig.navigation = null;
        this.galleryConfig.thumbnails = null;
      }
```

**Comment by maku** [comment]
@MurhafSousli i stumbled over this error -> when only 1 picture is available  there should no navigation capabilities
(currently behaviour when you click on the next button the loading symbol occurs on a blank screen and nothing happens)
How can I handle this? (the workaround to change the gallery config dynamically is a little ugly)
