### ISSUE TITLE
Simple Youtube Url does not work

### ISSUE THREAD

**Issue by cmb0335** [MurhafSousli/ngx-gallery#520]
#### What is the expected behavior?
Video shows up and plays correctly in the gallery

#### What is the current behavior?
Video displays an error

#### What are the steps to reproduce?
https://stackblitz.com/edit/ngx-gallery-p8but8?file=src/app/home/home.component.ts

Gallery: 8.0.2

**Comment by MurhafSousli** [comment]
Use the youtube ID as mentioned [in the docs](https://github.com/MurhafSousli/ngx-gallery/wiki/Advanced-Usage), not the URL!

Fixed stackblitz https://stackblitz.com/edit/ngx-gallery-buwqcy?file=src%2Fapp%2Fhome%2Fhome.component.ts
