### ISSUE TITLE
Warning: ng-gallery.mjs depends on 'bezier-easing'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by DywiTom** [MurhafSousli/ngx-gallery#525]
#### What is the expected behavior?

No Warning

#### What is the current behavior?

I got while compiling the following warning:

`Warning: C:\...\node_modules\ng-gallery\fesm2020\ng-gallery.mjs depends on 'bezier-easing'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

#### What are the steps to reproduce?

`ng serve`

#### Which versions are you using for the following packages?

Angular: 15.1.6
Angular CDK: 15.1.4
Angular CLI: 15.1.6
Typescript: 4.9.5
Gallery:  8.0.2

#### Is there anything else we should know?

Thank you for your great work.

**Comment by MurhafSousli** [comment]
In your `angular.json` add `bezier-easing` to `allowedCommonJsDependencies` the following

https://github.com/MurhafSousli/ngx-gallery/blob/814a1fc93b859552db1d031c9e04f88f193f0412/angular.json#L61-L62

**Comment by DywiTom** [comment]
Thanks for your answer.
It's a workaround, not solving actually the 'problem'.

**Comment by MurhafSousli** [comment]
There is no problem with using a common.js dependency in Angular, it won't affect the performance of the app but I can include the easing function internally in the next releases
