### ISSUE TITLE
Gallerize with gallery shows index outside the items range when [autoplay]=true. 

### ISSUE THREAD

**Issue by vagarthgaurav** [MurhafSousli/ngx-gallery#528]
#### What is the expected behavior?

Gallerize directive on gallery should show lightbox with gallery. 

#### What is the current behavior?

When autoplay is set to true the gallerize feature does not seem to work with the following error:

> [NgGallery]: Unable to set the active item because the given index (0) is outside the items range!

When autoplay property is removed it works fine. 

#### What I have tried

**component.ts**

    ngOnInit(): void {
       this.wagtailService.getPageForCurrentUrl().subscribe((r: any) => {
        this.data = r;

      this.data.gallery_images.forEach((image) => {
        this.images.push(new ImageItem({ src: image.image_url, thumb: image.image_url }));
      });
    });
  }

**component.html**

    <gallery
    style="height: 60vh; width: 100%"
    [items]="images"
    [itemAutosize]="true"
    imageSize="contain"
    [autoPlay]="true" 
    [dots]="true"
    [counter]="false"
    [thumb]="false"
    gallerize
    ></gallery>

#### Which versions are you using for the following packages?

Angular: 15.2.1
Angular CDK: 15.2.1
Angular CLI: 15.2.1
Typescript: 4.8.0
Gallery: 8.0.2

**Comment by vagarthgaurav** [comment]
Unable to reproduce anymore.

**Comment by beyondsanity** [comment]
Hello, sorry to comment on a closed thread but I find myself in the same situation.
I created a Stackblitz that reproduce the issue: https://stackblitz.com/edit/stackblitz-starters-pri6tj?file=src%2Fapp%2Fapp.component.ts

**Comment by MurhafSousli** [comment]
@beyondsanity it appears that the issue is when using `[autoPlay]="true"`

**Comment by beyondsanity** [comment]
> @beyondsanity it appears that the issue only occurs when using `[autoPlay]="true"` https://stackblitz.com/edit/stackblitz-starters-4yb2gc?file=src%2Fglobal_styles.css,src%2Fapp%2Fapp.component.ts

Yes, I confirm this behavior on both my code and the stackblitz project.
I tried to introduce some delays and changing the other plugin configurations but I didn't find any workaround

**Comment by beyondsanity** [comment]
@MurhafSousli the problem could to be related to some timing issues during initialization. In the same project I also have other anomalies, like an incorrect width in case the gallery in put inside a dynamic width container.

I was able to workaround the issues by adding a small delay:
https://stackblitz.com/edit/stackblitz-starters-zu42jk?file=src%2Fapp%2Fapp.component.ts

**Comment by MurhafSousli** [comment]
Yea, I have to look into it

**Comment by MurhafSousli** [comment]
@beyondsanity can you try it out with v12? get it with `npm i ng-gallery@beta`
