### ISSUE TITLE
Videos do not work / wrong type for VideoItem in docs

### ISSUE THREAD

**Issue by DauntedPine** [MurhafSousli/ngx-gallery#529]
Using 

`src = { url : string, type: string }` will give an error: 

```
Type '{ url: string; type: string; }' is not assignable to type 'string | (string & { url: string; type: string; })'.
  Type '{ url: string; type: string; }' is not assignable to type 'string & { url: string; type: string; }'.
    Type '{ url: string; type: string; }' is not assignable to type 'string'.(2322)
```

https://stackblitz.com/edit/angular-twfplh?file=src%2Fmain.ts

**Comment by alexandruantochi** [comment]
Looks like the type does not get added in the video tag.

**Comment by alexandruantochi** [comment]
Also a small sidenote, not having `controls : true` or `autoplay: true` will make the video unplayeble. Their default values are undefined.

**Comment by MurhafSousli** [comment]
Add `src: [{ url: this.videoLink, type: 'video/mp4' }] as any`
