### ISSUE TITLE
The demo app generates wrong config

### ISSUE THREAD

**Issue by DenisSeko** [MurhafSousli/ngx-gallery#53]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] question
```
One quicke question, I implemented demo step by step and from module I'm getting error
error TS2304: Cannot find name 'GalleryConfig'

### OS and Version?

windows 10
### Versions

Angular CLI: 1.5.0
Node: 6.11.2
OS: win32 x64
Angular: 5.0.5
... core

@angular/animations: 5.0.1
@angular/cdk: 5.0.4
@angular/cli: 1.5.0
@angular/common: 5.0.1
@angular/compiler-cli: 5.0.1
@angular/compiler: 5.0.1
@angular/forms: 5.0.1
@angular/http: 5.0.1
@angular/language-service: 5.0.0
@angular/platform-browser-dynamic: 5.0.1
@angular/platform-browser: 5.0.1
@angular/router: 5.0.1
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1

**Comment by MurhafSousli** [comment]
I think I forgot to add it to the docs
```ts
import { GalleryModule, GalleryConfig } from 'ng-gallery';
```

**Comment by DenisSeko** [comment]
well, I passed some config from online generator and now I am getting also strange error, but I it works when config is empty "export config : GalleryConfig = {} " mybe I am missing something? I tryed the same as you suggested

 export const config : GalleryConfig = {
  "gestures": true,
  "style": {
    "width": "100%",
    "height": "100%",
    "background": "#121519"
  },
  "navigation": null,
  "loader": null,
  "description": {
    "position": "bottom",
    "overlay": false,
    "text": true,
    "counter": false,
    "style": {
      "backgroundColor": "rgba(0, 0, 0, 0.8)"
    }
  },
  "player": {
    "autoplay": true,
    "interval": 3000,
    "progress": false,
    "position": "bottom"
  },
  "thumbnails": {
    "width": 120,
    "height": 90,
    "position": "bottom",
    "margin": 20
  },
  "lightbox": {
    "backdropClass": "g-backdrop",
    "panelClass": "g-overlay",
    "hasBackdrop": true
  },
  "imageSize": "contain",
  "bullets": false,
  "className": "fluid"
}

ERROR in src/app/app.module.ts(51,5): error TS2322: Type '{ "gestures": true; "style": { "width": string; "height": string; "background": string; }; "navig...' is not assignable to type 'GalleryConfig'.
  Types of property 'thumbnails' are incompatible.
    Type '{ "width": number; "height": number; "position": string; "margin": number; }' is not assignable to type 'GalleryThumbConfig'.
      Object literal may only specify known properties, and '"margin"' does not exist in type 'GalleryThumbCon

**Comment by MurhafSousli** [comment]
Remove the margin property from the thumbnail, the current generator has this bug

**Comment by DenisSeko** [comment]
After I remove margin property from thumbnail, it seems there are more bugs
{
  "gestures": true,
  "style": {
    "width": "900px",
    "height": "500px",
    "background": "#121519"
  },
  "navigation": {},
  "loader": {
    "icon": "data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='135' height='140' fill='%23fff'%3E%3Crect width='15' height='120' y='10' rx='6'%3E%3Canimate attributeName='height' begin='0.5s' dur='1s' values='120;110;100;90;80;70;60;50;40;140;120' calcMode='linear' repeatCount='indefinite'/%3E%3Canimate attributeName='y' begin='0.5s' dur='1s' values='10;15;20;25;30;35;40;45;50;0;10' calcMode='linear' repeatCount='indefinite'/%3E%3C/rect%3E%3Crect width='15' height='120' x='30' y='10' rx='6'%3E%3Canimate attributeName='height' begin='0.25s' dur='1s' values='120;110;100;90;80;70;60;50;40;140;120' calcMode='linear' repeatCount='indefinite'/%3E%3Canimate attributeName='y' begin='0.25s' dur='1s' values='10;15;20;25;30;35;40;45;50;0;10' calcMode='linear' repeatCount='indefinite'/%3E%3C/rect%3E%3Crect width='15' height='140' x='60' rx='6'%3E%3Canimate attributeName='height' begin='0s' dur='1s' values='120;110;100;90;80;70;60;50;40;140;120' calcMode='linear' repeatCount='indefinite'/%3E%3Canimate attributeName='y' begin='0s' dur='1s' values='10;15;20;25;30;35;40;45;50;0;10' calcMode='linear' repeatCount='indefinite'/%3E%3C/rect%3E%3Crect width='15' height='120' x='90' y='10' rx='6'%3E%3Canimate attributeName='height' begin='0.25s' dur='1s' values='120;110;100;90;80;70;60;50;40;140;120' calcMode='linear' repeatCount='indefinite'/%3E%3Canimate attributeName='y' begin='0.25s' dur='1s' values='10;15;20;25;30;35;40;45;50;0;10' calcMode='linear' repeatCount='indefinite'/%3E%3C/rect%3E%3Crect width='15' height='120' x='120' y='10' rx='6'%3E%3Canimate attributeName='height' begin='0.5s' dur='1s' values='120;110;100;90;80;70;60;50;40;140;120' calcMode='linear' repeatCount='indefinite'/%3E%3Canimate attributeName='y' begin='0.5s' dur='1s' values='10;15;20;25;30;35;40;45;50;0;10' calcMode='linear' repeatCount='indefinite'/%3E%3C/rect%3E%3C/svg%3E"
  },
  "description": {
    "position": "bottom",
    "overlay": true,
    "text": true,
    "counter": true,
    "style": {
      "backgroundColor": "rgba(0 ,0 , 0, 0.8)",
      "textShadow": "0 0 2px rgba(0, 0, 0, 0.5)"
    }
  },
  "player": {
    "autoplay": false,
    "interval": 3000,
    "progress": false,
    "position": "bottom",
    "speed": 3000
  },
  "thumbnails": {
    "width": 100,
    "height": 80,
    "position": "top"
    
  },
  "lightbox": {
    "backdropClass": "g-backdrop",
    "panelClass": "g-overlay",
    "hasBackdrop": true
  },
  "imageSize": "contain",
  "bullets": false,
  "className": "fluid"
}

ERROR in src/app/app.module.ts(23,15): error TS2322: Type '{ "gestures": true; "style": {}; "navigation": {}; "loader": { "icon": string; }; "description": ...' is not assignable to type 'GalleryConfig'.
  Types of property 'bullets' are incompatible.
    Type 'boolean' is not assignable to type 'GalleryBulletConfig'.
