### ISSUE TITLE
error after instaling

### ISSUE THREAD

**Issue by Motidru** [MurhafSousli/ngx-gallery#530]
Error: node_modules/ng-gallery/lib/components/templates/gallery-image.component.d.ts:34:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

**Comment by BizTechoff** [comment]
Why u closed it?

**Comment by BizTechoff** [comment]
> Error: node_modules/ng-gallery/lib/components/templates/gallery-image.component.d.ts:34:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

Why u closed it?

**Comment by Motidru** [comment]
Why u closed it?

**Comment by MurhafSousli** [comment]
It doesn't follow the issue template!

**Comment by BizTechoff** [comment]
U rights!
long template 🤯

בתאריך יום ג׳, 14 במרץ 2023, 02:14, מאת Murhaf Sousli ‏<
***@***.***>:
