### ISSUE TITLE
Proper way to destroy/cleanup gallery and ImageItem[]

### ISSUE THREAD

**Issue by njsent** [MurhafSousli/ngx-gallery#536]
I am not sure if I am disposing/cleaning up properly because the ImageItems as well as HTMLImageElement keep increasing in memory even after garbage collection as if the gallery is retaining them after destroy is called.    Here is the essence of the code:

`
@Input() imageUrls: string[];

galleryRef: GalleryRef = this.gallery.ref(); images: ImageItem[];

constructor(private gallery: Gallery, private lightbox: Lightbox) { }

ngOnInit() {
   this.galleryRef.setConfig({
      imageSize: ImageSize.Contain
    });

    this.images = this.imageUrls.map((url) => new ImageItem({ src: url, thumb: url }));

    this.galleryRef.load(this.images);
    
    if (this.fullscreen)
      this.lightbox.setConfig({ panelClass: 'fullscreen' });
   
  }

ngOnDestroy() {
    if (this.images)
      this.images.length = 0;
    
    if (this.galleryRef) {
      this.galleryRef.reset();
      this.galleryRef.destroy();
      this.galleryRef = null;
    }
    
    if (this.gallery) {
      this.gallery.destroyAll();
      this.gallery = null;
    }
}
`

Angular: 14.2.12
Angular CDK: 14.2.7
Angular CLI: 14.2.10
Typescript: 4.7.2
Gallery:  8.0.0

![nggallery](https://user-images.githubusercontent.com/8079162/229740430-d105ec06-1dcc-4cce-bfb8-34d3d7244692.png)

**Comment by MurhafSousli** [comment]
The ImageItem is just a class 

Here is the code for the HTMLImageElement

**Comment by njsent** [comment]
Update: The issue had nothing to do with ng-gallery but instead a recaptcha component on the same page causing the component to remain in memory.  My apologies for opening the issue.

**Comment by MurhafSousli** [comment]
No worries thanks for the update!
