### ISSUE TITLE
RTL navigation going the opposite side

### ISSUE THREAD

**Issue by Harpush** [MurhafSousli/ngx-gallery#540]
#### What is the expected behavior?
Clicking on the left arrow goes to the next image and right to the previous image (as it's Right To Left).

#### What is the current behavior?
The thumb images flip to RTL mode and we can navigate the images but the left arrow is for previous (going right) and the right arrow is for next (going left)

#### What are the steps to reproduce?
Just add RTL to any example in the gallery site. Best shown in [here](https://ngx-gallery.netlify.app/#/gallerize) (`Use with <gallery> Component` section)

#### What is the use-case or motivation for changing an existing behavior?
Weird interaction with RTL mode

#### Which versions are you using for the following packages?
Site versions - latest I guess?

#### Is there anything else we should know?

**Comment by Harpush** [comment]
@MurhafSousli isn't it a bug? 🤔

**Comment by MurhafSousli** [comment]
@Harpush It can be if the plugin mentioned that it supports RTL websites, so I think it is considered as a feature.

**Comment by Harpush** [comment]
> @Harpush It can be if the plugin mentioned that it supports RTL websites, so I think it is considered a feature.

I based on the issue #322 which is now closed as completed

**Comment by Harpush** [comment]
Any news concerning this?

**Comment by MurhafSousli** [comment]
As a workaround, you need to set `dir="ltr"` on the gallery in your RTL website, or in the global CSS

```css
gallery {
  direction: ltr;
} 
```
