### ISSUE TITLE
ItemAutosize in website/safari browsers do not work as expected. 

### ISSUE THREAD

**Issue by vagarthgaurav** [MurhafSousli/ngx-gallery#543]
#### What is the expected behavior?
The gallery to show images in carousel without any space between images i.e., each item takes the width of the image while using itemAutosize in all browser.

#### What is the current behavior?
On chorme and firefox itemAutosize behaves as expected. In Webkit/safari browsers the behaviour is different. The images do not appear next to each other. The items are not sized to the image widths. 

#### What are the steps to reproduce?

View in safari browser on mac or epiphany browser in linux. 

https://stackblitz.com/edit/angular-xm877d?file=src/app/news-page/news-page.component.html

https://angular-xm877d.stackblitz.io/

#### Which versions are you using for the following packages?

Angular: 15.2.1
Angular CDK: 15.2.1
Angular CLI: 15.2.1
Typescript: 4.8.0
Gallery: 8.0.2

**Comment by malte-behrendt-gr** [comment]
This different behavior is also visible on https://ngx-gallery.netlify.app/#/lab when playing around with "item autosize", image size "cover", ...
