### ISSUE TITLE
stateSnapshot - where is it?

### ISSUE THREAD

**Issue by adventmedia** [MurhafSousli/ngx-gallery#554]
#### What is the expected behavior?
galleryRef instance should include `stateSnapshot` as per API docs

#### What is the current behavior?
`stateSnapshot` does not exist

#### What is the use-case or motivation for changing an existing behavior?
need to access current state of gallery (specifically, what slide i.e. index are you on?) 

#### Which versions are you using for the following packages?

Angular: 16.0.1
Angular CDK: 16.0.1
Angular CLI: 16.0.1
Typescript: 5.0.4
Gallery: 9.0.0

**Comment by MurhafSousli** [comment]
Are you sure you're using the right package?

![image](https://github.com/MurhafSousli/ngx-gallery/assets/8130692/f5456944-f086-45a4-869c-457891f02a49)
