### ISSUE TITLE
Multiple galleries on the same page

### ISSUE THREAD

**Issue by adrienlamotte** [MurhafSousli/ngx-gallery#56]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

Hello ! 
Is there a way to have multiple galleries on the same page ?

Thank you for you work !

**Comment by MurhafSousli** [comment]
@adrienlamotte Yes, that's on my radar

**Comment by riheldo** [comment]
Hi, im trying show multiple galleries on the same page. But the images displaying in all galleries are the images from the last.
The goal is make a list divided in months, that show the images from that month.

Sample of code:
```html
<div class="fdk-album" *ngFor="let album of albums;">
    <h2>{{ album.month }}</h2>
    <p>{{ album.description }}</p>
    <gallery [items]="album.imgs"></gallery>
</div>
```

Is that possible?

**Comment by MurhafSousli** [comment]
@riheldo just give each gallery an id
