### ISSUE TITLE
Mov format

### ISSUE THREAD

**Issue by CarlosAmorimProjects** [MurhafSousli/ngx-gallery#562]
Hello, Murhaf.

Thank you for this project.

Does it have compatibilty with .mov files ?

I have tried it, it plays sound but no image...

Regards.

**Comment by MurhafSousli** [comment]
Yes, the HTML video player supports MOV format, if you have an issue add a reproduction stacklbitz

**Comment by CarlosAmorimProjects** [comment]
Thank you for getting back to me.

**Comment by CarlosAmorimProjects** [comment]
I'm trying to create the stackblitz, but it seems it's not compiling, it's only for me ou is stackblitz issue ?

https://stackblitz.com/edit/ngx-gallery

**Comment by MurhafSousli** [comment]
The stackblitz works fine!

**Comment by CarlosAmorimProjects** [comment]
I can't get it to work on Chrome, I had to do it on Edge :

https://stackblitz.com/edit/ngx-gallery-6tbryk?file=src%2Fmain.ts,src%2Fmain.html

Here you go, the video does play sound but it doesn't show video...

**Comment by MurhafSousli** [comment]
Its your MOV file, here a working MOV file: https://stackblitz.com/edit/ngx-gallery-whduxt?file=src%2Fmain.ts,src%2Fmain.html

**Comment by CarlosAmorimProjects** [comment]
Thank you for the help.
