### ISSUE TITLE
differentiate beetween navigation and simple click on an image

### ISSUE THREAD

**Issue by maku** [MurhafSousli/ngx-gallery#57]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] question
```

### Desired functionality
Currently a click on an image indicates a navigation request. I would like to differentiate beetween navigation and click. (means only a click on navigation icons do navigation)
e.g. I would like execute "custom logic" on a click (e.g. open a new window with a certain URL etc.)

How can this be achieved?

**Comment by MurhafSousli** [comment]
@maku In version 2, you can make your own custom component check https://murhafsousli.github.io/ngx-gallery/#/advanced

**Comment by maku** [comment]
@MurhafSousli thank you for your work on ngx-gallery v2.

But I don't get it what you mean:
From my (naive) point of view it should be enough to stop event propagation when a click on a navigation button occurs (event.stopPropagation()). Then it would be possible to add a simple click listener on the gallery component, right? (I only want to open an external page when the user clicks on an image)

The mentioned example (https://murhafsousli.github.io/ngx-gallery/#/advanced) is great but for other use cases (as far as I understand)

**Comment by MurhafSousli** [comment]
@maku Thanks!
For that, you need to make a custom image template
```ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { GalleryItemComponent } from '@ngx-gallery/core';

@Component({
  selector: 'custom-image-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  preserveWhitespaces: false,
  template: `
    <div [lazyImage]="data?.src" (loading)="loading = $event"></div>
    <i class="g-loading" *ngIf="loading"></i>
  `,
  styles: [`
    :host {
      position: relative;
      display: block;
      width: 100%;
      height: 100%;
    }
    div {
      background-position: center center;
      background-size: cover;
      width: 100%;
      height: 100%;
    }
  `],
})
export class CustomImageItemComponent implements GalleryItemComponent {
  loading: boolean;
  @Input() data: any;
  @HostListener('click', ['$event']) onClick(btn) {
     // do something
  }
}
```

in parent module, add it to `declarations` and `entryComponents`

```ts
@NgModule({
  imports: [
    // ...
  ],
  declarations: [
   // ...
    CustomImageItemComponent,
  ],
  entryComponents: [
    CustomImageItemComponent
  ]
})
export class ParentModule { }
```

Create `CustomImageItem` class to ease the creation of your custom gallery item

```ts
import { GalleryItem } from '@ngx-gallery/core';

export class CustomImageItem implements GalleryItem {
  public component = CustomImageItemComponent;  // <= here is your custom template
  public thumbComponent = ThumbnailItemComponent;  // <= you can also do the same for the thumbnails
  public data: any;

  constructor(src: string, thumb?: string) {
    this.data = {
      src: src,
      thumbSrc: thumb
    };
  }
}
```

Now in your parent component, you can use it like

```ts
@Component({
  template: `<gallery [items]="images"></gallery>`
})
export class ParentComponent implements OnInit {
  images: GalleryItem[];

  ngOnInit() {
    this.images = [
      new CustomImageItem('SRC_PATH', 'SRC_THUMB'),
      new CustomImageItem('SRC_PATH', 'SRC_THUMB'),
      new CustomImageItem('SRC_PATH', 'SRC_THUMB'),
       // ...
    ];
  }
```

**Comment by maku** [comment]
@MurhafSousli thanks for answering. 

But again do you think it would **not** be a good idea to **prevent** the event bubbling of the click event on the navigation 

e.g. in lib/core/src/components/gallery-nav.component.ts

```
<i *ngIf="config.loop || state.hasPrev" class="g-nav-prev" (click)="nextAction($event)"></i>

nextAction(event: Event) {
    event.stopPropagation();
    this.indexChange.emit('next');
  }
```

Then it would be possible to use existing behaviour and put a simple click event on the gallery component

**Comment by MurhafSousli** [comment]
Sorry I did not get it! what is the advantage of preventing the event bubbling? what is the current behavior? and what is the expected behavior?

**Comment by maku** [comment]
@MurhafSousli the current behaviour is:

**Comment by maku** [comment]
@MurhafSousli I don't want to be annoying but do you understand what I mean? I want only the click event when I DON'T click on the navigation button. (e.g. because I want to open an additional window in this case)... TIA

**Comment by MurhafSousli** [comment]
@maku I got it, I'm taking a look

**Comment by MurhafSousli** [comment]
@maku This is now possible in `2.0.0-beta.3` but HammerJS events do not support `stopPropagation()`, so for your case, you will need to disable the gestures to switch to the native click events.

**Comment by maku** [comment]
@MurhafSousli great thank you
