### ISSUE TITLE
Vertical virtual scroller causing flaky image index change without explicit invocation

### ISSUE THREAD

**Issue by maranmaran** [MurhafSousli/ngx-gallery#570]
#### What is the expected behavior?
Vertical scroll doesn't change item index

#### What is the current behavior?
Images jitter and jump index on vertical scroll

![image](https://github.com/MurhafSousli/ngx-gallery/assets/17520025/ad5d4086-9286-4edc-b3b5-3dbd9be89cb5)

Two days valid link: https://streamable.com/rguhly 

#### What are the steps to reproduce?
I have virtual scrolling grid.

When I go out of view with the gallery and in fast manner pull the vertical scroll back, sometimes (frequently) I get different item index as my first, and it kind of jumps between few photos.

#### Stackblitz
I'll post repro issue when I get the time.

#### Which versions are you using for the following packages?

Angular: 16
Gallery:  ^11.0.0

My setup code:

````
 ngOnDestroy() { this.ref.destroy() }

 private async setupGallery() {
    
    // this gets or creates the ref and adds images to it
    await this.addItemsToGallery(); 

    this.ref.set(0, 'instant'); // set 0 as index - (should see no jumping of images)
  }
````

The html is wrapped in virtual scroll component.
However, I don't think that should bother it.

My image data are always in consistent order
I'm forcing the index to be set as 0 but even so on init I see this jumping when I scroll or even refresh the page

**Comment by MurhafSousli** [comment]
I see, yes it is better to have a reproduction, there are couple of options we can try

**Comment by MurhafSousli** [comment]
Please try with the newer version 12 beta `npm i ng-gallery@beta`, closing this for now... feel free to reopen if you still encounter the issue
