### ISSUE TITLE
Youtube videos do not display when `[autoheight]="true"` is used

### ISSUE THREAD

**Issue by FiniteLooper** [MurhafSousli/ngx-gallery#574]
#### What is the expected behavior?
Youtube videos should display

#### What is the current behavior?
Youtube videos do not display at all when `[autoheight]="true"` is used. Just a blank space where the video would be.  Removing `autoheight` will make it display.

#### What are the steps to reproduce?
```ts
itemsArr= [
	new YoutubeItem({src: `1Ovcl3FYL3Y`}),
]
```
```html
<gallery [items]="itemsArr" [autoHeight]="true" />
```

[StackBlitz Demo](https://stackblitz.com/edit/finitelooper-ng16-ys4kxw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html)

#### What is the use-case or motivation for changing an existing behavior?
To make it work with videos

#### Which versions are you using for the following packages?

Angular: `16.2.1`
Angular CDK: `16.2.1`
Angular CLI: `16.2.0`
Typescript: `5.1.6`
Gallery: `11.0.0`

#### Is there anything else we should know?
There are exactly zero demos of video content being used.  The [wiki page for mixed content usage](https://github.com/MurhafSousli/ngx-gallery/wiki/Mixed-Content-Usage) makes mention of this feature in code, but there is no actual live demo. There is a link at the bottom of that page to "see advanced demo" which points to https://ngx-gallery.netlify.app/#/advanced which is a 404 error.  There are [a few wiki pages that link to this advanced example that no longer exists](https://github.com/search?q=repo%3AMurhafSousli%2Fngx-gallery+advanced&type=wikis)

**Comment by MurhafSousli** [comment]
Thanks for bringing this up, I fixed the link in wiki, it is https://ngx-gallery.netlify.app/#/custom-templates

**Comment by MurhafSousli** [comment]
This is fixed v12 beta `npm i ng-gallery@beta`
