### ISSUE TITLE
Imge description in Lightbox?

### ISSUE THREAD

**Issue by kamstob** [MurhafSousli/ngx-gallery#576]
#### What is the expected behavior?
I would like to add an image description in a similar way to in 'custom template' (see example: https://ngx-gallery.netlify.app/#/custom-templates). Does Lightbox provide a solution for this feature? If yes, may I have an example of usage?

Angular: 16.1.3
Angular CDK: 16.1.3
Angular CLI: 16.1.3
Typescript: 4.9.5
Gallery: 10.0.0

**Comment by MurhafSousli** [comment]
Yes, you can! https://github.com/MurhafSousli/ngx-gallery/wiki/Custom-templates-for-lightbox
