### ISSUE TITLE
add a angular pipe for protected images

### ISSUE THREAD

**Issue by Ty7ex** [MurhafSousli/ngx-gallery#582]
#### What is the expected behavior?
I want to display the protected images in my application.

#### What is the current behavior?
No image is currently displayed.

#### What are the steps to reproduce?
Take any image that requires a bearer token.

#### What is the use-case or motivation for changing an existing behavior?
I would like to use your lib in my application.

#### Which versions are you using for the following packages?
I use: "ng-gallery": "^11.0.0",

Angular: 16.2.2
Angular CDK: 16.2.1
Angular CLI: 16.2.0
Typescript: 5.1.6
Gallery: ^11.0.0

#### Is there anything else we should know?
Is there any other way or workaround to add angular custom pipe to <img [attr.src]=" '{{IMG.URL}}' | protectedImagePipe " alt="test">

**Comment by MurhafSousli** [comment]
You can implement you own custom template and define the logic you need https://github.com/MurhafSousli/ngx-gallery/wiki/Custom-Templates#galleryitemdef

**Comment by MurhafSousli** [comment]
Here you go https://stackblitz.com/edit/ngx-gallery-l7vqbt?file=src%2Fmain.ts
