### ISSUE TITLE
Constant cpu usage on idle page

### ISSUE THREAD

**Issue by jelleVandendriessche** [MurhafSousli/ngx-gallery#585]
#### What is the expected behavior?
No cpu usage once it's rendered. 

#### What is the current behavior?
<img width="921" alt="image" src="https://github.com/MurhafSousli/ngx-gallery/assets/6168612/76e99b85-b22f-425f-91e1-f38257bd0bdf">

#### What are the steps to reproduce?
On edge using the peformance monitor you can see that a constant style recals are being triggered when using a static gallery. 

#### What is the use-case or motivation for changing an existing behavior?
In some use-cases this pushed our apllication cpu usage to a constant 100%. (The gaps in the data is when switching tabs)
![image](https://github.com/MurhafSousli/ngx-gallery/assets/6168612/c345a962-0119-4b99-b1ff-c559e54a335e)
Removing the gallery or enabling the thumbs fixed this for us, but we don't want thumbs. 
On the demo page I was unable to reproduce this. 

#### Which versions are you using for the following packages?

Angular: 16.1.5
Angular CDK: 16.1.5
Angular CLI: 16.2.4
Typescript: 5.1.6
Gallery:  11.0.0

**Comment by MurhafSousli** [comment]
I released v12 beta, the core functionality is written from scratch and the technique has changed.. please try out the new version and feel free to open a new issue if you encountered any, I am closing this for now...
