### ISSUE TITLE
GalleryConfig in sub components

### ISSUE THREAD

**Issue by yosiasz** [MurhafSousli/ngx-gallery#586]
Hello @MurhafSousli 

#### What is the expected behavior?
For GalleryConfig to be able to be configured and work on sub components other than root

#### What is the current behavior?
GalleryConfig only works in root

#### What are the steps to reproduce?
 Try to implement GalleryConfig navIcon in a sub component or with href and icon dies not change

#### What is the use-case or motivation for changing an existing behavior?
Lets say I want custom navIcon for different parts of the app I want components within the app to set their own  config for that.what

#### Which versions are you using for the following packages?

Angular: ✅
Angular CDK:✅
Angular CLI:✅
Typescript:✅
Gallery: ✅

#### Is there anything else we should know?
Thanks for this amazing stuff

**Comment by yosiasz** [comment]
I believe this is the answer?
<img width="698" alt="image" src="https://github.com/MurhafSousli/ngx-gallery/assets/900951/4c9cdbbb-ebd1-471d-9c97-1ad0a1ab144d">

**Comment by MurhafSousli** [comment]
Correct, if you want set the config that applies to all gallery components, use the GALLERY_CONFIG token

**Comment by yosiasz** [comment]
Thanks @MurhafSousli .

How about this approach to apply something to only one component?

```
const config: GalleryConfig = {
  autoPlay: true
};
galleryRef.setConfig(config)
```

from here https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-config-api

<img width="255" alt="image" src="https://github.com/MurhafSousli/ngx-gallery/assets/900951/00c61132-429c-4a21-b7da-7d9817740182">

**Comment by yosiasz** [comment]
The following is not working for me in a sub component/container

```
  constructor(private gallery: Gallery) {}

  ngOnInit() {
    this.images = images;
    const config: GalleryConfig = {
      nav: false,
      navIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" class="icon__body"><g><path d="M21.855,18.482A12.85,12.85,0,0,1,20,11.994V8.006a8,8,0,0,0-16,0v3.982a12.851,12.851,0,0,1-1.855,6.494A1,1,0,0,0,3,20H21a1,1,0,0,0,.855-1.518Z"></path> <path d="M13.007,23.825a3,3,0,0,0,1.819-1.819H9.174A3,3,0,0,0,13.007,23.825Z"></path></g></svg>`,
    };

    // Get the galleryRef by id
    var galleryRef = this.gallery.ref('myGallery');
    galleryRef.setConfig(config);
```
