### ISSUE TITLE
galleryRef config not working

### ISSUE THREAD

**Issue by yosiasz** [MurhafSousli/ngx-gallery#587]
#### What is the expected behavior?

For `galleryRef.setConfig(config);` to work outside of root
per docu
https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-config-api

#### What is the current behavior?
`galleryRef.setConfig(config);` is not working in another component

#### What are the steps to reproduce?
Add the following to a non root component

```
    const config: GalleryConfig = {
      //nav: true,
      //autoHeight: true,
      imageSize: 'cover',
      //imageSize: 'cover',
      autoPlay: true,
      nav: false,
      navIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" class="icon__body"><g><path d="M21.855,18.482A12.85,12.85,0,0,1,20,11.994V8.006a8,8,0,0,0-16,0v3.982a12.851,12.851,0,0,1-1.855,6.494A1,1,0,0,0,3,20H21a1,1,0,0,0,.855-1.518Z"></path> <path d="M13.007,23.825a3,3,0,0,0,1.819-1.819H9.174A3,3,0,0,0,13.007,23.825Z"></path></g></svg>`,
    };

    // Get the galleryRef by id
    var galleryRef = this.gallery.ref('myGallery');
    galleryRef.setConfig(config);
```

#### What is the use-case or motivation for changing an existing behavior?
One might want gallery specific config and not root specific config

#### Which versions are you using for the following packages?

Angular: ☑️
Angular CDK:☑️
Angular CLI:☑️
Typescript:☑️
Gallery: ☑️

#### Is there anything else we should know?
Thanks

**Comment by MurhafSousli** [comment]
Oh, you misunderstood the docs. ofcourse it will not apply to other gallery components because this is only meant for that gallery reference. hence, the naming `galleryRef.setConfig(config);`

**Comment by yosiasz** [comment]
Got it. So if I want custom `navIcon` in one component and another custom `navIcon` i cant use this config?

**Comment by MurhafSousli** [comment]
Yes, I suggest you look at the wiki docs, the `navIcon` is only available in the global config https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-config-api
