### ISSUE TITLE
Black borders on the left/right on some configurations

### ISSUE THREAD

**Issue by nbarrett** [MurhafSousli/ngx-gallery#588]
#### What is the expected behavior?
* First of all, thanks so much @MurhafSousli for a fantastic library!
* When I choose `imageSize` = `cover`, slides should autosize so that there are no black borders on the left/right.
![image](https://github.com/MurhafSousli/ngx-gallery/assets/626941/20819f6f-bb41-4311-8ec3-7bc1c9848236)

#### What is the current behavior?

On the [ngx-ramblers](https://www.ngx-ramblers.org.uk) framework, which uses ngx-gallery as one of the rendering options: 
- when I choose `thumbPosition` = `left` [example](https://ngx-ramblers-prod-ekwg-33cbed454225.herokuapp.com/walks/weekends-away/swanage-april-2023/day-3) this happens correctly
- when I choose `thumbPosition` = `bottom` [example](https://ngx-ramblers-prod-ekwg-33cbed454225.herokuapp.com/walks/weekends-away/swanage-april-2023/day-4) the rendering problem happens

I think the first one works okay because the width is reduced to under the required viewport of `1080px`. Even if I set the width on the `gallery` component to `1080px` it makes no difference.

#### What are the steps to reproduce?

See the above links

#### What is the use-case or motivation for changing an existing behavior?

Gallery doesn't look quite as good when there are black borders, and like the author of ngx-gallery, I'm want perfection!

#### Which versions are you using for the following packages?

Angular: 16.2.9
Angular CDK: 16.2.9
Angular CLI:16.2.9
Typescript: 4.9.5
Gallery: 11.0.0

**Comment by MurhafSousli** [comment]
I cannot debug that examples you provided because autoplay is on, maybe if you provide a stackblitz

**Comment by nbarrett** [comment]
Hello again @MurhafSousli - I've turned off autoplay on those 2 examples so it should be more debugable now 👍

**Comment by MurhafSousli** [comment]
I've seen, actually you haven't set the imageSize to `cover`, it is set to `contain` by default
