### ISSUE TITLE
Thumbnails are not aligned at the start

### ISSUE THREAD

**Issue by Imorales0210** [MurhafSousli/ngx-gallery#597]
#### What is the expected behavior?
![image](https://github.com/MurhafSousli/ngx-gallery/assets/82295247/919a4b39-221e-4187-a241-363349424fb4)

#### What is the current behavior?
![image](https://github.com/MurhafSousli/ngx-gallery/assets/82295247/39d1065b-4e38-4582-83c1-1d7ab00e09ec)

#### What are the steps to reproduce?
defined images in the ts file

add this to your html file:

![image](https://github.com/MurhafSousli/ngx-gallery/assets/82295247/f53d3b8c-a77d-43df-98c5-282f66cfeb2b)

#### Which versions are you using for the following packages?

![image](https://github.com/MurhafSousli/ngx-gallery/assets/82295247/1f3730f9-c05d-4a28-9ffb-f878d8a12b25)
Gallery: "ng-gallery": "^11.0.0",

#### Is there anything else we should know?

i already put the attr thumbView in "default" but nothing is change

**Comment by MurhafSousli** [comment]
This is intended, when the size of the thumb slider is bigger than its thumbnails, it centralize them out of the box, the `thumbView` option is meant to force centralize the active item regardless of its locaiton.

To force remove the spaces on the edges, try the following in your global styles

```scss
.g-slider {
  --thumb-centralize-start-size: 0 !important;
  --thumb-centralize-end-size: 0 !important;
}
```

**Comment by Imorales0210** [comment]
Thanks it's work
