### ISSUE TITLE
Couldn't find @ngxgallery/lightbox and @ngx-gallery/gallerize

### ISSUE THREAD

**Issue by AbdooSalem** [MurhafSousli/ngx-gallery#60]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
> Linux (Mint 18.2 Cinnamon 64-bit)

I've just installed the module with npm but according to the documentation, I couldn't find
`` @ngxgallery/lightbox`` and `` @ngx-gallery/gallerize``, please update the docs..
My regards,

**Comment by MurhafSousli** [comment]
@AbdooSalem Which documentation should be updated?

**Comment by AbdooSalem** [comment]
Sorry I was mistaken,
I followed the instructions in `https://murhafsousli.github.io/ngx-gallery/#/getting-started/core`.
I installed  **ngx-gallery/core**, but I forgot to install the other two packages.

@MurhafSousli, Thank you for this great work..:)
