### ISSUE TITLE
Showing images without URL

### ISSUE THREAD

**Issue by mindarchitect** [MurhafSousli/ngx-gallery#622]
#### What is the expected behavior?
I would like to preview images before uploading them. 

#### What is the current behavior?
In order to show image, image url is required

#### What are the steps to reproduce?

This is a question, not bug.

#### What is the use-case or motivation for changing an existing behavior?
Image preview;

#### Which versions are you using for the following packages?

Angular: 18
Angular CDK: 18
Angular CLI: 18
Typescript: 5.5
Gallery: 12

**Comment by MurhafSousli** [comment]
I think you can use BLOB string as src as well.

**Comment by mindarchitect** [comment]
> I think you can use BLOB string as src as well.

Thank you.

Could you please suggest how can I do it in following simple scenario: 

I receive file object (type FIle). The src property of GalleryItemModel has following mixed type:

GalleryItemModel

src?: string | {
        url: string;
        type: string;
    }[];
    
I tried converting file to string. I tried reading file using file reader this.fileReader.readAsDataURL(file) and assigning the result src through string casting. Nothing works.

How can i assign blob to src string in this case?

Thank You.

**Comment by mindarchitect** [comment]
Figured out. Thank you.
