### ISSUE TITLE
[LIGTBOX] Lazy loading image content on thumbnail click in lightbox

### ISSUE THREAD

**Issue by mindarchitect** [MurhafSousli/ngx-gallery#625]
Is it possible to lazy load image content on thumbnail click in lightbox?

Angular: 18
Angular CDK: 18
Angular CLI: 18
Typescript: 5.4
Gallery: latest

**Comment by MurhafSousli** [comment]
Yes, you can set the input `<gallery loadingStrategy="lazy">`
