### ISSUE TITLE
v2.0.0 - gestures (swiping) do not work on ios

### ISSUE THREAD

**Issue by maku** [MurhafSousli/ngx-gallery#64]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
- [ ] feature request
- [ ] question
```

### Versions
using @ngx-gallery/core version 2.0.0-beta.4

### Repro steps
Here is a small and simple demo app (https://angular-g6hsdp.stackblitz.io/.)
The gestures (swiping) work for me on desktop browser and also on an android device.
But NOT on ios devices.

### Desired functionality
Gestures (swiping) should also work on ios

**Comment by MurhafSousli** [comment]
@maku demo is showing 404

**Comment by maku** [comment]
@MurhafSousli sorry the correct url is https://stackblitz.com/edit/angular-ngx-gallery-test (or https://angular-ngx-gallery-test.stackblitz.io)
