### ISSUE TITLE
load a gallery but open(i) doesn't show images

### ISSUE THREAD

**Issue by bpalacio** [MurhafSousli/ngx-gallery#69]
Hi,

i implemented the gallery in my own project, the gallery worked initialy, but today the open function of the ligthbox stop working, the ligthbox opened but doesn't show any images. the counter is in 0

![image](https://user-images.githubusercontent.com/22058906/37301649-cd85c9c6-25ee-11e8-9f11-41283e0e360f.png)

**Comment by MurhafSousli** [comment]
Please fill the issue template and add the code you use. closing as it does not follow the issue format
