### ISSUE TITLE
Gallerize with *ngFor does not work

### ISSUE THREAD

**Issue by danfergo** [MurhafSousli/ngx-gallery#70]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Linux a4887eb4a802 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 GNU/Linux

### Versions
node v8.9.0
npm 5.5.1

### Repro steps
``` html
<div *ngFor="let item of items">
     <div [gallerize]="'item-gallery-'+item.id" [innerHTML]='item.content'> </div>
</div>
```

### The log given by the failure
No error, simply does not work. 
The ` gallerizer$.pipe(debounceTime(300), ... ` is only called for the first *ngFor element and, as a consequence, clicking the item images results in nothing.

### Mention any other details that might be useful
The number of images in each item is variable, having no images in the first items.
Also, I'm using this HTML at a child module component so I've imported 
```
        GalleryModule.forRoot(),
        LightboxModule.forRoot(),
```
At the parent module, and `GallerizeModule` at the child module.

**Comment by MurhafSousli** [comment]
In this [stackblitz](https://stackblitz.com/edit/ngx-gallery?file=app%2Fapp.component.ts) It uses `*ngFor` and it works properly.
Can you reproduce your issue?

**Comment by danfergo** [comment]
There it is.
https://stackblitz.com/edit/ngx-gallery-64sgmz?file=app%2Fapp.component.html

**Comment by MurhafSousli** [comment]
@danfergo It seems that you did not add ` changeDetection: ChangeDetectionStrategy.OnPush` to your component which caused to an infinite loop.

Gallerize uses `ngAfterContentChecked` to re-look for images when content changes. but here it is firing itself when you the strategy is in default mode.

here is a working [stackblitz](https://stackblitz.com/edit/ngx-gallery-sf2wpt?file=app%2Fapp.component.ts)

**Comment by danfergo** [comment]
Oh allright, I didn't saw that. Thanks a lot!
