### ISSUE TITLE
probaby a bug in ipad

### ISSUE THREAD

**Issue by wilson0506** [MurhafSousli/ngx-gallery#78]
![image](https://user-images.githubusercontent.com/32795531/38450671-6f8b9a7e-3a54-11e8-9a96-f2eac57f0552.jpg)
Rich gallery example, it fail to show up in ipad

**Comment by MurhafSousli** [comment]
It seems to be working
Go to http://www.responsimulator.com/?url=murhafsousli.github.io%2Fngx-gallery%2F%23%2Fadvanced and click on the iPad button

![image](https://user-images.githubusercontent.com/8130692/38452622-6395fdc6-3a50-11e8-8763-a5b11599d179.png)

**Comment by wilson0506** [comment]
how to debug it in ipad, please teach me the way and i can tell u

**Comment by MurhafSousli** [comment]
I really don't know. google it!
