### ISSUE TITLE
aot build issue

### ISSUE THREAD

**Issue by elvirdolic** [MurhafSousli/ngx-gallery#82]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Repro steps

ng build --aot

2163959Z [0m[1m[31mERROR in node_modules\@ngx-gallery\core\ngx-gallery-core.d.ts.ɵe.html(11,22): : Object is possibly 'undefined'.[39m[22m[0m
2018-04-27T13:09:14.2164327Z > paldesk@1.0.0 build-aot C:\agent\_work\1\s
2018-04-27T13:09:14.2164790Z [0m[1m[31mnode_modules\@ngx-gallery\core\ngx-gallery-core.d.ts.ɵj.html(1,24): : Object is possibly 'undefined'.[39m[22m[0m
2018-04-27T13:09:14.2165071Z > ng build --aot
2018-04-27T13:09:14.2165610Z [0m[1m[31mnode_modules\@ngx-gallery\core\ngx-gallery-core.d.ts.ɵj.html(1,24): : Object is possibly 'undefined'.[39m[22m[0m

**Comment by MurhafSousli** [comment]
Add your usage code!

**Comment by ivanblazevic** [comment]
@MurhafSousli no need for code usage - just turn on strictNullChecks in any project and you get "Object is probably undefined" error. I have forked your repository and created PR for this issue: https://github.com/ivanblazevic/ngx-gallery/tree/82

**Comment by elvirdolic** [comment]
@MurhafSousli can you reproduce this our side. As disabling strictNullCheck for libs doesn't work somehow in this case we will need this PR change? Any chance to have this in?

**Comment by MurhafSousli** [comment]
@elvirdolic I couldn't get a reproduction for this issue.

**Comment by ivanblazevic** [comment]
@MurhafSousli to reproduce the issue:
1. create new app via angular cli
2. npm install @ngx-gallery/core
3. set strictNullCheck in tsconfig.app.json
4. ng build --aot

**Comment by MurhafSousli** [comment]
Why don't keep it strickNullCheck to false as the CLI brings it?

**Comment by elvirdolic** [comment]
@MurhafSousli because it's supported by typeScript. Angular has the flag to skip this for libs, but this is not working somehow with your lib: https://github.com/angular/angular/issues/21390

We thought that it would be faster to fix it here then to wait for a angular solution.

**Comment by MurhafSousli** [comment]
This complicates the usage of variables in the lib components. but you can use https://github.com/ivanblazevic/ngx-gallery/tree/82 code which fixes it in your app

**Comment by elvirdolic** [comment]
@MurhafSousli we are doing this but this is not a perfect solution as we have always to update  our fork only because of this 3 lines of changes. I can understand your point but it would be glad to have this in the main repo. Other users will also have this problem if they are using strictNullChecks (what is more or less a standard).

**Comment by ivanblazevic** [comment]
> This complicates the usage of variables in the lib components. but you can use https://github.com/ivanblazevic/ngx-gallery/tree/82 code which fixes it in your app

these are the required changes for fixing this problem: https://github.com/MurhafSousli/ngx-gallery/pull/83/files

@MurhafSousli  my question is how this complicates usage of variables in the lib components > basically these are just additional checks in *ngIf ?

**Comment by MurhafSousli** [comment]
Guys. this is a known bug in angular https://github.com/angular/angular/issues/21390. it is not related to this plugin, remove the `strictNullChecks` or wait for the fix from Angular

Dup #201
