### ISSUE TITLE
console error reports hammerjs not defined without `import hammerjs`?

### ISSUE THREAD

**Issue by shellphon** [MurhafSousli/ngx-gallery#84]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
- [ ] question
```
Hi, I am trying to use lightbox of ngx-gallery, without import hammerjs, the console of Chrome reports Hammer not defined. 

![image](https://user-images.githubusercontent.com/1677147/39561458-55c0759a-4ed8-11e8-97a0-453c119c62b4.png)

After import hammerjs, the error never appears.

But do I really need to import hammerjs for usage of lightbox without gestures?

And there's something wrong in the wiki [>>here](https://github.com/MurhafSousli/ngx-gallery/wiki/Core)

> $ npm install --save hammer.js

it may be 

> $ npm install --save hammerjs 

`hammer.js` is not in npm.

Hope your reply~

--- update ---

I found that the default value of gestures in Gallery is true.

If I set this,  the error never appears without import hammerjs.

~~~
 GalleryModule.forRoot({
      gestures:false
    }),
~~~

### OS and Version?

Windows 7

### Versions

~~~
λ Angular CLI: 1.5.4 Node: 7.8.0 OS: win32 x64 
Angular: 5.2.10 
... animations, common, compiler, compiler-cli,  core, forms 
... http, language-service, platform-browser 
... platform-browser-dynamic, router  
@angular/cdk: 5.2.4 
@angular/cli: 1.5.4 
@angular-devkit/build-optimizer: 0.0.42 
@angular-devkit/core: 0.5.6 
@angular-devkit/schematics: 0.0.52 
@ngtools/json-schema: 1.1.0 
@ngtools/webpack: 1.8.4 
@schematics/angular: 0.1.17 
typescript: 2.4.2 
webpack: 3.8.1
~~~

**Comment by JacobSamro** [comment]
This is happening on ngx-gallery v4.0.0 . Even if the gestures are set to false.
