### ISSUE TITLE
Poster attribute for <video>

### ISSUE THREAD

**Issue by gusarov** [MurhafSousli/ngx-gallery#85]
This is cool gallery, I'm already using mixed self-hosted videos among with YouTube... And this is where it looks sad - `VideoItem` is black until played, while `YoutubeItem` have a decent automatic poster.
Can you generate poster attribute for `<video>` from `VideoItem`? I'll be fine if it show thumbnail as a poster, but ideally, I think it should be a configurable 3rd option of `VideoItem` constructor

**Comment by MurhafSousli** [comment]
@gusarov thanks, youtube provides thumbnail, but normal HTML5 video doesn't. so you can give it a thumbnail manually

```ts
const videoItem = new VideoItem(videoSrc, thumbSrc)
```

**Comment by gusarov** [comment]
Yep, I did, but I'm not about thumbnail, I'm about poster (the jpg cover for video before it loads for the first time)

**Comment by gusarov** [comment]
![image](https://user-images.githubusercontent.com/1462777/39671158-a67b834a-511b-11e8-9510-0853c95049d8.png)

**Comment by MurhafSousli** [comment]
In the demo https://murhafsousli.github.io/ngx-gallery/#/mixed the video had a poster, but no problem will add this the next update

**Comment by gusarov** [comment]
```<video _ngcontent-c11="" controls="" src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"></video>```
I guess this is just a first frame of video that browser uses automatically. Looks like in my case first frames are always black.
