### ISSUE TITLE
Lightbox: Fullscreenmode on Safari Mobile phone

### ISSUE THREAD

**Issue by pharindoko** [MurhafSousli/ngx-gallery#86]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
IOS, Safari

### Versions
Angular 5.2.10
Angular CLI 1.7.4

### Repro steps
Set lightbox in config to fullscreen.
Open in mobile browser in this case safari.

### The log given by the failure
=> Close button is hidden through navbar of safari

### Desired functionality
Positioning of close button in combination with fullscreen mode for lightbox has to be adapted.
My proposal would be to use a media query in a first step and adapt the position of the close button.

**Comment by MurhafSousli** [comment]
@pharindoko Actually that how it is right now.
https://github.com/MurhafSousli/ngx-gallery/blob/4ae1b39125be8bc7e335d42d48f76cc1d6e3edd2/lib/core/src/styles/lightbox.scss#L23-L45

It is fullscreen by default on mobile. the `.fullscreen` class is useful to force fullscreen on large screens (desktop)

it seems that `height: 100vh` doesn't look properly on Safari but it is good on chrome. try to play with css and if you find a better solution, let me know.

**Comment by MurhafSousli** [comment]
It turns out there is no fix for this, more [info](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
