### ISSUE TITLE
Lightbox: Lazy loading images

### ISSUE THREAD

**Issue by pharindoko** [MurhafSousli/ngx-gallery#87]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X] question
```

### Repro steps
When you open up the light box - all src images given in item array as e.g. ImageItem[] will be directly loaded in the browser

### The log given by the failure
It`s not necessary to load all images at once. 
I would like to be able to use lazy loading strategy

### Desired functionality
Only a few images will be loaded instead of all.
When image is previous or next image it should appear hidden in the viewport and then be loaded automatically.

**Comment by MurhafSousli** [comment]
This is not possible with the recent version. try version 1.0.1 for that
In version 2 slides are preloaded for better sliding experience especially on mobile.

![image](https://user-images.githubusercontent.com/8130692/39703519-f77636c8-5210-11e8-93bc-751c8c928fc3.png)

**Comment by ayazhussein** [comment]
Hmm, I'm having an issue where directive [lazyImage] is not found

**Comment by pcaquatic** [comment]
Hi i am trying to add many images (~200) and the image is not showing properly and the slide is very sluggish. 
![image](https://user-images.githubusercontent.com/40566553/41847814-f8d2b44c-78ad-11e8-9967-4bdd7b9de424.png)

To reproduce:

  ngOnInit() {
    // This is for Basic example
    this.items = this.imageData.map(item => {
      return new ImageItem(item.srcUrl, item.previewUrl);
    });

    for (let index = 0; index < 200;  index++) {
      this.items.push(new ImageItem(`https://picsum.photos/1000/667/?image=${index + 1}`, `https://picsum.photos/600/400/?image=${index + 1}`));
      
    }
..
}

Any idea how to improve the performance?

**Comment by MurhafSousli** [comment]
The lazy load functionality will be available in the next update, which is coming soon

**Comment by MurhafSousli** [comment]
In version 3, there is a new option in gallery config `loadStrategy` also available as gallery input `[loadStrategy]`, which accept the following:

**default**: loads current, prev and next items
**lazy**: load only the current item
**preload**: load all items

**Comment by pharindoko** [comment]
Thanks Murhaf,

I‘ll try it today and will let you know about the result ....

**Comment by pcaquatic** [comment]
Hi Murhaf,
The issue still exists.
I modify the basic example here:
https://stackblitz.com/edit/ngx-gallery?file=src%2Fapp%2Fhome%2Fhome.component.html
I added  **[loadingStrategy]="'lazy'"**

```
<div class="basic-container">
	<h2>Basic Example</h2>
	<gallery id="basic-test" [items]="items" [loadingStrategy]="'lazy'" [loop]="true" [dots]="true" [thumbPosition]="'top'"></gallery>
</div>
```
and in the ts file
https://stackblitz.com/edit/ngx-gallery?file=src%2Fapp%2Fhome%2Fhome.component.ts
I loaded 300 files (on line 28)

```
  ngOnInit() {
    // Load items into the gallery component
    this.items = this.imageData.map(item => {
      return new ImageItem({ src: item.srcUrl, thumb: item.previewUrl });
    });

  // added more images to the gallery
    for (let index = 0; index < 300;  index++) {
  this.items.push(new ImageItem({ src:`https://picsum.photos/1000/667/?image=${index + 1}`, thumb: `https://picsum.photos/300/200/?image=${index + 1}`}));
    }

    // Load items into the lightbox gallery ref
    this.gallery.ref('lightbox').load(this.items);
  }
}
```
The gallery doesn't show the image correctly (see the snapshot below)
![image](https://user-images.githubusercontent.com/40566553/42434671-97ac0496-8386-11e8-92b9-979315164e62.png)


If I load 200 images or below, it is fine on my browser. 
Any idea if I am doing it wrongly? 

Thanks

**Comment by MurhafSousli** [comment]
Why don't you fork that stackblitz and give me the reproduction link?

**Comment by pcaquatic** [comment]
Hi Murhaf, 
here you go:
https://stackblitz.com/edit/ngx-gallery-reb2et

Thanks

**Comment by MurhafSousli** [comment]
@pcaquatic The gallery reserves each item width so even if the images are not loaded the slider width is equal to total number of items mutliplies by the gallery width

And each browser has a maximum width limit for an HTMLElement which can be found [here](https://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties)

When you added 300, the slider width became 300 * item width.. which exceeded the limit allowed by the browser.

I tried 200 items it worked, check this [stackblitz](https://stackblitz.com/edit/ngx-gallery-f7gear?file=src%2Fapp%2Fhome%2Fhome.component.ts)

Your use case is kinda weird! Honestly, I don't think a user would go through 300 images using the gallery!

Anyway, make sure you set a maximum width of your gallery so that if it multiples with 300 it stays within the browser maximum width limit

**Comment by pharindoko** [comment]
Hey Murhaf - I only use lightbox but it seems that I have the same issue.
How to set the maximum width or what kind of value is important to fix it.

**Comment by pharindoko** [comment]
Hello,

Can someone explain me on which element the maximum width must be set equal to the image count ? :)
I use the Lightbox Module

**Comment by MurhafSousli** [comment]
@pharindoko I just explained in my comment above.. I don't know the maximum width, each browser has a different one, you can read them [here](https://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties) or  google it!!

For example, if you have 200 items in your gallery and the gallery width is 500px  => then the sider width is 500px * 200 which is 10000px

**Comment by pharindoko** [comment]
@MurhafSousli  👍 
Answer accepted :)
