### ISSUE TITLE
Gallery: Cant't show the image correctly.

### ISSUE THREAD

**Issue by bcheok** [MurhafSousli/ngx-gallery#88]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X ] question

### OS and Version?
> chrome 64.0.3282.140 

### Versions
> angular/core ^5.2.6"
> ngx-gallery/core ^2.0.3"

### Repro steps
I was complete to install, but when it use to my app, it can't show the image.
![screen shot 2018-05-09 at 12 02 12 pm](https://user-images.githubusercontent.com/5170439/39795160-dc88c9e0-5380-11e8-8156-e9d8c156c784.png)
I found the "slides" class div alway set width is 0, I don't know what problem with that.

Below is the component code.
```
import {Component, OnInit, ViewChild} from '@angular/core';
import { Gallery, GalleryItem, ImageItem } from '@ngx-gallery/core';
import { Lightbox } from '@ngx-gallery/lightbox';

@Component({
  selector: 'app-gallery-box',
  templateUrl: './gallery-box.component.html',
  styleUrls: ['./gallery-box.component.scss']
})
export class GalleryBoxComponent implements OnInit {

  items: GalleryItem[];

  imageData = [
    {
      srcUrl: 'https://preview.ibb.co/jrsA6R/img12.jpg',
      previewUrl: 'https://preview.ibb.co/jrsA6R/img12.jpg'
    },
    {
      srcUrl: 'https://preview.ibb.co/kPE1D6/clouds.jpg',
      previewUrl: 'https://preview.ibb.co/kPE1D6/clouds.jpg'
    },
    {
      srcUrl: 'https://preview.ibb.co/mwsA6R/img7.jpg',
      previewUrl: 'https://preview.ibb.co/mwsA6R/img7.jpg'
    },
    {
      srcUrl: 'https://preview.ibb.co/kZGsLm/img8.jpg',
      previewUrl: 'https://preview.ibb.co/kZGsLm/img8.jpg'
    }
  ];

  constructor(public gallery: Gallery, public lightbox: Lightbox) { }

  ngOnInit() {

    this.items = this.imageData.map(item => {
      return new ImageItem(item.srcUrl, item.previewUrl);
    });
  }

}

```

It was no any error message show on, and the image can correctly link.

**Comment by bcheok** [comment]
and the html code

> <div class="gallery-box">
>   <div class="gallery-box-content">
>     <div class="basic-container">
>       <h2>Basic Example</h2>
>       <gallery id="basic-test" [items]="items"></gallery>
>     </div>
>   </div>
> </div>

**Comment by bcheok** [comment]
```
<div class="gallery-box">
  <div class="gallery-box-content">
    <div class="basic-container">
      <h2>Basic Example</h2>
      <gallery id="basic-test" [items]="items"></gallery>
    </div>
  </div>
</div>
```

**Comment by MurhafSousli** [comment]
First, do you want a lightbox? or just a gallery element?
The gallery element **MUST** have a height, [basic usage](https://github.com/MurhafSousli/ngx-gallery/wiki/Basic-Usage)

```ts
<div class="gallery-box">
  <div class="gallery-box-content">
    <div class="basic-container">
      <h2>Basic Example</h2>
      <gallery id="basic-test" style="height: 500px" [items]="items"></gallery>
    </div>
  </div>
</div>
```

**Comment by bcheok** [comment]
Thank for your reply!

I don't need the lightbox. 

I had tried this solution.
![screen shot 2018-05-09 at 3 40 56 pm](https://user-images.githubusercontent.com/5170439/39801980-76a7e150-539f-11e8-9881-6dce1238a1fa.png)

But it still don't show the picture.
:(

**Comment by bcheok** [comment]
I success now!! I put the `@import '~@ngx-gallery/core/styles/gallery'; ` in wrong place. Thank you~ :)
