### ISSUE TITLE
Infinity Scrolling

### ISSUE THREAD

**Issue by cgilbe27** [MurhafSousli/ngx-gallery#98]
**Is your feature request related to a problem? Please describe.**
Is it possible to scroll infinitely with this plugin? I have loop=true set but it doesnt actually loop

**Describe the solution you'd like**
loop to loop infinitely

**Comment by cgilbe27** [comment]
Seems as if https://github.com/MurhafSousli/ngx-gallery/blob/master/demo/src/app/gallery/core/components/gallery.component.ts Doesnt include the config for looping

**Comment by cgilbe27** [comment]
Loop is also missing here: https://github.com/MurhafSousli/ngx-gallery/blob/master/demo/src/app/gallery/core/utils/gallery.default.ts

**Comment by cgilbe27** [comment]
Any update for this?

**Comment by MurhafSousli** [comment]
The `loop` option can be set in 

```ts
galleryRef.setConfig({ loop: true})

// or 

GalleryModule.forRoot({ loop: true })
```

In version `3.0.0-beta.1`, it is also available as an input in `<gallery [loop]=true></gallery>`
